### ISSUE TITLE
[BUG]:Helm install fails with Error: template: csi-unity/templates/node.yaml:142:85: executing "csi-unity/templates/node.yaml" at <.Values.images.driver>:nil pointer evaluation interface{}.driver

### ISSUE THREAD

**Issue by guy7711** [dell/csm#100]
Installing with helm intall produces the following error:
Error: template: csi-unity/templates/node.yaml:142:85: executing "csi-unity/templates/node.yaml" at <.Values.images.driver>:nil pointer evaluation interface{}.driver

**To Reproduce**
1. get all dependecies and upload the to local repository
2. update values file, driver-image.yaml, k8s files with local repository's pull command link 
3. helm package and upload
4. helm install

**Expected behavior**
image should be pulled as is happening with all other apps deployed from the repository

**Screenshots**
cannot provide

**Logs**
cannot provide

**System Information (please complete the following information):**
 - Windows 10
 - Helm v3.6.3
 - Kubernetes Version 1.2
 - Tanzu Kubernetes Cluster v1.20.7

**Additional context**
The Value of the image location is definetly valid, this is ot the first deployment on this cluster from this repository.
docker pull with the same link works locally as well.

**Comment by prablr79** [comment]
@guy7711 can you share manifest file that populated / provided an input for the driver installation ?  i see you are mentioning Windows 10 as platform just an FYI we don't support windows OS yet, Please do refer support details here https://dell.github.io/csm-docs/docs/csidriver/

**Comment by prablr79** [comment]
@guy7711 can you also share which version of CSI Driver that you are trying to install ?

**Comment by guy7711** [comment]
im installing v2.0.0, now trying with v2.1.0 - though im unable to run docker pull for this version, it only works with "latest" tag

docker pull dellemc/csi-unity:v2.1.0
Error response from daemon: manifest for dellemc/csi-unity:v2.1.0 not found: manifest unknown: manifest unknown

about winOS, i ment that my personal workstation from which i'm running the commands is windows 10 with git bash mintty based.

**Comment by guy7711** [comment]
> 
> 
> @guy7711 can you share manifest file that populated / provided an input for the driver installation ? i see you are mentioning Windows 10 as platform just an FYI we don't support windows OS yet, Please do refer support details here https://dell.github.io/csm-docs/docs/csidriver/

unfortunately i cannot share any files, i'm insatlling it in an airgapped site.

**Comment by shanmydell** [comment]
> im installing v2.0.0, now trying with v2.1.0 - though im unable to run docker pull for this version, it only works with "latest" tag
> 
> docker pull dellemc/csi-unity:v2.1.0 Error response from daemon: manifest for dellemc/csi-unity:v2.1.0 not found: manifest unknown: manifest unknown
> 
> about winOS, i ment that my personal workstation from which i'm running the commands is windows 10 with git bash mintty based.


@guy7711 : v2.0.0 works with latest tag and v2.1.0 works with nightly tag.

**Comment by prablr79** [comment]
@guy7711 our suggestion to use Released build tag which v2.0.0 and v2.1.0 still under development.

**Comment by prablr79** [comment]
@guy7711 this tag is not released yet docker pull dellemc/csi-unity:v2.1.0.  hence closing this bug.

**Comment by guy7711** [comment]
> 
> 
> @guy7711 this tag is not released yet docker pull dellemc/csi-unity:v2.1.0. hence closing this bug.

this is not relevant to the BUG, do not close it, i just mentioned that i'm going to try v2.1.0 as well, if it's not released yet, then im gonna stick with v2.0.0 and the BUG is still there.

please refer to the ERROR mentioned.
Error: template: csi-unity/templates/node.yaml:142:85: executing "csi-unity/templates/node.yaml" at <.Values.images.driver>:nil pointer evaluation interface{}.driver

**Comment by prasar6** [comment]
@guy7711 - Do ensure that you are pointed to the right code in github(pull from v2.0.0 tag instead of main branch)
`git clone -b v2.0.0 https://github.com/dell/csi-unity.git`
Refer this section https://dell.github.io/csm-docs/docs/csidriver/installation/helm/unity/#install-csi-driver

**Comment by prablr79** [comment]
@guy7711 sorry , we will help you on this bug, please share your observation

**Comment by shanmydell** [comment]
@guy7711 : Yes this is a latest issue, This issue has been already reported https://github.com/dell/csm/issues/99 
and fixed as part of https://github.com/dell/csi-unity/pull/32, Please pull the latest code from main and let us know if you are still facing the issue.

**Comment by prablr79** [comment]
@guy7711 i guess this due to change in version required in https://github.com/dell/csi-unity/blob/main/helm/csi-unity/driver-image.yaml, please change image as v2.0.0 then you should be able install the driver.

**Comment by guy7711** [comment]
i will try again as suggested above and update soon, thanks for the answers

**Comment by guy7711** [comment]
Hi,
The issue was not resolved, i ran git clone -b v2.0.0 https://github.com/dell/csi-unity.git and cleared the files,
editted all values.yaml files, including the drivers files and added the repository URL path.

still, same issue

**Comment by guy7711** [comment]
i found the problem, there is an issue with the helm chart. when i edit the node-template.yaml file, adding the images url manually, it doesnt complain and move forward with the same error for the next image - same error different line (195:91)

apparently there is a problem with the helm chart file links

**Comment by shanmydell** [comment]
@guy7711 : Have you tried git clone https://github.com/dell/csi-unity.git the latest branch from main. Could you please try and update on the same.

**Comment by guy7711** [comment]
Fixed the issue by doing the following:

Copied all images: pointers from the relevant k8s-1.20-values.yaml and added the image from driver-image.yaml as well to:
values.yaml.

helm install worked.

**Comment by prablr79** [comment]
@guy7711 glad to hear that your setup is working now. hope are ok to close this issue ?

**Comment by prablr79** [comment]
Thanks for connecting with us, happy to help as always closing the defect now.  if you need any further assistance please do connect us in SLACK https://app.smartsheet.com/b/form/e99b4d2da13e42518df4d3307c010f47
