### ISSUE TITLE
[BUG]: karavi-metrics-powerscale pod gets an segmentation violation error during start

### ISSUE THREAD

**Issue by N1K68** [dell/csm#1019]
### Bug Description

After installing the CSM CSI driver for PowerScale version 2.8.0 the karavi-metrics-powerscale pod gets an segmentation violation error during start.  

### Logs

time="2023-10-25T13:21:52Z" level=warning msg="endpoint port is empty, use default EndpointPort: 8080"
time="2023-10-25T13:21:52Z" level=warning msg="IsiPath is empty, use defaultIsiPath: /ifs/data/csi"
time="2023-10-25T13:21:52Z" level=warning msg="IsiVolumePathPermissions is empty, use defaultIsiPermission: 0777"
time="2023-10-25T13:21:52Z" level=info msg="setting client options" authtype=1 endpoint="https://sust070a-01-325.sebank.se:8080" insecure=true username=d827724601@corp1.ad1.seb.net verbose=0
I1025 13:21:52.572983       1 leaderelection.go:248] attempting to acquire leader lease karavi/karavi-metrics-powerscale...
I1025 13:22:10.053555       1 leaderelection.go:258] successfully acquired lease karavi/karavi-metrics-powerscale
time="2023-10-25T13:22:12Z" level=info msg="function duration" duration="34.859µs" function=gatherClusterPerformanceStatsMetrics
time="2023-10-25T13:22:12Z" level=info msg="function duration" duration="3.668µs" function=pushClusterPerformanceStatsMetrics
time="2023-10-25T13:22:12Z" level=info msg="function duration" duration=112.605258ms function=ExportClusterPerformanceMetrics
time="2023-10-25T13:22:22Z" level=info msg="function duration" duration="10.908µs" function=gatherClusterCapacityStatsMetrics
time="2023-10-25T13:22:22Z" level=info msg="function duration" duration="3.436µs" function=pushClusterCapacityStatsMetrics
time="2023-10-25T13:22:22Z" level=info msg="function duration" duration=105.993103ms function=ExportClusterCapacityMetrics
time="2023-10-25T13:22:22Z" level=info msg="function duration" duration=8.757663ms function=ExportQuotaMetrics
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x125bc3b]

goroutine 1 [running]:
github.com/dell/csm-metrics-powerscale/internal/k8s.VolumeFinder.GetPersistentVolumes({{0x19c80e0, 0xc000011f80}, {0xc00003f780, 0x1, 0x1}, 0xc00045ce80}, {0x0?, 0x0?})
        /viewsvn/lovip262/jenkins/workspace/CSM/csm-observability/Release_Activities_Observability/csm-metrics-powerscale/internal/k8s/volume_finder.go:84 +0x51b
github.com/dell/csm-metrics-powerscale/internal/service.(*PowerScaleService).ExportQuotaMetrics(0xc000090600, {0x19de150?, 0x25702e0})
        /viewsvn/lovip262/jenkins/workspace/CSM/csm-observability/Release_Activities_Observability/csm-metrics-powerscale/internal/service/service.go:145 +0x142
github.com/dell/csm-metrics-powerscale/internal/entrypoint.Run({0x19de150, 0x25702e0}, 0xc0000905a0, {0x19ccfe0?, 0xc000143da0}, {0x19d2880, 0xc000090600})
        /viewsvn/lovip262/jenkins/workspace/CSM/csm-observability/Release_Activities_Observability/csm-metrics-powerscale/internal/entrypoint/run.go:146 +0x722
main.main()
        /viewsvn/lovip262/jenkins/workspace/CSM/csm-observability/Release_Activities_Observability/csm-metrics-powerscale/cmd/metrics-powerscale/main.go:141 +0x974

### Screenshots

![image](https://github.com/dell/csm/assets/104078640/dc6c9079-e5f2-426e-9dbb-48aa9e9ae3fa)

### Additional Environment Information

The configuration we are using are:
[csm-isilon.txt](https://github.com/dell/csm/files/13167213/csm-isilon.txt)

### Steps to Reproduce

Install the CSM CSI driver for PowerScale version 2.8.0 and enable the modules, metrics-powerscale,  otel-collector , topology. 

### Expected Behavior

I'm expects the karavi-metrics-powerscale pod to be able start up. 

### CSM Driver(s)

CSIDRIVERTYPE: isilon CONFIGVERSION : v2.8.0

### Installation Type

Dell Container Storage Modules 1.3.0

### Container Storage Modules Enabled

isilon v2.8.0
resiliency v1.7.0
observability v1.6.0

### Container Orchestrator

OpenShift 4.12.31

### Operating System

RHEL 8.6

**Comment by rajendraindukuri** [comment]
Hi @N1K68 Can you please provide info on if there are any unbound PVs in your env that belong to PowerScale?

**Comment by N1K68** [comment]
Hi,

No there is no unbound or bound PVs in the env that belong to PowerScale.

**Comment by N1K68** [comment]
@rajendraindukuri 

Hi, I have now uploaded the output of the get commands that you asked for.

[pv-all.txt](https://github.com/dell/csm/files/13247168/pv-all.txt)
[pvc-all.txt](https://github.com/dell/csm/files/13247170/pvc-all.txt)

**Comment by rajendraindukuri** [comment]
Hi @N1K68 ,
Thanks for sharing the info. As per the details shared, I see few PV s in "Available" status and are not bound by any PVC.
Can you please check by deleting these PV s or by binding them to any PVC s?

![image](https://github.com/dell/csm/assets/82365588/bda0219b-ba6c-46e4-95e7-d22f2fa84d33)


Thanks
Rajendra

**Comment by N1K68** [comment]
Hi @rajendraindukuri,

I have now bound the PVs that was in status "Available" to PVCs and the karavi-metrics-powerscale pod now seems to be able to start. I'm not sure what conclusion to draw from this however. Since there will be PV's in status  "Available" in all of our clusters. 

Regards // Niklas

**Comment by rajendraindukuri** [comment]
Hi @N1K68 ,
This is a bug. Will create a ticket to correct the same. 

Thanks

**Comment by shefali-malhotra** [comment]
Issue is fixed in latest code . Will be available as part of CSM 1.9 release .
