### ISSUE TITLE
[QUESTION]: Does PowerScale CSM Replication Module supports SyncIQ encryption.

### ISSUE THREAD

**Issue by anurajpd** [dell/csm#1025]
### How can the Team help you today?

**Details: ?**

**Comment by santhoshatdell** [comment]
Hi @anurajpd 

Replication module does support SyncIQ encryption. Please refer to these CSM docs:
https://dell.github.io/csm-docs/v1/replication/deployment/powerscale/#synciq-encryption
https://dell.github.io/csm-docs/v1/replication/deployment/powerscale/#synciq-encryption-1

Thanks!

**Comment by brittup** [comment]
Yes, you would just need to establish the SIQ encryption between the two PowerScale OneFS clusters before creating any SIQ policies. This would be standard OneFS setup.

**Comment by anurajpd** [comment]
Thank you. Can you please confirm the array secret format with replicationID.

Production Cluster SyncIQ Certificates
ps01-1# isi sync certificates server view 809c57b | grep -i id:
          ID: 809c57b723f765b33a4a1a9905fd5837c12ae0ebe5f75ffd5aa3353cd83536e8
ps01-1# isi sync certificates peer view 1e3def2 | grep -i id:
          ID: 1e3def272e919debfb3cb5bfd1a8de2be09d4b0dfe9a0af1b3b26eab16477e80

DR Cluster SyncIQ Certificates
ps02-3# isi sync certificates server view 1e3def2 | grep -i id:
          ID: 1e3def272e919debfb3cb5bfd1a8de2be09d4b0dfe9a0af1b3b26eab16477e80
ps02-3# isi sync certificates peer view 809c57b | grep -i id:
          ID: 809c57b723f765b33a4a1a9905fd5837c12ae0ebe5f75ffd5aa3353cd83536e8

Production Cluster Array Secret 
isilonClusters:
  - clusterName: "ps01"
    username: "csmadmin"
    password: "P@ssw0rd123"
    endpoint: "ps01.vdi.xtremio"
    replicationCertificateID: "809c57b723f765b33a4a1a9905fd5837c12ae0ebe5f75ffd5aa3353cd83536e8"
  - clusterName: "ps02"
    username: "csmadmin"
    password: "P@ssw0rd123"
    endpoint: "ps02.vdi.xtremio"
    replicationCertificateID: "1e3def272e919debfb3cb5bfd1a8de2be09d4b0dfe9a0af1b3b26eab16477e80"

DR Cluster Array Secret
isilonClusters:
  - clusterName: "ps01"
    username: "csmadmin"
    password: "P@ssw0rd123"
    endpoint: "ps01.vdi.xtremio"
    replicationCertificateID: "809c57b723f765b33a4a1a9905fd5837c12ae0ebe5f75ffd5aa3353cd83536e8"
  - clusterName: "ps02"
    username: "csmadmin"
    password: "P@ssw0rd123"
    endpoint: "ps02.vdi.xtremio"
    replicationCertificateID: "1e3def272e919debfb3cb5bfd1a8de2be09d4b0dfe9a0af1b3b26eab16477e80"

**Comment by santhoshatdell** [comment]
That's correct. Here is the [sample ](https://github.com/dell/csi-powerscale/blob/main/samples/secret/secret.yaml)secret file for reference.

**Comment by shanmydell** [comment]
Closing as the question is answered
