### ISSUE TITLE
[QUESTION]: Unable to connect to Backend PowerMax storage 

### ISSUE THREAD

**Issue by sagaya1982** [dell/csm#1041]
### How can the Team help you today? - I am a new User towards implementing CSI on PowerMax . When we try to configure storage for CSI getting the below error 

**Details: ?**
Driver logs
 
I1115 07:29:55.275068 1 leaderelection.go:243] attempting to acquire leader lease dell-storage-csi-csm/driver-csi-powermax-dellemc-com...
2I1115 07:30:11.235525 1 leaderelection.go:253] successfully acquired lease dell-storage-csi-csm/driver-csi-powermax-dellemc-com
3time="2023-11-15T07:30:11Z" level=info msg="Read CSI_LOG_FORMAT: text from configuration file"
4time="2023-11-15T07:30:11Z" level=info msg="Read CSI_LOG_LEVEL: debug from config file"
5time="2023-11-15T07:30:11Z" level=info msg="Setting log level to debug"
6time="2023-11-15T07:30:11Z" level=debug msg="setting GrpcMaxThreads to 50"
7time="2023-11-15T07:30:11Z" level=debug msg="Entering controllerProbe"
8time="2023-11-15T07:30:11Z" level=debug msg="Portgroups length is: 0"
9time="2023-11-15T07:30:11Z" level=info msg="Successfully started the lock request handler"
10time="2023-11-15T07:30:11Z" level=info msg="CleanupMapEntries: Successfully started the cleanup worker. This will wake up every 240.00 minutes to clean up stale entries"
11time="2023-11-15T07:30:15Z" level=error msg="Failed to fetch details for array: 000297900573. [Unauthorized]"
12time="2023-11-15T07:30:15Z" level=error msg="None of the managed arrays specified are locally connected"

**Comment by boyamurthy** [comment]
hi @sagaya1982  , may i know which method of installation you are using (helm.operator) . please share your values.yaml /other config files .
Meanwhile you can check, 
1.  are you using the Unisphere version > 10.0.0
2.  whether encrypted secrets are created correctly for Unisphere login credentials.
3. the array is local to the Unisphere 


Thanks,
Murthy

**Comment by shanmydell** [comment]
@sagaya1982 : Please feel free to reopen the issue with requested details
