### ISSUE TITLE
[QUESTION]:Minimal access to Dell EMC without loosing functionality

### ISSUE THREAD

**Issue by grvn** [dell/csm#1047]
# Background
---
I've got multiple different clusters who need access to the same Dell EMC instances ( PowerScale, PowerFlex, Unity, PowerMax, PowerStore ) for self-provisioning.

The functionality each cluster need is:
- automatic provisioning of storage ( basic functionality )
- ability to limit usage by applying quotas to provisioned storage ( SmartQuota I believe it's called in PowerScale, I do not remember what it is called in the others )

Last time ( 1+ years ago ) I tried using the Dell CSI Operator and/or Dell CSM Operator they needed accounts with so much elevated privileges that they could do almost whatever they wanted to all the resources in each Dell EMC instance.
I'm revisiting this now because a Dell solutions architect told me that it would be different this time ( ha talked something about using "access zones"!? ).

# Question
---
How can I limit the access each cluster has so they are not able to modify each others resources but still able to do everything they need to do?

### For example:
If cluster1 is compromised I do not want its credentials to the Dell EMC <productname> to enable an attacker to access the resources from cluster2 or cluster3 or.... clusterN in the same Dell EMC instance.

**Comment by coulof** [comment]
Hi @grvn,
What you are pointing at is precisely the goal of CSM Authorization (see [here ](https://dell.github.io/csm-docs/docs/authorization/) and [there](https://infohub.delltechnologies.com/l/persistent-storage-for-containerized-applications-on-kubernetes-with-powermax-san-storage-2/csm-for-authorization/).

It will remove the storage credentials from the local kubernetes cluster, implement RBAC for the objects managed by each cluster and add quota management per cluster.

If you use PowerScale, most customers set a base quota on the directory you give to your Kubernetes Cluster. If you have multiple clusters, you can provide different base paths upon driver installation or within the `StorageClass` parameters.

Also, we are working on a 2.0 version of that module and will be more than happy to continue that conversation directly on [Slack](https://dell.enterprise.slack.com/archives/C025E763URH). In case you need an invite to join you can request it [here](http://del.ly/Slack_request).

**Comment by shanmydell** [comment]
@grvn : Hope the above answer helps, Please join in slack to continue the conversation

**Comment by grvn** [comment]
@coulof: CSM Authorization does, almost, what I want.
If I understand the docs. correctly, there is still one Kubernetes/OpenShift cluster with StorageAdmin privilegies ( the one running the `proxy-server` pod )?
So if the cluster running `proxy-server` is compromised, it's game over for all clusters.

> Ability to shield storage credentials from Kubernetes administrators ensuring credentials are only handled by storage admins

That sound exacly like what I want. But I'm falling a bit short on how to make it work for me.

---
I can see how this can be used if you run something like a hub cluster, completely air-gapped, with only "centralized" components like RHACM, RHACS etc. but in our use case we run "decentralized"... so no hub cluster or any other shared containerized component between the clusters. So then all the clusters would have to run their own instance of `proxy-server` pod which kind of defeats the purpose.

The only shared component in our environment are the Dell EMC storage solutions like PowerScale.

I can move this over to the Slack channel linked by @coulof if that is what you prefer?

**Comment by shanmydell** [comment]
@grvn : Please continue the conversation in the slack channel, please let us know if you find any difficulties in onboarding
