### ISSUE TITLE
[BUG]: NFS Export gets deleted when one pod is deleted from the multiple pods consuming the same PowerFlex RWX NFS volume

### ISSUE THREAD

**Issue by suryagupta4** [dell/csm#1050]
### Bug Description

As per the implementation of PowerFlex 2.8.0 NFS feature, whenever a pod is deleted, the NFS export is also getting deleted. Considering a scenario where there are multiple pods consuming the same PowerFlex NFS volume running on different hosts, when one pod is deleted, its access should be removed from the NFS export but the other pod consuming that volume should still has access to it and the NFS export should be retained for this host.

### Logs

PVC, PV created:

```
[root@master-1-XLAciAjAjp1SS templates]# k get pvc,pv
NAME                         STATUS   VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/pvc0   Bound    k8s-4438caf3ab   8Gi        RWX            vxflexos-nfs   6m12s

NAME                              CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM          STORAGECLASS   REASON   AGE
persistentvolume/k8s-4438caf3ab   8Gi        RWX            Delete           Bound    default/pvc0   vxflexos-nfs            4m22s
```
Pods created consuming the same volume but present on different hosts
```
[root@master-1-XLAciAjAjp1SS templates]# k get po -owide
NAME        READY   STATUS    RESTARTS   AGE     NODE                            NOMINATED NODE   READINESS GATES
pod-nfs-0   1/1     Running   0          4m18s   worker-1-xlaciajajp1ss.domain   <none>           <none>
pod-nfs-1   1/1     Running   0          103s    worker-2-xlaciajajp1ss.domain   <none>           <none>

```

One pod deleted:
```
[root@master-1-XLAciAjAjp1SS templates]# k delete -f pod0.yaml
pod "pod-nfs-0" deleted
```

Not able to write any data on the second pod:
```
[root@master-1-XLAciAjAjp1SS templates]# k exec pod-nfs-1 -it /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
[root@pod-nfs-1 /]#
[root@pod-nfs-1 /]# ls
bin  data0  dev  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
[root@pod-nfs-1 /]# touch data0/test.txt
touch: setting times of 'data0/test.txt': Operation not permitted
```

### Steps to Reproduce

- Install PowerFlex 2.8.0 driver
- Create one RWX NFS volume
- Create two pods consuming the same volume
- Delete one pod
- Try to write data to another pod

### Expected Behavior

Should be able to write data to another pod since its access to the export should retain.

### CSM Driver(s)

CSI Driver PowerFlex 2.8

### Installation Type

Helm

### Container Orchestrator

Kubernetes 1.26

### Operating System

RHEL 8.6

**Comment by wrender** [comment]
Since the RECLAIM POLICY  on your PV is set to "Delete" isn't this expected?  You would need to set that to "Retain" if you don't want it to be deleted.

**Comment by suryagupta4** [comment]
> Since the RECLAIM POLICY on your PV is set to "Delete" isn't this expected? You would need to set that to "Retain" if you don't want it to be deleted.

When there are two pods consuming the same RWX volume and both are on different hosts, both the hosts are given access to the NFS export, if one pod is deleted then the other pod's host should still have access to the NFS export.

**Comment by wrender** [comment]
I didn’t read it properly the first time. I agree, the pod deletion shouldn’t remove the nfs export from the first pod. Sounds like a design flaw or bug.

**Comment by gallacher** [comment]
link: 18467
