### ISSUE TITLE
[QUESTION]:  The PowerFlex Dockerfile is incorrectly labeling the version as 2.7.0 for the 2.8.0 version.

### ISSUE THREAD

**Issue by adarsh-dell** [dell/csm#1054]
### How can the Team help you today?

 The PowerFlex Dockerfile is incorrectly labeling the version as 2.7.0 for the 2.8.0 version.
 
 docker inspect 9fc3532ae77a
[
    {
        "Id": "sha256:9fc3532ae77a410e7427e8ec601e430b2999016f8693809a3eda5af878023f7f",
        "RepoTags": [
            "dellemc/csi-vxflexos:v2.8.0"
        ],
        "RepoDigests": [
            "dellemc/csi-vxflexos@sha256:be75b4de126607dcc7ec691ed459f447d4d0e43f91fc937123f361fda4efc80b"
        ],
        "Parent": "",
        "Comment": "FROM 9668ddf91d0c",
        "Created": "2023-09-20T12:38:48.363671526Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/csi-vxflexos.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "architecture": "x86_64",
                "build-date": "2023-07-27T14:20:38",
                "com.redhat.component": "ubi9-micro-container",
                "com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
                "description": "CSI Driver for provisioning persistent storage from Dell EMC PowerFlex",
                "distribution-scope": "public",
                "io.buildah.version": "1.29.0",
                "io.k8s.description": "Very small image which doesn't install the package manager.",
                "io.k8s.display-name": "Ubi9-micro",
                "io.openshift.expose-services": "",
                "license": "Apache-2.0",
                "maintainer": "Red Hat, Inc.",
                "name": "csi-powerflex",
                "release": "13",
                "summary": "CSI Driver for Dell EMC PowerFlex",
                "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/ubi9/ubi-micro/images/9.2-13",
                "vcs-ref": "1fe65958f0b903c34b9f4e297121f45d958e4ae8",
                "vcs-type": "git",
                "vendor": "Dell Inc.",
                **"version": "2.7.0"**
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 232115678,
        "VirtualSize": 232115678,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/e0ce8dfe7c9793a97b4aede524e9b69f637db0664e225c7c76f42a266b31fa40/diff:/var/lib/docker/overlay2/db62e7ef7c7b1e2b354cdb76c2cac1d3591262b00336adb0286635cd2aae6197/diff:/var/lib/docker/overlay2/f1ededb0cb3fe224ba3ebfe8d7b013eeb0898d03bf3b162ff5a7933592a2e114/diff:/var/lib/docker/overlay2/78891f94cbde7c58999ea645daa43085e76039a017e033bc0fcc97ec836024eb/diff:/var/lib/docker/overlay2/c5b3405d1130b3a99447bce72faa18ad42fb05fe790da29e3f6933e7bc1b098d/diff",
                "MergedDir": "/var/lib/docker/overlay2/eac0bf175685e1af558c7dfc6cee6a17f770f53001e5da2e1ec92b7b270d27fe/merged",
                "UpperDir": "/var/lib/docker/overlay2/eac0bf175685e1af558c7dfc6cee6a17f770f53001e5da2e1ec92b7b270d27fe/diff",
                "WorkDir": "/var/lib/docker/overlay2/eac0bf175685e1af558c7dfc6cee6a17f770f53001e5da2e1ec92b7b270d27fe/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:80a3f0b229f61dfcdaee710c74201f383ef99e1dde651fc5c2a53b3aefc9b095",
                "sha256:6e73ddf97b8c728dc02827e1b9a9bbbfe922599013c72459c61c04f3d011c2dd",
                "sha256:f5a8ffd5bef4ca13abe8f4e0092d53a5ae1279ddc9f9ff5d28d362f130bff79c",
                "sha256:dea2a1c5de0336027bc68671104a87157304599327ce34f365d5b600d9913152",
                "sha256:a2c5b8714a4b2af6247e89102da1862cc83bcc48dc4d214b7fe0db0c238e64a4",
                "sha256:17ea200871eb0ea7ff0faf077fc1937a051693467322a69015ed42e5c92c0f4b"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
[root@dm-st--xxxxxxxxxxxxxx ~]# **docker inspect 9fc3532ae77a | grep "2.7.0"
                "version": "2.7.0"**

**Comment by adarsh-dell** [comment]
Added this issue as a known issue in the release notes of CSI-PowerFlex driver.

**Comment by suryagupta4** [comment]
This issue is with v2.8.0 and hence added in the known issue of 2.8.0
The same has been fixed and have added in the fixed issues of v1.9.0
