### ISSUE TITLE
[BUG]: Github actions has to be updated for PowerMax 

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#1064]
### Bug Description

in git hub action file , we are excluding the reverse proxy directory as part of gosec . We should include this . 

### Logs
.

### Steps to Reproduce

check github actions

### Expected Behavior

gosec has be to executed against all files/directories .

### CSM Driver(s)

CSI driver for PowerMax

### Container Orchestrator

all

### Operating System

all

**Comment by gallacher** [comment]
link: 19291
