### ISSUE TITLE
[QUESTION]: COSI driver licensing issue

### ISSUE THREAD

**Issue by shanduur** [dell/csm#1083]
### How can the Team help you today?

**Details:**

I noticed that there is no License file available in the repository for the COSI driver. Understanding the licensing of the software is crucial for users and contributors to comply with the terms and conditions set by the project.

Could the maintainers provide information regarding the licensing of the COSI driver? Having a clear and accessible license file in the repository would greatly assist users and potential contributors in understanding the legal and usage terms associated with the software.

Thank you for your attention to this matter.

**Comment by gallacher** [comment]
Hi @shanduur.  Thank you for bringing this to the attention of the CSM maintainers.  There is a PR up to address this: https://github.com/dell/cosi/pull/189
