### ISSUE TITLE
[QUESTION]: Can't create PVs with CSI driver version 2.8 and Powerstore ver 3.6

### ISSUE THREAD

**Issue by dlavi** [dell/csm#1093]
### How can the Team help you today?

**Details: ?**

**Comment by shanmydell** [comment]
@dlavi : Please provide more details and logs for further investigation

**Comment by dlavi** [comment]
After connecting successfully to the hosts ( recognized with the powerstore with iSCSI) I am trying to create PVs ( all done through our automated tools), we are getting error message like the following : 
"msg":"could
n't get the software version installed on the powerstore array"

**Comment by vbkvi** [comment]
I tired connecting to powerstore https://[10.169.39.101](https://10.169.39.101/)/, but observing can't reach the page. Pease confirm the installation of powerstore is successful on thi IP.

**Comment by dlavi** [comment]
Logs with the exact error was attached in the prev message , please advise which specific log do you need ?

**Comment by dlavi** [comment]
Lavi, Doron ***@***.***) has sent you a protected message.
                                          Read the message            Learn about messages protected by Microsoft Purview Message Encryption.        
    
    
    
        
           Privacy Statement        
    
    
        
              Learn More on email encryption.             Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

**Comment by vbkvi** [comment]
Please provide me the configuration date used.
if possible, provide Powerstore logs when this error happened.

**Comment by shanmydell** [comment]
@dlavi : Thanks for the response
