### ISSUE TITLE
[BUG]: Volumes failing to mount when customer using NVMeTCP on Powerstore.

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#1108]
### Bug Description

There are currently 2 networks configured - 1 iSCSI with NVMeTCP enabled  and the new NVMeTCP network with iSCSI enabled:

They hit an issue when attempting to mount the volume :

 

{"level":"info","msg":"/csi.v1.Node/NodeStageVolume: REQ 10755: VolumeId=fe8d5b5c-810e-4dcf-8e50-3e796cb9b3d7/PS4959cf04ec32/scsi, PublishContext=map[DEVICE_WWN:68ccf09800174a7470388bd33ed4962b LUN_ADDRESS:6 PORTAL0:X.X.X.X:X PORTAL1:X.X.X.X:X PORTAL2<IP>:<port> PORTAL3:X.X.X.X:X TARGET0:iqn.X.X.X:dellemc-powerstore-crk00214204286-a-0a04a548 TARGET1:iqn.X.X.Xdellemc-powerstore-crk00214204286-b-7f4d3183 TARGET2:iqn.X.X.X:dellemc-powerstore-crk00214204286-b-7f4d3183 TARGET3:iqn.X.X.X:dellemc-powerstore-crk00214204286-a-0a04a548], StagingTargetPath=/var/lib/kubelet/plugins/kubernetes.io/csi/csi-powerstore.dellemc.com/b161fedae439149deb024ed9db6fe6acdc064a3dc95ef6a3a862b764bff9dda0/globalmount, VolumeCapability=mount:\u003cfs_type:\"ext4\" \u003e access_mode:\u003cmode:SINGLE_NODE_MULTI_WRITER \u003e , VolumeContext=map[Name:csivol-5dae47f2a7 Protocol:scsi arrayID:PS4959cf04ec32 csi.storage.k8s.io/pv/name:csivol-5dae47f2a7 csi.storage.k8s.io/pvc/name:alpine-pvc csi.storage.k8s.io/pvc/namespace:dev-infrastructure description:alpine-pvc-dev-infrastructure serviceTag:23NW983 storage.kubernetes.io/csiProvisionerIdentity:1702561598490-5138-csi-powerstore.dellemc.com], XXX_NoUnkeyedLiteral={}, XXX_sizecache=0","time":"2023-12-18T15:12:05.745758592Z"}

Unknown macro: {"level"}
Unknown macro: {"level"}
Unknown macro: {"level"}
Unknown macro: {"level"}
Unknown macro: {"level"}

### Logs

They hit an issue when attempting to mount the volume :

 

{"level":"info","msg":"/csi.v1.Node/NodeStageVolume: REQ 10755: VolumeId=fe8d5b5c-810e-4dcf-8e50-3e796cb9b3d7/PS4959cf04ec32/scsi, PublishContext=map[DEVICE_WWN:68ccf09800174a7470388bd33ed4962b LUN_ADDRESS:6 PORTAL0:<IP>:<port>PORTAL1:<IP:<port>PORTAL2:<IP>:<port>PORTAL3:X.X.X.X:X TARGET0:iqn.X.X.X:dellemc-powerstore-crk00214204286-a-0a04a548 TARGET1:iqn.X.X.X:dellemc-powerstore-crk00214204286-b-7f4d3183 TARGET2:iqn.X.X.X:dellemc-powerstore-crk00214204286-b-7f4d3183 TARGET3:iqn.X.X.X:dellemc-powerstore-crk00214204286-a-0a04a548], StagingTargetPath=/var/lib/kubelet/plugins/kubernetes.io/csi/csi-powerstore.dellemc.com/b161fedae439149deb024ed9db6fe6acdc064a3dc95ef6a3a862b764bff9dda0/globalmount, VolumeCapability=mount:\u003cfs_type:\"ext4\" \u003e access_mode:\u003cmode:SINGLE_NODE_MULTI_WRITER \u003e , VolumeContext=map[Name:csivol-5dae47f2a7 Protocol:scsi arrayID:PS4959cf04ec32 csi.storage.k8s.io/pv/name:csivol-5dae47f2a7 csi.storage.k8s.io/pvc/name:alpine-pvc csi.storage.k8s.io/pvc/namespace:dev-infrastructure description:alpine-pvc-dev-infrastructure serviceTag:23NW983 storage.kubernetes.io/csiProvisionerIdentity:1702561598490-5138-csi-powerstore.dellemc.com], XXX_NoUnkeyedLiteral={}, XXX_sizecache=0","time":"2023-12-18T15:12:05.745758592Z"}

Unknown macro: {"level"}
Unknown macro: {"level"}
Unknown macro: {"level"}
Unknown macro: {"level"}
Unknown macro: {"level"}

### Steps to Reproduce

Mount volumes with nvme

### Expected Behavior

mounting should work fine. 

### CSM Driver(s)

csi driver for PowerStore 

### Container Orchestrator

all

### Operating System

all

**Comment by gallacher** [comment]
link: 20502
