### ISSUE TITLE
[BUG]: Multi Controller defect - sidecars timeout

### ISSUE THREAD

**Issue by adamginna-dell** [dell/csm#1110]
### Bug Description

The first controller pods start without any problems. Second and next controller pods are failing.
Link to [Change in a csi-lib-utils library](https://github.com/kubernetes-csi/csi-lib-utils/commit/bbcd13252ca60814a2e5c31255db660de4bed957) that add timeout for connection with socket. New versions of sidecars use new version of csi-lib-utils and timeout cause controller pods fail. 

### Logs

level=info msg="Attempting driver connection at: unix:/var/run/csi/csi.sock"
level=debug msg="grpc.Dial returned context deadline exceeded"
level=error msg="Waiting on connection to driver csi.sock: context deadline exceeded"
level=debug msg="grpc.Dial returned context deadline exceeded"
level=error msg="Waiting on connection to driver csi.sock: context deadline exceeded"

### Steps to Reproduce

Setup controller replicas in to number more then 1.

### Expected Behavior

All controller pods are in Running state.

### CSM Driver(s)

CSI Driver - Unity 2.9.0, Powerscale 2.9.0, Powerflex 2.9.0, Powermax 2.9.0  

### Container Orchestrator

All

### Operating System

All

**Comment by adamginna-dell** [comment]
Standby controller pod is in crashloopbackoff state. As a workaround scale down the replica count of the controller pod’s deployment to 1 using
`kubectl scale deployment <deployment_name> --replicas=1 -n <driver_namespace>`

**Comment by gallacher** [comment]
link: 20348
