### ISSUE TITLE
[FEATURE]: Support PowerStore v3.6

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#1129]
Qualify CSM PowerStore driver and associated modules with the latest version of the PowerStore v3.6 storage platform

**Comment by cindyhodell** [comment]
Team - can we get the documentation updated with PowerStore 3.6 support? It is not listed in the matrix.

**Comment by boyamurthy** [comment]
> Team - can we get the documentation updated with PowerStore 3.6 support? It is not listed in the matrix.

hi @cindyhodell, thank you for letting us know this and updated the support matrix for PowerStore 3.6.
