### ISSUE TITLE
[BUG]: CSM Operator resource state remains "Failed" even after driver is successfully installed

### ISSUE THREAD

**Issue by KerryKovacevic** [dell/csm#1130]
### Bug Description

Triggered install of Powerflex driver via CSM Operator; no modules selected.
The controller and node pods came up , but the CSM resource remained in failed state even 15 minutes later.

### Logs

Based on logs, the operator controller is expecting modules pods also to come up even though no modules were selected for install.

### Steps to Reproduce

Install driver via operator with no modules, check CSM state after controller and node pods come up

### Expected Behavior

CSM state after driver install via operator should be successful if controller and nodes are healthy, even with no modules installed.

### CSM Driver(s)

PowerFlex

### Installation Type

CSM Operator version : 1.4.1

### Container Orchestrator

N/A

### Operating System

N/A

**Comment by gallacher** [comment]
link: 20776

**Comment by jooseppi-luna** [comment]
Fixed in CSM v1.9.2
