### ISSUE TITLE
[QUESTION]: `nasName` setting is said optional but is mandatory from the driver

### ISSUE THREAD

**Issue by coulof** [dell/csm#1138]
### Bug Description

Per the sample : https://github.com/dell/csi-powerflex/blob/main/samples/secret.yaml#L31 I configured a secret with `nasName` but the driver crashes with : 

```
powerflex-node-787b4 registrar I0211 17:20:01.139332       1 main.go:101] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: rpc error: code = Unknown desc = nasName value not found in secret, it is mandatory parameter for NFS volume operations, if not specified, provide the default value as 'none',}
powerflex-node-787b4 registrar E0211 17:20:01.139353       1 main.go:103] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: rpc error: code = Unknown desc = nasName value not found in secret, it is mandatory parameter for NFS volume operations, if not specified, provide the default value as 'none', restarting registration container.
```

### Logs

powerflex-node-787b4 registrar I0211 17:20:01.139332       1 main.go:101] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- plugin registration failed with err: rpc error: code = Unknown desc = nasName value not found in secret, it is mandatory parameter for NFS volume operations, if not specified, provide the default value as 'none',}
powerflex-node-787b4 registrar E0211 17:20:01.139353       1 main.go:103] Registration process failed with error: RegisterPlugin error -- plugin registration failed with err: rpc error: code = Unknown desc = nasName value not found in secret, it is mandatory parameter for NFS volume operations, if not specified, provide the default value as 'none', restarting registration container.

### Steps to Reproduce

install and don't configure `nasServer`

### Expected Behavior

Fix the doc or the driver

### CSM Driver(s)

CSI for PowerFlex 2.9.0

### Container Orchestrator

OCP 4.14

### Operating System

CoreOS

**Comment by adarsh-dell** [comment]
Hi @coulof , We are making this field completely optional from v2.10 onwards as per the request by https://github.com/dell/csm/issues/1101 and fix went as a part of this PR https://github.com/dell/csi-powerflex/pull/283.

But I am curious to understand that if nasName was provided by you in secret.yaml then why we are hitting this issue because this was expected to work so can you please decode your secret and see if the nasName value is present there or not?
In case if nasName is present I may need complete log of node and controller pod to debug it further.

Thanks for reporting this issue.

Regards,
Adarsh

**Comment by adarsh-dell** [comment]
@coulof I've observed your mention of installing the nasServer without configuring it. Until v2.9.1, we should ensure that the nasName remains as Null instead of leaving the field empty. JFYI, We will hit this issue if and only array version >=4.x.

- Adarsh

**Comment by shanmydell** [comment]
@adarsh-dell @coulof : Tagging milestone will add the issue twice in release notes, hence removing it, changed the title to Question, if it is an issue, reopen the other issue tagged with milestone

**Comment by adarsh-dell** [comment]
Closing this issue since we are taking care of this one as part of https://github.com/dell/csm/issues/1101.
