### ISSUE TITLE
[QUESTION]: Update documenation PowerFlex CSI driver support support for EKS Anywhere to YES

### ISSUE THREAD

**Issue by hoppea2** [dell/csm#1141]
### How can the Team help you today?

Dell APJ Presales team has installed and successfully tested PowerFlex 2.6 with EKS Anywhere with multiple variations and configurations. and will validate that it can be deployed with the latest version of CSM as well. 

Details here: 
https://ambar-thecloudgarage.medium.com/eks-anywhere-on-bare-metal-with-dell-technologies-and-metalsoft-c91f78020dbc

Can the documentation then be updated in the Community Qualified Platform section? 
https://dell.github.io/csm-docs/docs/csidriver/#community-qualified-platforms

**Comment by shanmydell** [comment]
Updated via https://github.com/dell/csm-docs/pull/1025
