### ISSUE TITLE
[QUESTION]: How to back the pvc on openshift powerflex storage

### ISSUE THREAD

**Issue by yamham** [dell/csm#1145]
### How can the Team help you today?

**Details: ?**
We would like to back up pvc on openshift4.12 version how ever the openshift dose not support kubernetes-native snapshot support is there any alternative way to back these pvc which are using by openshift vertual machine as disk

**Comment by AkshaySainiDell** [comment]
Hi @yamham, 
Have you had an opportunity to look through below pages in CSM documentation for the snapshot feature ? 
[Volume Snapshot Feature](https://dell.github.io/csm-docs/docs/snapshots/)
[Volume Snapshot Feature - PowerFlex](https://dell.github.io/csm-docs/docs/csidriver/features/powerflex/#volume-snapshot-feature)

Please go through above links and let us know if these do not help is resolving your query.

**Comment by AkshaySainiDell** [comment]
Closing the issue based on above comment. Please feel free to reopen or start a new issue if you require any additional help.
