### ISSUE TITLE
[QUESTION]:PowerScale - Install CSM on Windows nodes

### ISSUE THREAD

**Issue by Yonghyun4195** [dell/csm#1170]
I would like to install CSM operator for CSM integration of K8s on Windows node based on Powerscale.

Can't I install Windows node?
Or is there any additional work to do to install on a windows node?

Controller error log

Events:

  Type    Reason   Age                   From     Message

  ----    ------   ----                  ----     -------

  Normal  BackOff  11s (x3903 over 15h)  kubelet  Back-off pulling image "registry.k8s.io/sig-storage/csi-resizer:v1.8.0"

 

Node error log

Events:

  Type     Reason   Age                     From     Message

  ----     ------   ----                    ----     -------

  Normal   BackOff  4m57s (x4026 over 15h)  kubelet  Back-off pulling image "dellemc/csi-isilon:v2.8.0"

**Comment by Leonard-Dell** [comment]
Unfortunately, we don't support Windows.

**Comment by coulof** [comment]
Hi @Yonghyun4195,
We don't build images other than x86_64, nonetheless, everything is open source and you can compile a Windows image.
There is an example [here](https://infohub.delltechnologies.com/en-US/p/kubernetes-on-z-with-powermax-modern-software-running-on-mainframe/) to compile the driver for mainframe architecture.

You can give it a try for Windows.

Let us know how this works.
