### ISSUE TITLE
[QUESTION]: NFS based mountpoint inside PODs always defaults to root:root

### ISSUE THREAD

**Issue by anandhg02** [dell/csm#1204]
NFS based mountpoint inside PODs always defaults to _root:root_, as _fsGroup securityContext_ does not apply to NFS mounts. But POD needs non-root access. This looks to be a known issue for NFS and the workaround is to use _initCointainer_ to use _chown_ command to set the required owner:group . It would be helpful if a reference be added in the CSM documentation about this. 

**Reference:** 
[Why does my app fail when a non-root user owns the NFS file storage mount path? | IBM Cloud Docs](https://cloud.ibm.com/docs/openshift?topic=openshift-nonroot)

**Comment by adarsh-dell** [comment]
Hi @anandhg02 ,

**Comment by anandhg02** [comment]
Hello Adarsh, Yes I found this later from the Release Notes section. What I intend to says was, can this be documented in a proper location may be under **_CSI Driver > Features_** and also explain the workaround as well,  just my suggestion.

**Comment by gallacher** [comment]
@anandhg02, this aligns with troubleshooting.  Would it be helpful if this was added to the Troubleshooting section? https://dell.github.io/csm-docs/docs/csidriver/troubleshooting/powerscale/.

**Comment by anandhg02** [comment]
Agree, yes it can be part of Troubleshooting. But as this issue (fsGroup not working as expected) is common for any NFS based provisioning the Resolution or Workaround can be added under other storage arrays as well like PowerStore, Unity XT.

**Comment by gallacher** [comment]
@anandhg02 I've created a pull request (https://github.com/dell/csm-docs/pull/1063).  Please have a look when you have a moment to see if this addresses things.  Thank you.

**Comment by anandhg02** [comment]
Thanks a lot @gallacher

**Comment by gallacher** [comment]
You're very welcome @anandhg02
