### ISSUE TITLE
[QUESTION]: csm-authorization module for powerstore

### ISSUE THREAD

**Issue by john-crane** [dell/csm#1219]
Hello, 

will be the powerstore supported in future versions of csm-authorization module? I would like to split utilization of powerstore between vmware nad k8s cluster and better authorization and the ability to have some sort of RBAC would make it so much easier. 

Thank you.

**Comment by shanmydell** [comment]
Hi @john-crane , Thanks for expressing interest in support of authorization for PowerStore, we have added it to your future roadmap, once the timelines are confirmed, will update in the same thread, thanks

**Comment by cindyhodell** [comment]
Hi John, thank you again for raising this feature request. To add more context, we are making some updates to the backend of the Authorization module and once those are complete, we plan to extend support to PowerStore. We cannot share a specific ETA/target release at this time but it is on our roadmap.
