### ISSUE TITLE
[BUG]: Driver logs show dirty tag in version

### ISSUE THREAD

**Issue by francis-nijay** [dell/csm#126]
**Describe the bug**
Driver logs show dirty tag in version

**To Reproduce**
1. checkout csi-powerstore from github
2. build image and deploy
3. logs show dirty tag in version

Name=csi-powerstore.dellemc.com, VendorVersion=2.1.0+dirty,

**Expected behavior**
Driver logs of images build from unmodified repository should not have dirty tag

**Comment by shanmydell** [comment]
@francis-nijay : Can this issue be closed?
