### ISSUE TITLE
[BUG]:Documentation improvement recommendations for PowerScale

### ISSUE THREAD

**Issue by gashof** [dell/csm#127]
**Describe the bug**
Documentation improvement recommendations for PowerScale in this example. Similar should be looked at for all drivers.  See attached DocIssuesQuestions.

**To Reproduce**
N/A

**Expected behavior**
Documentation on upgrades to be improved so that novice through experts can follow the steps.

**Screenshots**
See attached doc

**Logs**
N/A

**System Information (please complete the following information):**
This example was for PowerScale

**Additional context**
N/A
[DocIssuesQuestions.docx](https://github.com/dell/csm/files/7663476/DocIssuesQuestions.docx)

**Comment by prablr79** [comment]
@gashof Thanks for recommendation, we will review and update the document portal.
