### ISSUE TITLE
[QUESTION]: New OpensShift Cluster 4.15.6 is not listing the DELL CSM Certified

### ISSUE THREAD

**Issue by edga-silva** [dell/csm#1274]
### How can the Team help you today?
Hi all,

I am new with OpenShift and I am recently installed OpenShip Cluster v.4.15.6. 

**Details: ?**

My aim is to connected to DELL PowerFlex for external Storage but it seems the only Operator available in OperatorHub is the DELL Community and no the Certified.  I would appreciate if you can give me an idea how to fix/add the DELL provider to OperatorHub. 

Everything seems to work fine. 
[root@localhost OpenShift]# oc get catsrc -n openshift-marketplace
NAME                  DISPLAY               TYPE   PUBLISHER   AGE
certified-operators   Certified Operators   grpc   Red Hat     15d
community-operators   Community Operators   grpc   Red Hat     15d
redhat-marketplace    Red Hat Marketplace   grpc   Red Hat     15d
redhat-operators      Red Hat Operators     grpc   Red Hat     15d

[root@localhost OpenShift]# oc get pods -n openshift-marketplace
NAME                                                              READY   STATUS      RESTARTS      AGE
38a1acd49436958c530d97ec29f955c4870b78342cba38bc16d84f5229mhl5c   0/1     Completed   0             15d
ae79136c969668d1bde0aa55ffc0e6bdcd432703aee4e1d14c818fddbf8l262   0/1     Completed   0             3d1h
certified-operators-cxwpz                                         1/1     Running     0             15d
community-operators-nwgxk                                         1/1     Running     0             15d
f193956087e6b79fadfb66d675c3abc94196dc6343bfd147ce002a52f6plp9f   0/1     Completed   0             15d
marketplace-operator-6bcd474fbf-bss64                             1/1     Running     3 (15d ago)   15d
redhat-marketplace-g5cc7                                          1/1     Running     0             15d
redhat-operators-kf8tq                                            1/1     Running     0             15d

[root@localhost OpenShift]# oc describe  catalogsources certified-operators -n openshift-marketplace
Name:         certified-operators
Namespace:    openshift-marketplace
Labels:       <none>
Annotations:  operatorframework.io/managed-by: marketplace-operator
              target.workload.openshift.io/management: {"effect": "PreferredDuringScheduling"}
API Version:  operators.coreos.com/v1alpha1
Kind:         CatalogSource
Metadata:
  Creation Timestamp:  2024-04-11T13:05:57Z
  Generation:          1
  Resource Version:    13592221
  UID:                 2e25fc68-c17f-4ffd-82de-d1c22a570278
Spec:
  Display Name:  Certified Operators
  Grpc Pod Config:
    Extract Content:
      Cache Dir:    /tmp/cache
      Catalog Dir:  /configs
    Memory Target:  40Mi
    Node Selector:
      kubernetes.io/os:                linux
      node-role.kubernetes.io/master:
    Priority Class Name:               system-cluster-critical
    Security Context Config:           restricted
    Tolerations:
      Effect:              NoSchedule
      Key:                 node-role.kubernetes.io/master
      Operator:            Exists
      Effect:              NoExecute
      Key:                 node.kubernetes.io/unreachable
      Operator:            Exists
      Toleration Seconds:  120
      Effect:              NoExecute
      Key:                 node.kubernetes.io/not-ready
      Operator:            Exists
      Toleration Seconds:  120
  Icon:
    base64data:
    Mediatype:
  Image:         registry.redhat.io/redhat/certified-operator-index:v4.15
  Priority:      -200
  Publisher:     Red Hat
  Source Type:   grpc
  Update Strategy:
    Registry Poll:
      Interval:  10m
Status:
  Connection State:
    Address:                   certified-operators.openshift-marketplace.svc:50051
    Last Connect:              2024-04-11T13:20:04Z
    Last Observed State:       READY
  Latest Image Registry Poll:  2024-04-26T13:33:23Z
  Registry Service:
    Created At:         2024-04-11T13:15:51Z
    Port:               50051
    Protocol:           grpc
    Service Name:       certified-operators
    Service Namespace:  openshift-marketplace
Events:                 <none>

The operators are no disabled as you can see:

[root@localhost OpenShift]# oc get operatorhubs/cluster -o yaml
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  annotations:
    capability.openshift.io/name: marketplace
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-04-11T12:49:32Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 11258930-830c-42d2-9830-489c22719200
  resourceVersion: "13294554"
  uid: 3406e75b-ed55-4e71-9c0a-d2c98a25537a
spec: {}
status:
  sources:
  - disabled: false
    name: certified-operators
    status: Success
  - disabled: false
    name: community-operators
    status: Success
  - disabled: false
    name: redhat-marketplace
    status: Success
  - disabled: false
    name: redhat-operators
    status: Success

I am new and I would appreciate if you can point me to the right track.

Thank in advance,
Ed

**Comment by rajendraindukuri** [comment]
Hi @edga-silva Our latest version of CSM Opeator v1.5.0 is certified on Openshift 4.13 and 4.14. So you will not see any certified operators listed in 4.15.x

Thanks
Rajendra

**Comment by edga-silva** [comment]
Thank Rajendra for your reply. 

In this situation, do you recommend to install the community edition? what will be the pros and cons? 

Or do you recommend to re-install the OpenShift versions 4.13 or 4.14?  

I would appreciate your thought here. 

Kind Regards,
Ed

**Comment by shanmydell** [comment]
@edga-silva : CSM v1.5.0 will not work with 4.14, this limitation will be lifted in upcoming releases, for now would suggest re-installing to 4.14.

**Comment by edga-silva** [comment]
Thank Shanmy. I will reinstall OpenShift 4.14 and connect DELL PowerFlex version R3_6.2000.117 following the below document:
https://infohub.delltechnologies.com/en-us/l/red-hat-openshift-4-11-deployment-and-data-protection-using-ppdm-on-dell-powerflex-4-0-1/powerflex-csi-instance/

The document is for OpenShift 4.11 with PowerFlex, hopefully I will not be any issues and it is valid.
