### ISSUE TITLE
[QUESTION]: PVC Usage not showing in Openshift

### ISSUE THREAD

**Issue by stephen50191** [dell/csm#1288]
I'm using RedHat OpenShift 4.12 with Dell CSM 1.3 with the Unity CSI driver.  Typically when we use a PVC from other storage appliances we get back the usage but for some reason the Unity created volumes are not.

Is there a way to enable this?

Thanks,

**Comment by coulof** [comment]
@stephen50191, have you enabled the "health monitoring" upon installation ? https://github.com/dell/helm-charts/blob/main/charts/csi-unity/values.yaml#L139

**Comment by shanmydell** [comment]
@stephen50191 : Please feel free to re-open the ticket with questions answered
