### ISSUE TITLE
[QUESTION]: What is the taint "offline.powerstore.storage.dell.com" for？Is it possible to remove it during installation?

### ISSUE THREAD

**Issue by RyanBao** [dell/csm#1296]
### How can the Team help you today?

Just a quick question: What is the taint "offline.powerstore.storage.dell.com" for？Is it possible to remove it during installation as features like CSM for Resiliency or CSI Driver pods monitor will not be used?

**Details: ?**
Powerstore CSI Driver 2.8.0 within K8S v1.24.7

Thanks.

**Comment by alikdell** [comment]
"offline.powerstore.storage.dell.com" That means driver node pods are down in that node or that node is down/not reachable.

We do not recommends user manually delete any taints adds by CSM for Resiliency. Use has option to enable/disable driver node pod monitoring by CSM for Resiliency.

**Comment by adarsh-dell** [comment]
Hi @RyanBao , I hope your query got resolved as I can see @alikdell has explained it very well.
Please feel free to close the issue.

Thanks

**Comment by RyanBao** [comment]
Thanks for the clarification. We'll try to disable driver node pod monitoring feature.

**Comment by RyanBao** [comment]
Thanks for the clarification. We'll try to disable driver node pod monitoring feature.
