### ISSUE TITLE
[QUESTION]: how to add init container to powermax deployment and change powermax sha

### ISSUE THREAD

**Issue by mrandhikpurwala** [dell/csm#1313]
### How can the Team help you today?

**Details: We are using Dell CSM deployment and we have a requirement to inject secrets using Vault injector. Since CSM creates the deployment we are unable to find a way to inject secrets to powermax container using Vault Injector.

Is there a way to make modifications to the deployment so that it uses the init container or adds annotations to the deployment so that vault injector can be triggered?**

**Comment by coulof** [comment]
Hi @mrandhikpurwala,
The CSM Operator does not allow the customization of `Deployment` and `DaemonSet`.

If you need to fine-tune them, it is better to patch the helm charts : https://github.com/dell/helm-charts/blob/main/charts/csi-powermax/templates/controller.yaml#L169

And if you have GitOps integration, you can [combine Kustomize with the helm chart](https://storage-chaos.io/kustomize-and-helm-better-together.html  ) to cleanly maintain your patch.


Let me know if that answers.
