### ISSUE TITLE
[FEATURE]:Implemented Unified log collection solution for CSM modules

### ISSUE THREAD

**Issue by prablr79** [dell/csm#132]
This PR includes functionalities w.r.t unified log collection solution under a Kubernetes cluster for a given namespace -

Driver details (namespace, driver name, driver version)
Details of the nodes, namespaces, pods, and sidecars
Detailed description of each pod
Lease details
Customised log collection for specific platforms

**Comment by prablr79** [comment]
@Prabhu-Dell  can you close this feature request, since work is now merged ?

**Comment by Prabhu-Dell** [comment]
Closing the feature as it's completed and merged.
