### ISSUE TITLE
[QUESTION]:Powerstore integration with OCP 4.14 on NVME-FC protocol

### ISSUE THREAD

**Issue by ajaysingh1985** [dell/csm#1329]
### How can the Team help you today?

**At one of our customer sites

-	We have integrated the Powerstore with Open shift 4.14 through FC protocol with the help of YAML file from the below link.
https://github.com/dell/csm-operator/blob/main/samples/storage_csm_powerstore_v2100.yaml

-	Can you please help if we can change the protocol from FC to NVME-FC, we have not been able to get any details for the same in any YAML.

The objective here is to integrate the PowerStore with Open shift 4.14 on NvME -FC protocol through CSI driver. We are looking for similar YAML for NvME-FC protocol for integration of Powerstore with Open shift 4.14. 
**

**Comment by adarsh-dell** [comment]
Hi @ajaysingh1985 ,

If FC zoning is done, then we have to provide the protocol in the secret. Please refer to this file and line number: [secret.yaml#L65](https://github.com/dell/csi-powerstore/blob/76e2cb671bd3cb28aa860e9057649d1d911e1deb/samples/secret/secret.yaml#L65).

If the blockProtocol is set to 'Auto', the driver will automatically choose the protocol based on the available initiators found on the worker node, based on priority.

As you mentioned, FC zoning is already done, but now the customer wants to use NVME-FC. They can update the secret's blockProtocol field with the NVMeFC value and either restart or reinstall the driver based on their feasibility.

Although the above is the process, I didn't understand what you specifically found in [storage_csm_powerstore_v2100.yaml](https://github.com/dell/csm-operator/blob/main/samples/storage_csm_powerstore_v2100.yaml) that you are referring to as the FC protocol? I think you may have FC zoned the cluster first and then installed the driver using this sample, right? And the secret's blockProtocol was set to "Auto".

Thanks,
Adarsh

**Comment by adarsh-dell** [comment]
@ajaysingh1985 ,

One more point to note here is that I hope you haven't created any volumes using the FC protocol? If you have, we may need to assess the impact on already created volumes using FC protocol as going forward you want to use nvmeFC,

Thanks,
Adarsh

**Comment by shanmydell** [comment]
@ajaysingh1985 : Please feel free to re-open the ticket with the details requested.
