### ISSUE TITLE
[BUG]: Data loss (DL) when deleting PVC but leaves unusable volumesnapshot and volumesnapshotcontent

### ISSUE THREAD

**Issue by delldubey** [dell/csm#1338]
### Bug Description

- Creation of clone from a snapshot fails after source PVC of the snapshot is deleted.

### Logs

NA

### Steps to Reproduce

Create a PVC - pvc1
Create a snap on pvc1 - snap1
Delete the pvc1
Create pvc2 using snap1 as source

### Expected Behavior

A PVC from snapshot having READY as TRUE must be created.  

### CSM Driver(s)

CSI Powerstore

### Container Orchestrator

OCP 4.14

### Operating System

RH

**Comment by boyamurthy** [comment]
link : 25443
