### ISSUE TITLE
[QUESTION] Unity 350F support for RH OCP 4.14.22

### ISSUE THREAD

**Issue by KevinFerchau** [dell/csm#1343]
When will Unity 350F be supported with RH OCP 4.14.22?

Also, for 4.14.22, what version of CSI driver should be used?

Thanks in advance,

Kevin

**Comment by gallacher** [comment]
Hi @KevinFerchau, thank you for reaching out.  CSM 1.9 introduced support for OCP 4.14 in December 2023.  CSM 1.9 aligns with v2.9.0 of the Unity CSI driver.   In this version, Unity XT 5.1.x, 5.2.x, and 5.3.0 are supported.  CSM 1.10, released in March (v2.10.1 of the Unity CSI driver) supports OCP 4.14 and 4.15 for Unity XT 5.1.x, 5.2.x, and 5.3.0.

**Comment by vyshakav-dell** [comment]
Hi @KevinFerchau, please refer to my below comments

1. Please refer to the appropriate [documentation](https://dell.github.io/csm-docs/v1/) by clicking on 'Releases' dropdown in the top right section of your screen. You will be able to see the 1.9.4 version of CSM. 

![image](https://github.com/dell/csm/assets/136616665/a5180b85-db04-4497-b8da-6126aef50bde)

If you are using Helm to deploy the Unity CSI driver, you could use the following link - https://dell.github.io/csm-docs/v1/csidriver/installation/helm/unity/

2. Yes, Unity software releases are compatible with all Unity storage array models. So, CSM supports any flavor of 5.3.x version in this particular case.

**Comment by KevinFerchau** [comment]
Hello,

Customer still has some concerns that AES256 is not supported with SNMP.

Your thoughts?
-----------------


Hello Kevin,

Thank you. From the below description it is clear AES256 is supported for SSH, but what about SNMP? The query is related to AES256 not being available for SNMP

Below is the screenshot from Dell server 650 iDRAC SNMP integration and it shows AES256, but this option is apparently not present for DS-6620 and S4148.

![image](https://github.com/user-attachments/assets/1dcb3093-ddc0-466f-ad69-8957fae9f9ec)

**Comment by vyshakav-dell** [comment]
Hi @KevinFerchau, unity uses net-snmp,  so doesn't support AES-256.

AES-256 (Advanced Encryption Standard with a 256-bit key) enhances the encryption capabilities of SNMPv3 beyond the standard. [However, net-snmp, the SNMP agent, does not support AES-256 with SNMPv3/USM1](https://stackoverflow.com/questions/32566585/does-net-snmp-support-aes-192-and-aes-256-encryption).

**Comment by KevinFerchau** [comment]
Hello all,

This question is related to the Connectrix DS-6620B SAN switches and PowerSwitch S4148 LAN in their storage environment.

You mention that AES256 is not supported with Unity, but what about these switches?

Perhaps they have a different plan for the Unity.

Thanks,

Kevin Ferchau
OEM Advisory Sales Engineer
Dell Technologies Design Solutions
Cell Phone: (602)-432-7440
Email: ***@***.******@***.***>

Your Solution. Dell Powered.
www.DellEMC.com/oem<http://www.dellemc.com/oem>



Internal Use - Confidential
