### ISSUE TITLE
[BUG]: karavictl storage create doesn't prompt for storage password  

### ISSUE THREAD

**Issue by atye** [dell/csm#1347]
### Bug Description

When creating a storage system, the option to input the password using STDIN doesn't work.

 

This is a regression that appears to have happened after 1.6.0 :

https://github.com/dell/karavi-authorization/blob/v1.6.0/cmd/karavictl/cmd/storage_create.go#L160

https://github.com/dell/karavi-authorization/blob/v1.9.1/cmd/karavictl/cmd/storage_create.go#L118

### Logs

NA

### Steps to Reproduce

Create storage with karavictl and see that prompt is not coming.

### Expected Behavior

Prompt should come.

### CSM Driver(s)

NA

### Container Orchestrator

NA

### Operating System

NA

**Comment by tdawe** [comment]
link: 25794
