### ISSUE TITLE
[BUG]: Revert PR csm-replication/pull/137 (static repctl)

### ISSUE THREAD

**Issue by donatwork** [dell/csm#1385]
### Bug Description

Reverting the change to enable a static build of repctl. It is causing many problems on some of our developer machines as some platforms may not have all of the needed static libraries. We will instead have the default as dynamic but add another target for a static build.

### Logs

[root@master-1-4hzX1TDQXeHOC repctl]# make
cp -f ../scripts/gen_kubeconfig.sh ./pkg/cmd/scripts/gen_kubeconfig.sh
cp -f ../scripts/config-placeholder ./pkg/cmd/scripts/config-placeholder
CGO_ENABLED=1 CGO_LDFLAGS="-static" go build ./cmd/repctl
# github.com/dell/repctl/cmd/repctl
/root/go1.22/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lresolv
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

make: *** [Makefile:6: build] Error 1

### Steps to Reproduce

Run make build in the repctl directory.

### Expected Behavior

A clean build of repctl.

### CSM Driver(s)

csm-replication

### Container Storage Modules Enabled

csm-replication

### Container Orchestrator

n/a

### Operating System

RHEL 8

**Comment by gallacher** [comment]
link: 26437

**Comment by donatwork** [comment]
Fix merged to main.
