### ISSUE TITLE
[FEATURE]: Unity consistency update to reduce the number of authentication API calls

### ISSUE THREAD

**Issue by sharmilarama** [dell/csm#1415]
**Describe the solution you'd like**
 CSM Unity was using login API , updating that to use BasicSystemInfo API to reduce the authentication requests to check array liveness probe. This improvement is aligned to match the behavior in other storage drivers.

**Describe alternatives you've considered**
None, work around is to turn off liveness probe in scaled environments

**Additional context**

**Comment by suryagupta4** [comment]
link: 26431

**Comment by suryagupta4** [comment]
@shanmydell : Can we close this git issue?

**Comment by suryagupta4** [comment]
@shanmydell : Do we need to update the milestone for this git issue?

**Comment by sharmilarama** [comment]
@suryagupta4 I have updated it. Thanks for bringing this up.
