### ISSUE TITLE
[BUG]:  Dell CSM Installation Issues

### ISSUE THREAD

**Issue by soudamsugit** [dell/csm#1416]
### Bug Description

We are using Dell Powermax on openshift. We were using Dell CSI Operator 1.12.o, currently installed Dell CSM Operator 1.5.1

The operator sucessfuly installed and we wanted to configure powermax, but following the instllation its not comming up

This git is not working from office netwrok of ANZ, Can we please connect over a call as this is blocking our production upgrade of openshfit. 

### Logs

We are using Dell Powermax on openshift. We were using Dell CSI Operator 1.12.o, currently installed Dell CSM Operator 1.5.1

The operator sucessfuly installed and we wanted to configure powermax, but following the instllation its not comming up

This git is not working from office netwrok of ANZ, Can we please connect over a call as this is blocking our production upgrade of openshfit. 

### Steps to Reproduce

NA

### Expected Behavior

CSM Installation

### CSM Driver(s)

CSM 1.5.1

### Installation Type

Mannual

### Container Storage Modules Enabled

Yes

### Container Orchestrator

Openshift

### Operating System

CoreOS

**Comment by soudamsugit** [comment]
The instllation not very straight and quite complicated to using. We are from ANZ bank need your help to resolve this issue

**Comment by soudamsugit** [comment]
Hello Team, any update on this one?

**Comment by sharmilarama** [comment]
@soudamsugit Thanks for reaching out, I see you had also raised this issue in Slack. We will follow up with you in that thread.

**Comment by suryagupta4** [comment]
This issue has been taken care over slack, closing the issue.
