### ISSUE TITLE
[QUESTION]:scini driver is not running

### ISSUE THREAD

**Issue by PalanirajR** [dell/csm#1417]
OCP - CSM - scini driver is not running

OCP VER 4.16.3

rmmod: ERROR: Module scini is not currently loaded
Error (1) unloading module binary /bin/emc/scaleio/scini.ko
[FAILED]

[32mINFO:    Starting scini service[0m
Loading the best matching scini driver for your kernel...
The running kernel version is 5.14.0-427.26.1.el9_4.x86_64
Didn't find a perfect match in /bin/emc/scaleio/scini_sync/driver_cache.
Attempting to find a best match...
Attempting to load /bin/emc/scaleio/scini_sync/driver_cache/RHEL9/4.5.2100.105/5.14.0-362.8.1.el9_3.x86_64/scini.ko (version: 5.14.0-362.8.1.el9_3.x86_64)...
insmod: ERROR: could not insert module /bin/emc/scaleio/scini_sync/driver_cache/RHEL9/4.5.2100.105/5.14.0-362.8.1.el9_3.x86_64/scini.ko: Invalid module format
Running driver_sync to fetch a matching driver...
Calling driver_sync "retrieve_blob_tar" with path RHEL416/4.5.2100.105/5.14.0-427.26.1.el9_4.x86_64
driver_sync.sh START - Fri Aug  9 21:06:10 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
Calling driver_sync "retrieve_blob_tar" with path RH/4.5.2100.105/5.14.0-427.26.1.el9_4.x86_64
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
No match after driver_sync fetch attempt.
Attempting to build the scini driver...
scini builder tarball is not available.
insmod: ERROR: could not load module iniLoadedVersion=67438644: No such file or directory
Failed to load the scini driver after it was built.
Will attempt to fetch the latest scini builder tarball...
Calling driver_sync "retrieve_file" with path RHEL416/4.5.2100.105/Dell-PowerFlex-scini_builder-4.5.2100.105.x86_64.tgz
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
Calling driver_sync "retrieve_file" with path RH/4.5.2100.105/Dell-PowerFlex-scini_builder-4.5.2100.105.x86_64.tgz
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
Failed fetching the builder tarball. Please check driver_sync.log
Failed to load driver scini.
Error (1) loading module binary /bin/emc/scaleio/scini.ko
rmmod: ERROR: Module scini is not currently loaded
Error (1) unloading module binary /bin/emc/scaleio/scini.ko

[32mINFO:    Starting scini service[0m
Loading the best matching scini driver for your kernel...
The running kernel version is 5.14.0-427.26.1.el9_4.x86_64
Didn't find a perfect match in /bin/emc/scaleio/scini_sync/driver_cache.
Attempting to find a best match...
Attempting to load /bin/emc/scaleio/scini_sync/driver_cache/RHEL9/4.5.2100.105/5.14.0-362.8.1.el9_3.x86_64/scini.ko (version: 5.14.0-362.8.1.el9_3.x86_64)...
insmod: ERROR: could not insert module /bin/emc/scaleio/scini_sync/driver_cache/RHEL9/4.5.2100.105/5.14.0-362.8.1.el9_3.x86_64/scini.ko: Invalid module format
Running driver_sync to fetch a matching driver...
Calling driver_sync "retrieve_blob_tar" with path RHEL416/4.5.2100.105/5.14.0-427.26.1.el9_4.x86_64
driver_sync.sh START - Fri Aug  9 21:06:10 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
Calling driver_sync "retrieve_blob_tar" with path RH/4.5.2100.105/5.14.0-427.26.1.el9_4.x86_64
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
No match after driver_sync fetch attempt.
Attempting to build the scini driver...
scini builder tarball is not available.
insmod: ERROR: could not load module iniLoadedVersion=67438644: No such file or directory
Failed to load the scini driver after it was built.
Will attempt to fetch the latest scini builder tarball...
Calling driver_sync "retrieve_file" with path RHEL416/4.5.2100.105/Dell-PowerFlex-scini_builder-4.5.2100.105.x86_64.tgz
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
Calling driver_sync "retrieve_file" with path RH/4.5.2100.105/Dell-PowerFlex-scini_builder-4.5.2100.105.x86_64.tgz
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync failed! Please check driver_sync.log
Failed fetching the builder tarball. Please check driver_sync.log
Failed to load driver scini.
Error (1) loading module binary /bin/emc/scaleio/scini.ko
rmmod: ERROR: Module scini is not currently loaded
Error (1) unloading module binary /bin/emc/scaleio/scini.ko
[FAILED]

[31mERROR:   *****************************[0m
[31mERROR:   ** Dumping driver_sync.log[0m
[31mERROR:   *****************************[0m
driver_sync.sh START - Fri Aug  9 21:06:10 UTC 2024
/bin/wget
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
/bin/wget
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
/bin/wget
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
driver_sync.sh START - Fri Aug  9 21:06:11 UTC 2024
/bin/wget
Error (gpg): File /config/emc_public_gpg_key must exist.
driver_sync.sh END - Fri Aug  9 21:06:11 UTC 2024
[31mERROR:   *****************************[0m
[31mERROR:   Failed to start scini driver[0m

**Comment by bharathsreekanth** [comment]
@PalanirajR It looks like PowerFlex SDC 4.5.2.1 is not compatible with kernel versions for OCP 4.16.3. This needs to be worked with the Powerflex engg team to see if they will add support for it or leverage the self-compile SDC enhancement within our CSI driver to build an SDC compatible with this specific kernel version.

**Comment by PalanirajR** [comment]
It was working fine and working in other 2 nodes just fine but we had issues with OSD going down and we were trying to replace with new one and stopped working after removing OSD1 and removing local pflex storage from the node. Not sure anything OSD cleanup did acting up like this.
