### ISSUE TITLE
[BUG]: Feedback link is not working in CSM-docs

### ISSUE THREAD

**Issue by WilsonRadadia20** [dell/csm#1421]
### Bug Description

Feedback link for all the drivers and modules are not working on clicking hyperlink after clicking Yes/No option for feedback the link breaks.

### Logs

![image-2024-08-09-16-14-09-262](https://github.com/user-attachments/assets/bc7fb62a-cf6d-429c-887f-481101d3475a)

### Steps to Reproduce

1. https://dell.github.io/csm-docs/docs/csidriver/test/powerstore/
2. click the Feedback down Yes/ No
3.  click No
4. click the Hyperlink Sorry to hear that. Please [tell us how we can improve](https://github.com/USERNAME/REPOSITORY/issues/new).
5. Link breaks

### Expected Behavior

The hyperlink for feedback should probably point to https://github.com/dell/csm/issues/new/choose.

### CSM Driver(s)

The hyperlink for feedback is not working for any driver or any modules.

### Container Orchestrator

N/A

### Operating System

N/A

**Comment by suryagupta4** [comment]
link: 27115
