### ISSUE TITLE
[QUESTION]:Is the kubernetes volume metrics (e.g. 'kubelet_volume_stats_used_bytes', 'kubelet_volume_stats_available_bytes') supported on a Unity 300

### ISSUE THREAD

**Issue by byrnes8** [dell/csm#1426]
### How can the Team help you today?

• Customer is using Prometheus to manage the Array.
• Red Hat case open already.
• The Customer is trying to create a Persistent Volume Claim resource on OpenShift platform but are unable to see the disk usage of PVCs. 
Currently, the PVCs appear to be completely empty, showing no disk usage. 
They can see the total. 
They state there is actually data on those PVCs but they can't see how much.
They want to see the occupancy rates of lun, pool and pvc areas in Emc Unity 300 on Redhat side.

Red Hat OpenShift Container Platform 4.14
Dell Container Storage Module Operator version 1.3.0. 
Using Dell Unity as an external storage via Dell CSI.

***************************
REDHAT Case open
****************************

“As we saw that the metrics in your cluster are not showing any details related to usage.
We need to check from the storage vendor side if these metrics are getting exposed to Prometheus or not.

If the metrics are not exposed to Prometheus, then we will not be able to get the usage details”.

*******************
Prometheus Version
*******************
version 2.46.0 

![image](https://github.com/user-attachments/assets/ea2c9cfb-d265-4bf7-9e77-59ceeb636c28)

*************
Main Query
**************

• Does the CSI driver in question (csi-unity.dellemc.com) implement the CSI RPC NodeGetVolumeStats call necessary that returns this information?
• REF | https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetvolumestats [github.com]
• Is the kubernetes volume metrics (e.g. 'kubelet_volume_stats_used_bytes', 'kubelet_volume_stats_available_bytes') supported.

***********************
Internal DELL consult
**********************
https://dell.github.io/csm-docs/docs/observability/ >>>> as per this page  Unity does not have Observability 

********************
Request
********************

Just want to confirm if this is the case:
Unity does not have Observability for :
UNITY 300
The OE code for this is  5.1.0.0.5.394.

**Comment by adarsh-dell** [comment]
Hi @byrnes8 ,
**Please find my analysis regarding your query:**

1. **Capabilities Supported by CSI-Unity Driver:**
   - **GET_VOLUME_STATS:** Yes! Supported. [Link](https://github.com/dell/csi-unity/blob/756d20e3c62730c6bc5b9e42ae77ac62b32a8951/service/node.go#L815)
   - **VOLUME_CONDITION:** Yes! Supported. [Link](https://github.com/dell/csi-unity/blob/756d20e3c62730c6bc5b9e42ae77ac62b32a8951/service/controller.go#L770)
   -  These capabilities are supported only when volume health monitoring is enabled. [Check the logic here](https://github.com/dell/csi-unity/blob/756d20e3c62730c6bc5b9e42ae77ac62b32a8951/service/controller.go#L776).

2. **Volume Health Monitoring:**
   - For more information on enabling and disabling volume health monitoring on the controller and node side, visit:
     - [Installation Guide](https://dell.github.io/csm-docs/docs/deployment/helm/drivers/installation/unity/#install-csi-driver)
     - [Volume Health Monitoring](https://dell.github.io/csm-docs/docs/csidriver/features/unity/#volume-health-monitoring)
  
![image](https://github.com/user-attachments/assets/f2e0b1f6-8143-428f-9c3f-89cd24b50cf0)

3. **Implementation Details:**
   - **NodeGetVolumeStats Implementation:** [Link](https://github.com/dell/csi-unity/blob/756d20e3c62730c6bc5b9e42ae77ac62b32a8951/service/node.go#L835)
   - **Controller Side Health Tracking and Reporting:** [Link](https://github.com/dell/csi-unity/blob/756d20e3c62730c6bc5b9e42ae77ac62b32a8951/service/controller.go#L1836)
   -  Read more details [here](https://github.com/kubernetes-csi/external-health-monitor#overview).
   
![image](https://github.com/user-attachments/assets/5521f518-ca3d-4b53-8bac-b8fec81ed5a3)

4. **Kubernetes Volume Metrics:**
   - Regarding the support for Kubernetes volume metrics (e.g., 'kubelet_volume_stats_used_bytes', 'kubelet_volume_stats_available_bytes'), please refer to the struct returned in the response as per the standard: [Link](https://github.com/dell/csi-unity/blob/756d20e3c62730c6bc5b9e42ae77ac62b32a8951/service/node.go#L929)

5. **Observability support**
   - This is a valid point, All above data that I have shared is wrt health monitoring feature with the help of health monitor sidecar so if user will enable this (vol health monitoring) feature then we will be able to see all these stats after describing the PVC resource. **For Observability support, yes your finding is correct that we don't have this support for csi-unity driver.**
   
![image](https://github.com/user-attachments/assets/76e32e3f-53de-4b90-805e-6ee4aa9adcba)


**Thanks,**
**Adarsh**

**Comment by byrnes8** [comment]
Thank you Adarsh,

If possible can you keep this issue open, in case I have any queries on the above.

Thanks,
Séamus

**Comment by adarsh-dell** [comment]
Sure.

> Thank you Adarsh,
> 
> If possible can you keep this issue open, in case I have any queries on the above.
> 
> Thanks, Séamus

Sure

**Comment by shanmydell** [comment]
Hi @byrnes8 , 

As the query is answered, closing this ticket.

You can reopen this ticket if you have any further queries.

If you have new query, you can open a new ticket.

Thanks,
Yamuna

**Comment by byrnes8** [comment]
Thanks Adarsh,

Regards,
Séamus Byrne
Senior Engineer| ISG EMEA Support Services
Dell Technologies| ISG Regional Storage Support
***@***.******@***.***>
Working hours: 08:30AM – 17:00 PM GMT+1, Monday-Friday
Click here to contact Dell EMC Customer Support [dellemc.com]<https://urldefense.com/v3/__https:/www.dellemc.com/resources/en-us/asset/technical-guides-support-information/solutions/h4165-csc-phonelist-ho.pdf__;!!LpKI!hEsi3NcpiIf781VqZGoDxjCFVrRl7TZhzgS5sX-LmOgUfumdWbESGD-9oNQkd2ulpg97WJJeb8xg4bqjNc-1fK1RexA$>
Please consider the environment before printing this email.



Internal Use - Confidential
