### ISSUE TITLE
[BUG]: CSM Operator e2e tests: Error in test 3

### ISSUE THREAD

**Issue by francis-nijay** [dell/csm#1427]
### Bug Description

Test 3 of CSM operator connectivity client test throws error - Mismatch with struct type Resource

### Logs

 error - Mismatch with struct type Resource

### Steps to Reproduce

Execute e2e connectivity client test

### Expected Behavior

Test should run successfully

### CSM Driver(s)

CSI Powerflex

### Container Orchestrator

Kubernetes

### Operating System

RHEL

**Comment by rajkumar-palani** [comment]
As discussed with @francis-nijay , this issue is related to Neptune and no longer needed. Closing it.
