### ISSUE TITLE
[BUG]:  Dell CSI Operator listed two times after upgrade (1.2.0 + 1.5.0)

### ISSUE THREAD

**Issue by infrahvs** [dell/csm#144]
**Describe the bug**
Openshift upgraded to 4.8.20.
Operator upgraded from 1.2.0 to 1.5.0 but remains stuck in mode.
The Operator remains functional and provides storage to pods.

Dell CSI Operator 1.2.0 provided by Dell EMC remains in status Cannot update (Warning symbol) "CatalogSource was removed"
Dell CSI Operator 1.5.0 provided by Dell EMC remains in status "Pending"  (Hourglass symbol)  "Upgrade available"

Is there a safe way to resume/restart the upgrade ?

**To Reproduce**
Sandbox cluster has been upgraded without issue.
Production cluster remains stuck mid-upgrade, was on exact same version than sandbox cluster.

**Expected behavior**
To have only one CSI operator to version 1.5.0

**Logs**
Logs CSI Operator 1.5
![CSI_1 5](https://user-images.githubusercontent.com/96285193/146938713-8ebb5e02-4e1c-4eed-aa94-ba7379c85ca8.png)

Logs CSI Operator 1.2
![CSI_1 2](https://user-images.githubusercontent.com/96285193/146938717-ece935ee-dbb9-430d-adb4-934ad149e4da.png)

Deployments are still linked to 1.2.0
![deployments](https://user-images.githubusercontent.com/96285193/146939053-4f4aeb1a-96b5-41f8-9b79-33d7bad2ffdb.png)

**System Information (please complete the following information):**
 -  Openshift 4.8.20
 - OS image Red Hat Enterprise Linux CoreOS 48.84.202111061102-0 (Ootpa)

**Additional context**

**Comment by rensyct** [comment]
Hi @infrahvs 
Sorry to know that the upgrade went to a hung state in the production clusters. This happened because the listing of the latest version (v1.6.0) of dell-csi-operators from RedHat took place during the upgrade of the production cluster from v1.2.0 to v1.5.0.
We had reached out to RedHat and for now they have removed the listing of v1.6.0
Could you please help let us know the status of upgrade as v.1.6.0 listing has been removed

**Comment by infrahvs** [comment]
Hello,



I see the Subscription details Update channel is displaying dell-csi-operator-certified.v1.5.0 (no more 1.6.0)

But I still have two CSI Operators, any way to safely resume/complete the upgrade ?





B R



Anael

**Comment by bandak2** [comment]
Hi @infrahvs,

Sorry for the delay.
RedHat team is looking into it. They had to pull out the dell-csi-operator v1.6.0 from the index to streamline the releases from their end. However, since it's the Holiday week, the Red Hat folks are away for holidays and the latest response that we can get would be from the 3rd of Jan 2022.
We'll revert once we hear from Red Hat.

Thanks,
Keerthi

**Comment by rensyct** [comment]
Hi @infrahvs 
Apologies for the delay in response. We have initiated the conversation with RedHat again regarding this as they had mentioned for our previous communication that their team are away for Holidays. We have requested for a call with them to help get a solution for this issue.

**Comment by rensyct** [comment]
Hi @infrahvs 
Do you see an "update", or "cancel" or "retry" option in UI.

**Comment by infrahvs** [comment]
Hello,

Operators > Installed Operators :
On Dell CSI Operator (1.2.0), I have “Delete ClusterServiceVersion”
On Dell CSI Operator (1.5.0), I have “Edit Subscription” or Uninstall Operator”

 

 

Operators > OperatorHub : only “Uninstall”.

 

 

 

 

Meilleures salutations.

 

Anaël Savioz

Ingénieur Système

 

Hôpital du Valais
Centre de Services – IT Operations

Avenue du Grand-Champsec 86
case postale 696
1951 Sion

 

Tél. team : +41 27 603 66 10  |  Tél. direct :  +41 27 603 15 13 
 ***@***.***> ***@***.*** |  <https://urldefense.com/v3/__http:/www.hopitalvs.ch__;!!LpKI!2D9q3t7CpZnMtpCwPuRi6VjRBE00idMMdsytbxfvjSC6Y47H2Ocgy0z36Cd2t5EXochDnA$> www.hopitalvs.ch [hopitalvs.ch]

**Comment by rensyct** [comment]
Thank you @infrahvs for your response
Could you please help send screenshot for all of the below
Operators > Installed Operators :
On Dell CSI Operator (1.2.0), I have “Delete ClusterServiceVersion”
On Dell CSI Operator (1.5.0), I have “Edit Subscription” or Uninstall Operator”
Operators > OperatorHub : only “Uninstall”.

**Comment by infrahvs** [comment]
Hello,


Please find them below

 



 

 



 



 

 

 

Meilleures salutations.

 

Anaël Savioz

Ingénieur Système

 

Hôpital du Valais
Centre de Services – IT Operations

Avenue du Grand-Champsec 86
case postale 696
1951 Sion

 

Tél. team : +41 27 603 66 10  |  Tél. direct :  +41 27 603 15 13 
 ***@***.***> ***@***.*** |  <https://urldefense.com/v3/__http:/www.hopitalvs.ch__;!!LpKI!2D9q3t7CpZnMtpCwPuRi6VjRBE00idMMdsytbxfvjSC6Y47H2Ocgy0z36Cd2t5EXochDnA$> www.hopitalvs.ch [hopitalvs.ch]

**Comment by rensyct** [comment]
I am not able to see any screenshots. Could you please help send those again

**Comment by infrahvs** [comment]
Using web interface this time :

![2022-01-07_08-33-28](https://user-images.githubusercontent.com/96285193/148517971-6586d50d-c34e-472e-bef9-f2e2cdc869fd.png)
![2022-01-07_08-34-25](https://user-images.githubusercontent.com/96285193/148517978-48095dfc-c0f2-4568-a641-4ccb34c8a1ef.png)
![2022-01-07_08-32-42](https://user-images.githubusercontent.com/96285193/148517982-e9977de5-52c2-4ea8-b645-0a1a76b7407a.png)

**Comment by rensyct** [comment]
Thank you @infrahvs for the screenshots. This helps. We wanted to know if you would be willing to move to the latest version of dell-csi-operator which is v1.6.0

**Comment by infrahvs** [comment]
We have upgraded our openshift cluster from 4.7 to  4.8.20 and after that we did the operator upgrade.

(and if the 1.6.0 version can help I can try to upgrade to that version).

**Comment by rensyct** [comment]
Was the operator upgrade done through UI?
After the upgrade hung, was there anything else that was done on the cluster?

**Comment by infrahvs** [comment]
Hello,

All from the UI, yes.


Nothing has been done since then, I don’t want to play with it and loose any data.

 

 

Meilleures salutations.

 

Anaël Savioz

Ingénieur Système

 

Hôpital du Valais
Centre de Services – IT Operations

Avenue du Grand-Champsec 86
case postale 696
1951 Sion

 

Tél. team : +41 27 603 66 10  |  Tél. direct :  +41 27 603 15 13 
 ***@***.***> ***@***.*** |  <https://urldefense.com/v3/__http:/www.hopitalvs.ch__;!!LpKI!2D9q3t7CpZnMtpCwPuRi6VjRBE00idMMdsytbxfvjSC6Y47H2Ocgy0z36Cd2t5EXochDnA$> www.hopitalvs.ch [hopitalvs.ch]

**Comment by rensyct** [comment]
Thank you for your response @infrahvs . RedHat team want to know the actual state of the cluster before they can help provide a solution. Please help with the below info

From the UI, we would need below mentioned YAML files
1. Installed-operators => Dell CSI Operator => Subscription => Install Plan link (available to the right) => YAML tab contents
2. Installed-operators => Dell CSI Operator => Subscription => CatalogSource link (available to the right) => YAML tab contents
3. Installed-operators => Dell CSI Operator => YAML

The subscription will live in the namespace where the operator is installed (if installed to "all namespaces" then the namespace would be "openshift-operators"):

Get the subscription (there should only be one) and output that to a file:

$ oc get subscription -n openshift-operators -o yaml > dell-csi-subscription-1.2.0.yaml

The InstallPlan is where I would look next. Any errors with the 1.5.0 operator (why it's stuck in a pending state) should show up there under the Status field:

$ oc get installplan -n openshift-operators  -o yaml > dell-csi-installplan.yaml

If the status field is still inconclusive as to why the 1.5.0 pod(s) aren't being scheduled, you can look at the pod status to see why:

$ oc get pod -n openshift-operators -o yaml > dell-csi-pod.yaml

It may also help to get the pod status of the certified catalog source pod. You need to know the name (uuid) of the certified catalog pod first:

$ export PODNAME=$(oc get po -n openshift-marketplace -o custom-columns=:metadata.name | grep certified)

$ oc get po $PODNAME -n openshift-marketplace -o yaml > certified-operators-pod.yaml

**Comment by infrahvs** [comment]
[certified-operators-pod-59l29.txt](https://github.com/dell/csm/files/7853088/certified-operators-pod-59l29.txt)
[certified-operators-pod-grhxz.txt](https://github.com/dell/csm/files/7853089/certified-operators-pod-grhxz.txt)
[dell-csi-installplan.txt](https://github.com/dell/csm/files/7853090/dell-csi-installplan.txt)
[dell-csi-pod.txt](https://github.com/dell/csm/files/7853091/dell-csi-pod.txt)
[dell-csi-subscription.txt](https://github.com/dell/csm/files/7853092/dell-csi-subscription.txt)

**Comment by infrahvs** [comment]
It seems the RequirementsNotMet is saying the older version of the CSI Operator is owning the service account.
reason: RequirementsNotMet
  requirementStatus:
...
    - group: ''
      kind: ServiceAccount
      message: Service account is owned by another ClusterServiceVersion
      name: dell-csi-operator-manager-service-account
      status: PresentNotSatisfied
      version: v1

**Comment by rensyct** [comment]
Thank you @infrahvs  for attaching subscription and installplan. Please help attach the catalogsource as well.

**Comment by infrahvs** [comment]
[installplan.txt](https://github.com/dell/csm/files/7854573/installplan.txt)

**Comment by rensyct** [comment]
InstallPlan was attached earlier. Please help get the catalogsource. You can also get the catalogsource from the UI
Installed-operators => Dell CSI Operator => Subscription => CatalogSource link (available to the right) => YAML tab contents

**Comment by infrahvs** [comment]
[CatalogSource.txt](https://github.com/dell/csm/files/7854704/CatalogSource.txt)

**Comment by bandak2** [comment]
Thanks for the logs @infrahvs. We passed on the logs to the RH team. They've taken a look and are interested in the service account which is holding onto the older CSV; which can help provide further insights to proceed further.
Can you please provide us with the output of the following command from the installed operator namespace?
`oc get sa dell-csi-operator-manager-service-account -o yaml > dell-csi-operator-manager-service-account.yaml`

**Comment by infrahvs** [comment]
The service account is missing.

oc get sa dell-csi-operator-manager-service-account
Error from server (NotFound): serviceaccounts "dell-csi-operator-manager-service-account" not found

oc get sa dell-csi-operator-manager-service-account -A
error: a resource cannot be retrieved by name across all namespaces


FYI the service account is present in our sandbox environment. 
[sa-sandbox.txt](https://github.com/dell/csm/files/7860808/sa-sandbox.txt)

**Comment by bandak2** [comment]
can you please try that again over the namespace where the operator is installed, like:
`oc get sa dell-csi-operator-manager-service-account -n openshift-operators -o yaml > dell-csi-operator-manager-service-account.yaml`

**Comment by infrahvs** [comment]
apiVersion: v1
imagePullSecrets:
- name: dell-csi-operator-manager-service-account-dockercfg-kxm4g
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-01-27T20:45:06Z"
  labels:
    control-plane: controller-manager
    operators.coreos.com/dell-csi-operator-certified.openshift-operators: ""
  name: dell-csi-operator-manager-service-account
  namespace: openshift-operators
  ownerReferences:
  - apiVersion: operators.coreos.com/v1alpha1
    blockOwnerDeletion: false
    controller: false
    kind: ClusterServiceVersion
    name: dell-csi-operator-certified.v1.2.0
    uid: db9c1631-98ef-441f-a24b-eb191dc0ecdd
  resourceVersion: "495458974"
  uid: e3dd24ae-1d1f-4d45-991f-61a4e35056e9
secrets:
- name: dell-csi-operator-manager-service-account-token-427d8
- name: dell-csi-operator-manager-service-account-dockercfg-kxm4g

**Comment by bandak2** [comment]
Thanks much.! can you gather the CSV info for both the observed versions, and share the files.
oc describe csv dell-csi-operator-certified.v1.2.0 > dell-csi-operator-csv-1.2.0.yaml
oc describe csv dell-csi-operator-certified.v1.5.0 > dell-csi-operator-csv-1.5.0.yaml

**Comment by infrahvs** [comment]
[dell-csi-operator-csv-1.2.0.txt](https://github.com/dell/csm/files/7861024/dell-csi-operator-csv-1.2.0.txt)
[dell-csi-operator-csv-1.5.0.txt](https://github.com/dell/csm/files/7861025/dell-csi-operator-csv-1.5.0.txt)

**Comment by bandak2** [comment]
Hi @infrahvs ,

Thanks for sharing the requested details.
RH team responded with the recommended way to proceed with the upgrade. They've tried various options internally and suggested the following procedure as the best way to proceed with the upgrade. Meanwhile, we'll check with the RH team to see if we can simulate or reproduce the issue on a sandbox cluster to gain more confidence in the provided solution.

Here are the excerpts from RH conversations suggesting the workaround.

> After further testing, the safest way to move forward is to run the following command in the namespace where the operator is installed:
`oc edit sa dell-csi-operator-manager-service-account`

> And remove the metadata.ownerReferences block from the service account yaml so that this:

```
apiVersion: v1
imagePullSecrets:
- name: dell-csi-operator-manager-service-account-dockercfg-kxm4g
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2021-01-27T20:45:06Z"
    labels:
      control-plane: controller-manager
      operators.coreos.com/dell-csi-operator-certified.openshift-operators: ""
    name: dell-csi-operator-manager-service-account
    namespace: openshift-operators
  ownerReferences:
    - apiVersion: operators.coreos.com/v1alpha1
      blockOwnerDeletion: false
      controller: false
      kind: ClusterServiceVersion
      name: dell-csi-operator-certified.v1.2.0
      uid: db9c1631-98ef-441f-a24b-eb191dc0ecdd
  resourceVersion: "495458974"
  uid: e3dd24ae-1d1f-4d45-991f-61a4e35056e9

```  

> becomes:

```
apiVersion: v1
imagePullSecrets:
- name: dell-csi-operator-manager-service-account-dockercfg-kxm4g
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2021-01-27T20:45:06Z"
    labels:
      control-plane: controller-manager
      operators.coreos.com/dell-csi-operator-certified.openshift-operators: ""
    name: dell-csi-operator-manager-service-account
    namespace: openshift-operators
  resourceVersion: "495458974"
  uid: e3dd24ae-1d1f-4d45-991f-61a4e35056e9  

```  

> This had proven to be the safest, least error prone method of altering the ownerReferences field of the service account. I was able to simply remove the block 100% of the time without causing destruction to the service account. Editing/modifying the block is more error-prone, and I, therefore, do not recommend it. If you change the owner of a service account to an object that doesn't exist (incorrect name or uid), then the service account is likely to get destroyed by k8s garbage collection.
> Once the erroneous ownerReference is removed from the service account, the upgrade should progress and soon finish.

We'll revert with their suggestions on the reproduction of the issue on the sandbox cluster.

**Comment by bandak2** [comment]
Hi @infrahvs,

We got the scripts from RH that they used to test this. There are 3 scripts which do the following

**install-dell-csi-operator-v1.2.0.sh** -- creates a project with name 'dell-csi-test' and installs a sample dell-csi-operator-v1.2.0 operator (but without the CRs) in that namespace.
**patch-service-account.sh** -- patches the dell-csi-operator-manager-service-account service account to remove owner references on the account and prints the resultant service account yaml.
**approve-and-install-v1.5.0.sh** -- approves the install plan to install dell-csi-operator-v1.5.0. 

Attaching the zip file for the scripts that were shared by the RH team, and the logs from our execution in the lab.
[script-and-logs.zip](https://github.com/dell/csm/files/7925315/script-and-logs.zip)

After installing the v1.2.0 operator using '_install-dell-csi-operator-v1.2.0.sh_', we ran the '_patch-service-account.sh_' shell script to remove the owner references from the service account. Following that, we ran the '_approve-and-install-v1.5.0.sh_' script to upgrade the operator to the v1.5.0 version. 
It was updated as expected and the CSV reflected the latest version.

Request you to go through the attached scripts and our sample log and try it on a sandbox to confirm that it works for you before you can proceed with your production cluster.

**Comment by bandak2** [comment]
Hi @infrahvs, Were you able to try patching the ownershipRef on the dell-csi-operator-manager-service-account ?
Can you please try it and let us know if you were able to proceed with the upgrade? 
We can check further based on your observations.

**Comment by infrahvs** [comment]
Hello, the operator is fine and at version 1.5.0 since last week. Thanks for the support.
