### ISSUE TITLE
[FEATURE]: PowerStore Sync / Metro for Block - CSM Replication

### ISSUE THREAD

**Issue by Prabhu-Dell** [dell/csm#1443]
**Describe the solution you'd like**
Enable the functionality of volume replication to another PowerStore node synchronously, including ESX metro volumes, only for Block.

The feature should enable

- Metro replication capabilities.
- Array native metro replication.
- Metro Volume and Sync replication.

**Comment by donatwork** [comment]
Feature merged into main. Resolving issue.
