### ISSUE TITLE
[BUG]: Gobrick does not clean wwids from /etc/multipath/wwids after removing multipath devices 

### ISSUE THREAD

**Issue by AkshaySainiDell** [dell/csm#1447]
### Bug Description

Gobrick executes the following set of commands for removing a multipath device:

```bash
multipath -f /dev/dm-2
echo 1 > /sys/class/block/sdf/device/delete
multipathd del path /dev/sdf
```

These commands do not remove entries from the /etc/multipath/wwids file, resulting in stale entries being left behind. The growing count of entries could potentially impact the performance of multipath if the file becomes exceptionally large.

To address this issue, Gobrick should be enhanced to remove a device from the `wwids` file using below command:
```bash
multipath -w mpathX (or WWID)
```

### Logs

N/A

### Screenshots

![image](https://github.com/user-attachments/assets/67696154-f928-47a9-8847-0fc11fb81410)

### Steps to Reproduce

Using any CSM Driver:

1. Create a PVC.
2. Create a POD that consumes the PVC.
3. Note the WWIDs on the worker node where the POD is scheduled:
   ```bash
   wc -l /etc/multipath/wwids
   ```
4. Delete the POD.
5. Check the WWIDs again:
   ```bash
   wc -l /etc/multipath/wwids
   ```
   **Observation:** The count will not decrease.

### Expected Behavior

Stale devices from `wwids` file should be removed

### CSM Driver(s)

All CSM drivers

### Container Orchestrator

N/A

### Operating System

N/A

**Comment by AkshaySainiDell** [comment]
link: 27849

**Comment by gallacher** [comment]
@AkshaySainiDell, please add labels for all impacted CSM components.  Thanks.
