### ISSUE TITLE
[BUG]: Dead links in Documentation 

### ISSUE THREAD

**Issue by shanmydell** [dell/csm#1464]
### Bug Description

There are dead links in csm documentation

### Logs

![image](https://github.com/user-attachments/assets/c9fe5da8-20d3-4359-9229-586f3f782da3)

### Steps to Reproduce

Please run a dead link checker on the website 

### Expected Behavior

There should not be any deadlinks.
**Explore new solutions that will verify external links as well**

### CSM Driver(s)

Documentation 

### Container Orchestrator

NA

### Operating System

NA

**Comment by patilv3** [comment]
link: 29785
