### ISSUE TITLE
[QUESTION]: Will CSM for Authorization V2 get rid of PV requirement for Redis?

### ISSUE THREAD

**Issue by thikade** [dell/csm#1466]
### How can the Team help you today?

**Details: ?**
CSM for Authorization v1.x requires a PV for the Redis deployment, which unfortunately needs another storageclass. Node local storage works for PoCs, but having the authorization server Redis pod pinned to a specific node would be a pretty bad design decision.   
The dependency on another storageclass to setup the DELL CSI driver and CSMs is quite frustrating.  

Therefore my question: will this requirement for Redis PV, - and more important - for requiring another storageclass be dropped in v2?

**Comment by atye** [comment]
Hi @thikade. Yes, that requirement is dropped in v2. In v2, Redis Sentinel (highly available) uses the [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) volume so you don't have to specify any storage class.

If you are using Powerflex storage, I recommend to have a look at CSM Authorization v2.0.0 Tech Preview. 

https://dell.github.io/csm-docs/docs/deployment/csmoperator/modules/authorization-v2.0-tech-preview/
https://dell.github.io/csm-docs/docs/authorization/v2.0-tech-preview/

**Comment by thikade** [comment]
Sounds good, thanks for the heads-up, will have a closer look at v2 sooner than expected.
No - we are using _PowerMax_ storage - will that be an issue?

**Comment by thikade** [comment]
.... and two things came up when reviewing v2 docs, though:
1. Is this a doc bug? v2 deployment instructions still show the PV / SC requirement! See [1]
2. A new requirement introduces a dependency to Hashicorp Vault. 
  Is there any other credentials manager support on the roadmap, or even just plain Kubernetes secrets maybe - which would enable a fast start? 

[1]  
https://dell.github.io/csm-docs/docs/deployment/csmoperator/modules/authorization-v2.0-tech-preview/#install-csm-authorization-proxy-server

![image](https://github.com/user-attachments/assets/f4f03fda-ca92-4d57-9c5c-9520ce200850)

**Comment by atye** [comment]
Yes, the Tech Preview is only for Powerflex. In CSM 1.12, the next release planned for early November, Authorization v2 will support Powermax. 

That table row appears to be a documentation bug. The Operator Authorization CR [sample file](https://github.com/dell/csm-operator/blob/dc2a6cf47590e237c7719819ceed3fce3a2cf5e1/samples/authorization/csm_authorization_proxy_server_v200-alpha.yaml#L69) does not include a storageClass parameter.

For the time being, we are only supporting Hashicorp Vault. You may open a feature request for another manager or k8s secrets.

**Comment by thikade** [comment]
Thanks for the answers, looking forward to v1.12, and going to create a RFE!
