### ISSUE TITLE
[BUG]: CSM Operator - Changes to csiDriverSpec does not reflect in CSM state or csidrivers.storage.k8s.io object

### ISSUE THREAD

**Issue by nitesh3108** [dell/csm#1475]
### Bug Description

When updating csiDriverSpec.storageCapacity field, the change is reflected in the CSM object but does not get reflected in the csidrivers.storage.k8s.io resource. The csidrivers.storage.k8s.io resource should update when storageCapacity is changed. If it can't be updated because of some issue, the state of the CSM object should move to Failed state.

 

### Logs

Example: storageCapacity set to true when initially deployed. Then updated to false. See CSM object and csidrivers.storage.k8s.io resource

# kubectl get csm isilon -n isilon -o yaml
apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  annotations:
    storage.dell.com/CSMOperatorConfigVersion: v2.11.0
    storage.dell.com/CSMVersion: v1.11.0
spec:
  driver:
    authSecret: isilon-creds
    common:
 ....
      image: dellemc/csi-isilon:v2.11.0
      imagePullPolicy: IfNotPresent
    configVersion: v2.11.0
    controller:
...
    csiDriverSpec:
      fSGroupPolicy: ReadWriteOnceWithFSType
    csiDriverType: isilon
    dnsPolicy: ClusterFirstWithHostNet
    forceRemoveDriver: true
    node:
...
  modules:
...
status:
  controllerStatus:
    available: "1"
    desired: "1"
    failed: "0"
  nodeStatus:
    available: "2"
    desired: "2"
    failed: "0"
  state: Succeeded
 

# kubectl get csidrivers.storage.k8s.io csi-isilon.dellemc.com -o yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  creationTimestamp: "2024-08-15T20:15:27Z"
  name: csi-isilon.dellemc.com
  resourceVersion: "3953213"
  uid: 31d00f0b-f5e4-46ee-a112-5e73ec87000f
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: true
  volumeLifecycleModes:
  - Persistent
  - Ephemeral

### Steps to Reproduce

- Install csm operator 
- Install PowerScale driver with storageCapacity enabled
- Disable storageCapacity during runtime
- It's not reflecting the latest value its still showing enabled

### Expected Behavior

- Install csm operator 
- Install PowerScale driver with storageCapacity enabled
- Disable storageCapacity during runtime
- StorageCapacity should be disabled

### CSM Driver(s)

CSI PowerScale v2.11.0

### Installation Type

CSM Operator

### Container Orchestrator

K8s

### Operating System

RHEL

**Comment by gallacher** [comment]
link: 27258
