### ISSUE TITLE
[BUG]: SDC 4.5.2.1 fails to load when deployed on OCP 4.16.x using csm-operator

### ISSUE THREAD

**Issue by suryagupta4** [dell/csm#1482]
### Bug Description

csm-operator v1.6.0 pulling the older sdc 4.5.2.1 image when deployed on OCP 4.16.x which has a different SHA id. The latest sdc 4.5.2.1 patch is available with the same tag but with a different SHA id.

### Logs

NA

### Steps to Reproduce

Deploy PowerFlex via CSM-Operator v1.6.0 using the ocp PowerFlex sample having SHA image reference

### Expected Behavior

SDC init container should be able to deploy SDC on the worker nodes without any issues

### CSM Driver(s)

CSM Operator v1.6.0
CSI PowerFlex v2.11.0

### Installation Type

Operator

### Container Orchestrator

OCP 4.16

### Operating System

CoreOS

**Comment by suryagupta4** [comment]
link: 28461

**Comment by jooseppi-luna** [comment]
Fixed -- **please note**: to get the latest 4.5.2.1 SDC image, `ImagePullPolicy` for the `dellemc/sdc:4.5.2.1` image will have to be set to `Always`.
