### ISSUE TITLE
[BUG]: CSM Can't build offline package

### ISSUE THREAD

**Issue by liuj23CD** [dell/csm#1489]
### Bug Description

  bash scripts/csm-offline-bundle.sh -c

ERROR
Received a non-zero return code (1) from the following comand:
  /usr/bin/docker pull dellemc/csi-isilon:v2.12.0

Output was:
Error response from daemon: manifest for dellemc/csi-isilon:v2.12.0 not found: manifest unknown: manifest unknown

 

### Logs

(base) root@liuj23-ubuntu:~/csm-operator# bash scripts/csm-offline-bundle.sh -c

*
* Building image manifest file

   Processing file /root/csm-operator/operatorconfig/driverconfig/common/default.yaml
   Processing file /root/csm-operator/bundle/manifests/dell-csm-operator.clusterserviceversion.yaml

*
* Pulling and saving container images

   bitnami/kubectl:1.28
   dellemc/connectivity-cert-persister-k8s:0.11.0
   dellemc/connectivity-client-docker-k8s:1.19.0
   dellemc/csi-isilon:v2.12.0

ERROR
Received a non-zero return code (1) from the following comand:
  /usr/bin/docker pull dellemc/csi-isilon:v2.12.0

Output was:
Error response from daemon: manifest for dellemc/csi-isilon:v2.12.0 not found: manifest unknown: manifest unknown

Exiting

### Steps to Reproduce

bash scripts/csm-offline-bundle.sh -c

### Expected Behavior

check the csmoffline-bundle.sh file

### CSM Driver(s)

latest

### Container Orchestrator

rke2r1

### Operating System

centos

**Comment by jooseppi-luna** [comment]
@liuj23CD -- it looks like you are using scripts from the main branch, rather from the v1.11.0 tagged release. v1.12.0 has not been released yet, which is why the pull is failing. Using one of the tagged release branches instead should fix this problem!
