### ISSUE TITLE
[QUESTION]:How can I use a dedicated VLAN interface on OpenShift worker when using Unity-CSI

### ISSUE THREAD

**Issue by kumbalakandy** [dell/csm#1492]
### How can the Team help you today?

**Details: ?**
I deployed Dell CSM and Unity CSI. I am using NFS protocol to access the Unity. How can I use a dedicated interface for this? The interface (VLAN) is created using NMState Operator.

**Comment by atye** [comment]
Hi @kumbalakandy. I assume you are running CSM v.1.11.0. In the Unity CR below, you'll see a configuration parameter for custom networks NFS traffic with comments about how to use it.

https://github.com/dell/csm-operator/blob/af9597868ef08575b7427dc57f0d7aa562086477/samples/storage_csm_unity_v2110.yaml#L149

**Comment by kumbalakandy** [comment]
Hi @atye,
I am using CSM  v1.6.0 via OpenShift Operator Hub. I have done the following to get it working:
1. I have created a VLAN interface on all my worker nodes using NMState (Ex IP: 172.19.21.x/24)
2. Used a different VLAN for Unity NFS. This is to send the traffic through the firewall. This will help me to see the logs if the traffic is being generated from the right interface. 
3. Added a static static route on the VLAN interface which I created in the step 1. 
4. Deployed Unity CSM, CSI, and created a NFS storage class (used the X_CSI_ALLOWED_NETWORKS environment variable) . 
5. Created  PVC using the storage class created in the step 4. 
6. Deployed some application to the PVC created in the step 5 and validated. 

Please let me know if I missed something or done extra here.

**Comment by atye** [comment]
@kumbalakandy That all looks good to me and sounds like it's working as expected. If you don't any further issues, please feel free to close this issue.
