### ISSUE TITLE
[QUESTION]: repctl - how to delete ReplicationGroups from CLI

### ISSUE THREAD

**Issue by murphyry** [dell/csm#1506]
Hello,

While using repctl to control ReplicationGroups I have not been able to find a way to delete old/state ReplicationGroups once they no-longer existing on the backend storage array.

Right now I have 4x ReplicationGroups that are empty and no-longer existing on the backend PowerFlex systems. How do I delete them with repctl? If I cant delete them with repctl what is the process to clear out these stale entries?

![image](https://github.com/user-attachments/assets/296a6774-9083-4c7a-9173-1651683e8c9d)
![image](https://github.com/user-attachments/assets/34478296-3c11-40d8-b9f2-85e470cc7eb4)

**Comment by santhoshatdell** [comment]
Hi @murphyry The replication groups can be deleted with _kubectl_ command. Please refer to https://dell.github.io/csm-docs/docs/replication/replication-actions/#deleting-replication-groups

**Comment by murphyry** [comment]
That did the trick, I didn't see that down there at the bottom. Thank you!
