### ISSUE TITLE
[QUESTION]:DO CSM/CSI support rke2 ?

### ISSUE THREAD

**Issue by liuj23CD** [dell/csm#1509]
### How can the Team help you today?

**Details: ?**
DO CSM/CSI support rke2 ?

**Comment by atye** [comment]
Hi @liuj23CD. We have not specifically qualified RKE2. You may reference https://dell.github.io/csm-docs/docs/support/cert-csi/#run-all-test-suites to perform a community qualification and submit the results here:

https://github.com/dell/csm/issues/new?assignees=&labels=type%2Fqualification&projects=&template=community_qualification.yml&title=%5BQualification%5D%3A+

**Comment by atye** [comment]
@liuj23CD, I will close this issue. If you have further questions about RKE2 support, feel free to re-open this. If you have issues executing the cert-csi qualification, please open a new issue.
