### ISSUE TITLE
[QUESTION]: Powerstore K8S CSI volume resize without pod restart

### ISSUE THREAD

**Issue by denis256** [dell/csm#155]
### CSI volume resize without pod restart

Hello, I was wondering if Powerstore CSI can expand volume filesystem without pod restart?

In the official K8S documentation for "Online File System Expansion" is mentioned only `GCE-PD, AWS-EBS, Cinder, and Ceph RBD` also didn't find any meaningful explanation by searching `csi-powerstore` source code

References:

https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/#online-file-system-expansion

**Comment by walker2** [comment]
Hello, 

PowerStore driver supports the online expansion of the volumes, which is advertised in plugin capabilities gRPC call [here](https://github.com/dell/csi-powerstore/blob/2b6d0e23ab2e75ae524a6f32b0d42813bd027821/pkg/identity/identity.go#L69)

Here is a little snippet from CSI spec about online expansion
```
ONLINE indicates that volumes may be expanded when published to a node. 
...
When a plugin supports ONLINE volume expansion and also has the EXPAND_VOLUME controller capability
then the plugin MUST support expansion of volumes currently published and available on a node. 
```

The official k8s blog article you linked is from 2018 and mentions only in-tree plugins that were present at that time. 

If you're interested in specific code here is a [link](https://github.com/dell/csi-powerstore/blob/6921a5737c1b52bd538d495d9f21e28bd5cca4a1/pkg/node/node.go#L673) that points to `NodeExpandVolume` call that performs expansion of the filesystem
