### ISSUE TITLE
[QUESTION]:Dell PowerFlex CSI to Support Windows Server Failover Clustering on OpenShift Virtulization

### ISSUE THREAD

**Issue by kumbalakandy** [dell/csm#1556]
Hello Team,
We are planning to run an OpenShift Cluster on Dell PowerFlex for OpenShift Virtualization use case. Does Dell CSM Support required storage configuration for Windows Server Failover  Cluster to Setup an SQL Cluster? 

![image](https://github.com/user-attachments/assets/2f1048c5-4699-4532-a9aa-0d4125a9038f)

**Comment by kumbalakandy** [comment]
@atye @nitesh3108,

Any help is really appreciated.

**Comment by sakshi-garg1** [comment]
Powerflex supports ScaleIO protocol.

**Comment by kumbalakandy** [comment]
Hello @sakshi-garg1 ,

Does it mean the SCSI-3 Persistent Reservation is supported when I use the PowerFlex CSI for OpenShift Virtualization?

**Comment by sakshi-garg1** [comment]
No, SCSI-3 is not supported by Powerflex.
ScaleIO protocol is a proprietary block storage and metadata protocol over TCP/IP. It is NOT iSCSI due to ScaleIO’s distributed nature.

**Comment by AronAtDell** [comment]
@sakshi-garg1 , @kumbalakandy - Please let us know if the question has been answered. If yes, please close. Thanks!

**Comment by kumbalakandy** [comment]
Hello @sakshi-garg1 @AronAtDell ,
Still I am looking for a solution to deploy Windows Server Failover Clustering on OpenShift Virtualization and PowerFlex.

The answer from @sakshi-garg1 looks like it is not possible. Please correct me if I am wrong.

**Comment by sakshi-garg1** [comment]
Hi @kumbalakandy, your requirement for Windows Server Failover Clustering requires a LUN disk with a SCSI connection whereas PowerFlex does not support SCSI. It supports only ScaleIO protocol. With this it seems not possible with PowerFlex.

**Comment by kumbalakandy** [comment]
Thanks @sakshi-garg1 
Please close the thread.
