### ISSUE TITLE
[QUESTION]:unity storage version

### ISSUE THREAD

**Issue by ChinYiLiao** [dell/csm#157]
### How can the Team help you today?

**Details: ? before upgrade openshift verion, we want to check the version is suitable for it.
Current unity OE new version is 5.1.2, but in github information it only for 5.1.0. 
Could unity OE 5.1.2 support the CSI v1.5 and Openshift 4.9?  
thanks a lot~

**Comment by karthikk92** [comment]
Deployment of the csi driver is done using operator or just helm ? So far with the latest operator and driver release(csi operator 1.6 and driver 2.1.0), we have qualified 5.1.0 Unity storage and we are not yet to qualified 5.1.2 unity OE version. So i would recommend to use 5.1.0 unity version as of now.

**Comment by ChinYiLiao** [comment]
Due to apache log4J, unity 5.1.2 version is fix it. When the unity OE 5.1.2 will be certified?

**Comment by ChinYiLiao** [comment]
We have two containar enviroments.
checked the environment, our two unity storages OE are upgraded to 5.1.2.0.5.007 to fixed the log4J security issue.
One is openshift  4.6.42 + CSI v1.5.0, and another is  openshift  4.8.20 + CSI v1.6.0.
But I couldn't find the support martix form unity github.
Will it cause the issues or problem?

**Comment by bandak2** [comment]
Hi @ChinYiLiao, while we are checking on the qualification front for the latest OE 5.1.2.0.5.007, Can you please confirm your reference to CSI v1.5.0 and CSI v1.6.0 is for **dell-csi-operator**, or is it a reference to the **csi-unity** driver versions?

**Comment by rajendraindukuri** [comment]
Hi @ChinYiLiao we qualified our upcoming release 2.2 with Unity OE 5.1.2.  Closing this issue for now. Please feel free to reopen if needed. Thanks.
