### ISSUE TITLE
[QUESTION]: Should the CSM Operator sample files include Observability related lines for PowerStore?

### ISSUE THREAD

**Issue by gashof** [dell/csm#1573]
According to the docs CSM Observability is supported with PowerStore:
![image](https://github.com/user-attachments/assets/01538e55-d16c-4585-b8e1-2153aa48f3d0)

When I go to the CSM Operator installation instructions for Observability:
https://dell.github.io/csm-docs/docs/deployment/csmoperator/modules/observability/#prerequisites

It sends the user to github samples:
•	Enable Observability module and components in [sample manifests](https://github.com/dell/csm-operator/tree/main/samples). If cert-manager has already been installed, don’t enable it.

I went to the 1.7.0 files(same for older) on GitHub, but none of the PowerStore sample files have any reference to Observability.
https://github.com/dell/csm-operator/tree/v1.7.0/samples

**Comment by gashof** [comment]
It looks like it is missing from the minimal instructions too: 
How to enable this module using minimal CR 
Alternatively, you can use the minimal sample files provided [here](https://github.com/dell/csm-operator/tree/main/samples/minimal-samples).

**Comment by adarsh-dell** [comment]
CSI-PowerStore supports only the Resiliency module through the CSM-operator. I hope this clarifies your query.

Thanks, Adarsh

**Comment by gashof** [comment]
Thanks Adarsh!  I see that now.
