### ISSUE TITLE
[QUESTION]:How to reclamate the volume in PersistentVolume on OpenShift

### ISSUE THREAD

**Issue by yumatsui07** [dell/csm#1592]
### How can the Team help you today?

**Details: ?**

We use Dell CSI Driver (https://github.com/dell/csi-powerstore/tree/v2.10.1/dell-csi-helm-installer) on OpenShift 4.14.
We deploy Pods which require PersistentVolume in this environment, there are some containers in which  space reclamation does not run.

Is there a CSI Driver solution that runs space reclamation on any PersistentVolumeClaim on OpenShift?

Now we execute `fstrim` command to the mounted volume in such containers as a workaround, but we cannot execute it in some containers.

Kind regards.

**Comment by atye** [comment]
Hi @yumatsui07. The CSI Driver does not execute any space reclamation. After a brief investigation, it seems that this could be done with the [csi-addon specification](https://github.com/csi-addons/spec/).

If you would like this to be at least investigated as a feature for Dell CSM, please open a feature request at https://github.com/dell/csm/issues/new?assignees=&labels=type%2Ffeature-request%2C+needs-triage&projects=&template=feature_request.md&title=%5BFEATURE%5D%3A.

Regarding why `fstrim` cannot be executed in some containers, can you share more details about it? Is there an error? Can you share what version of the Powerstore array you have and what protocol you are using for volumes?

**Comment by yumatsui07** [comment]
@atye 
Thank you for your answering. I understood that we cannot execute space reclamation without introducing any other component.

> Regarding why `fstrim` cannot be executed in some containers, can you share more details about it? Is there an error?

There might be no technical problem. I guess it's just that some container don't have the `fstrim` command or don't permit executing the command by the SecurityContext.

Our Environment
```
Dell EMC PowerStore
Version: 3.2.0.0 (Release, Build 1828615, 2022-10-11 09:47:46, Retail)
```

We define the storageclasses using `ext4` and `xfs` as filesystems, and use them to creating PVCs.

**Comment by atye** [comment]
Since `fstrim` would be executed on the application side anyway, I wouldn't think there is a CSI Driver issue. If you would like a space reclamation feature to be investigated for Dell CSM, you can use the link I provided earlier to open a feature request. Is there anything else we can help with on this issue before we close it?

**Comment by yumatsui07** [comment]
Thank you for your answering @atye . We'll try using [csi-addon specification](https://github.com/csi-addons/spec/) first.
There's no more issue, so I close this issue.
