### ISSUE TITLE
[BUG]: Documentation for iSCSI and FC multipathing for PowerStore

### ISSUE THREAD

**Issue by dancohen21** [dell/csm#1595]
### Bug Description

Linux Multipathing Requirements seem inadequate for Dell PowerStore.
https://dell.github.io/csm-docs/docs/deployment/csmoperator/drivers/powerstore/#linux-multipathing-requirements

The MPIO configuration documented on page 202 of the Dell Linux Host connectivity guide suggests the following multipath.conf file.  (https://elabnavigator.dell.com/vault/pdf/Linux.pdf)

defaults {
 polling_interval 5
 checker_timeout 15
 disable_changed_wwids yes
 find_multipaths no
}
devices {
 device {
 vendor DellEMC
 product PowerStore
 detect_prio "yes"
 path_selector "queue-length 0"
 path_grouping_policy "group_by_prio"
 path_checker tur
 failback immediate
 fast_io_fail_tmo 5
 no_path_retry 3
 rr_min_io_rq 1
 max_sectors_kb 1024
 dev_loss_tmo 10
 hardware_handler "1 alua"
 }
 device {
 vendor .*
 product dellemc-powerstore
 uid_attribute ID_WWN
 prio ana
 failback immediate
 path_grouping_policy "group_by_prio"
 path_checker "none"
 path_selector "queue-length 0"
 detect_prio "yes"
 fast_io_fail_tmo 5
 no_path_retry 3
 rr_min_io_rq 1
 max_sectors_kb 1024
 dev_loss_tmo 10
 }
}

this is also supported by support article number: 000220440

### Logs

N/A

### Steps to Reproduce

installation pre-reqs

### Expected Behavior

documentation consistency, and evaluating the proper configuration for Red Hat OpenShift environments with FC/iSCSI connectivity to Dell PowerStore systems.

### CSM Driver(s)

1.11, 1.12

### Installation Type

csm-operator 1.6.1

### Container Orchestrator

RHOCP 4.16

### Operating System

OpenShift Linux - RHCOS based on RHEL 9.4

**Comment by suryagupta4** [comment]
Hi @dancohen21,
Thank you for your feedback. The documentation at https://dell.github.io/csm-docs/docs/deployment/csmoperator/drivers/powerstore/#linux-multipathing-requirements provides a basic configuration with minimal required fields for multipathing required by the driver to be working in order to ensure we don't overload the documentation and keep it minimal. The same section `linux-multipathing-requirements` references to the Dell Host Connectivity Guide for additional settings to be set as per the requirement if at all it is required to be set by the end user.

**Comment by dancohen21** [comment]
the section in the CSM documentation where it talks about configuring the multipath.conf file
under: https://dell.github.io/csm-docs/docs/deployment/csmoperator/drivers/powerstore/#linux-multipathing-requirements

defaults {
  user_friendly_names yes
  find_multipaths yes
}
  blacklist {
}

and where it wraps it in a machineconfig to apply...

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: workers-multipath-conf-default
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,ZGVmYXVsdHMgewp1c2VyX2ZyaWVuZGx5X25hbWVzIHllcwpmaW5kX211bHRpcGF0aHMgeWVzCn0KCmJsYWNrbGlzdCB7Cn0K
          verification: {}
        filesystem: root
        mode: 400
        path: /etc/multipath.conf

This is not the best configuration.  a more appropriate multipath.conf file is specified in the Host connectivity guide  on page 202.  This is what should be documented and encoded for the machineconfig for powerstore.  It seems best to have tighter alignment between the PowerStore Linux best practices documented in the host connectivity guide and the CSM documenation if it is deemed applicable.
