### ISSUE TITLE
[QUESTION]: Deploying CSM behind a Proxy

### ISSUE THREAD

**Issue by Mahons** [dell/csm#1602]
We are trying to deploy the CSM Operator on a new OpenShift cluster (4.16). Unfortunately, we're behind a proxy which is quite restrictive. We've whitelisted the documented registries:

- registry.k8s.io
- registry.connect.redhat.com

However, we're running in to continuous issues with additional undocumented registries, such as:

- europe-west-docker.pkg.dev 
- production.cloudflare.docker.com

I'm wondering if there is a complete list of URLs for whitelisting?

**Comment by atye** [comment]
Hi @Mahons. Which images is the CSM Operator attempting to pull from europe-west-docker.pkg.dev or production.cloudflare.docker.com? The CSM Operator has no references to those registries unless you prepared the offline bundle with them.

Could your proxy or proxies further down the chain be modifying the registry?
Are you seeing these issues with installing the Operator or with installing one of the CSMs (powerflex, or powermax, etc)? If you are seeing an issue with the CSM, could you paste the sample file you used to install it?

**Comment by Mahons** [comment]
Hi @atye, I've asked my colleague to revert on the above, as he's at the coalface. 

In relation to our proxy, no, it definitely wouldn't be modifying the registry.

**Comment by shanmydell** [comment]
@Mahons : Please reopen the question with the requested details
