### ISSUE TITLE
[QUESTION]: Disable Snapshot Sidecar

### ISSUE THREAD

**Issue by OA72280** [dell/csm#1607]
Need to disable the snapshot sidecar for PowerFlex CSI drivers CSM Operator 1.3.0 and Up

Customer needs to not allow end users to ignite PowerFlex snapshots

**Comment by adarsh-dell** [comment]
Hi @OA72280 , Was there any issue observed during the process?

@WilsonRadadia20 @jooseppi-luna Any recommendation on this one?

**Comment by jooseppi-luna** [comment]
This was addressed as part of an internal ticket -- we can close this out
