### ISSUE TITLE
[BUG]: UI is broken for Operator documentation page in the instructions 

### ISSUE THREAD

**Issue by shanmydell** [dell/csm#1615]
### Bug Description

![image](https://github.com/user-attachments/assets/3d2006c8-f404-4048-a14f-be8e75ce0235)

### Logs

https://dell.github.io/csm-docs/docs/deployment/csmoperator/#openshift-installation-via-operator-hub

### Steps to Reproduce

https://dell.github.io/csm-docs/docs/deployment/csmoperator/#openshift-installation-via-operator-hub

### Expected Behavior

UI should be rendered properly 

### CSM Driver(s)

NA

### Container Orchestrator

NA

### Operating System

NA

**Comment by anandrajak1** [comment]
This section needs to removed from the operator
![image](https://github.com/user-attachments/assets/8d21df3b-a7ab-4562-83bb-e04b07cdaeee)

**Comment by chimanjain** [comment]
Removed the section from the csm-docs for csm 1.13.0 release.
