### ISSUE TITLE
[QUESTION]: Operand

### ISSUE THREAD

**Issue by OA72280** [dell/csm#1629]
Customer on OpenShift 4.14 Cluster running CSM 1.3 

When upgrading to CSM 1.5.1 the process fails. The customer attempted to remove the CSM operator 1.3 and all operands .... the Operator Successfully deleted out but the CRD for dell csm remained. 

Customer removed the CRD file and attempted to install the 1.5.1 Operator without success. Appears that its not fetching the CRD file 

This is using the Red Hat operator hub and customer is mirroring the Red Hat catalog.

Any known issues where when installing the operator via operator hub the associated CRD files aren't pulling?

**Comment by atye** [comment]
@OA72280 I don't think we've seen any known issues like that. They would be listed in https://dell.github.io/csm-docs/docs/deployment/csmoperator/troubleshooting/.

Could you share more details about the issue? What are the errors?

**Comment by shanmydell** [comment]
@OA72280 : Please reopen the ticket with requested details
