### ISSUE TITLE
[BUG]: Consistency of VolumePrefix, skipcertificatevalidation and other modifiable values in CSI drivers

### ISSUE THREAD

**Issue by rishabhatdell** [dell/csm#1647]
### Bug Description

There are default values for modifiable parameters 

For example default value of volume prefix are "csi-", "k8s", csivol for different drivers 

for skipcertificatevalidation is set to false for PowerMax 

 

All adjustable parameters should have the same value consistently across the drivers.

### Logs

NaN

### Steps to Reproduce

NaN

### Expected Behavior

NaN

### CSM Driver(s)

All CSI Drivers

### Container Orchestrator

NaN

### Operating System

NaN

**Comment by rishabhatdell** [comment]
link: 30848

**Comment by adarsh-dell** [comment]
Hi @rishabhatdell,

I believe similar changes might be needed for the CSM Installation wizard as well, correct? If so, could we also include the labels for the installation wizard and ensure that these changes are incorporated into this component as part of the fix?

Thanks!
