### ISSUE TITLE
[FEATURE]: CSM Resiliency enhancement to consider pod affinity

### ISSUE THREAD

**Issue by hoppea2** [dell/csm#165]
**Describe the solution you'd like**
CSM Resiliency should take pod affinity into account when identifying pods to be removed from an affected node

**Describe alternatives you've considered**
Currently pod affinity is ignored when pods are removed

**Additional context**
This does not resolve the overall scheduler imbalance issue in k8s but may assist in mitigation

**Comment by alikdell** [comment]
Functionality will be available CSM for Resiliency release
