### ISSUE TITLE
[QUESTION]:Upgrade or fresh install?

### ISSUE THREAD

**Issue by melkor6682** [dell/csm#1653]
### How can the Team help you today?
Decide what is best method for updating drivers.

**Details:**

Current csi-unity driver: `v2.10`
Desired csi-unity driver: `v2.12`

Our environment is disconnected.  We used the offline installer method originally. 
`Should we uninstall and install? ` or `Upgrade?`

**Comment by rishabhatdell** [comment]
You can perform the upgrade using the instructions provided at this link: [Dell CSM Offline Upgrade Guide ](https://dell.github.io/csm-docs/docs/deployment/offline/upgrade/).
