### ISSUE TITLE
[QUESTION]: RootClientEnabled

### ISSUE THREAD

**Issue by MuralidharB** [dell/csm#166]
### How does RootClientEnabled flag work?

Is there a documentation on `RootClientEnabled`? Does this flag determine how an NFS Share is exported? Does `True` mean it allows all user ids retained including root and `False` mean all user ids including root user id is squashed?

**Comment by randeepsharma** [comment]
Hi,

Here a link which clients http://doc.isilon.com/onefs/9.3.0/help/en-us/ifs_t_create_an_nfs_export_gui.html
RootClientEnabled flag when set to false squashes user to nobody and when set to true user id is preserved.

Do let me know if any more info is needed.

Thanks
Randeep

**Comment by randeepsharma** [comment]
Closing this. Please feel free to connect again.
