### ISSUE TITLE
Power Max CSI - Images pointing to k8s repo despite changing repository to internal repo

### ISSUE THREAD

**Issue by gloriousbao** [dell/csm#173]
We are following steps for installation of dell powermax csi using operator in the offline mode.

We created the required tar and executed the step to push images to our internal registry.

When deploying the powermax deployment using the sample file provided, all deployments point to images referring to k8s.gcr.io, requesting guidance for the same

![image](https://user-images.githubusercontent.com/98939984/152298318-041ca5a5-bad5-4608-8c98-73df0b5d3f60.png)

**Comment by boyamurthy** [comment]
> We are following steps for installation of dell powermax csi using operator in the offline mode.
> 
> We created the required tar and executed the step to push images to our internal registry.
> 
> When deploying the powermax deployment using the sample file provided, all deployments point to images referring to k8s.gcr.io, requesting guidance for the same
> 
> ![image](https://user-images.githubusercontent.com/98939984/152298318-041ca5a5-bad5-4608-8c98-73df0b5d3f60.png)

hi @gloriousbao  , thanks for reaching out Dell powermax , Hope you have followed the offline installation steps given @https://dell.github.io/csm-docs/docs/csidriver/installation/offline/ .

Could you share the logs for generating offline bundle tar file using the internal repo.  

Thanks,
Murthy

**Comment by gloriousbao** [comment]
Hello, I have re-downloaded the latest package, I will share the logs in some time once I reach the step

**Comment by gloriousbao** [comment]
Attached logs for reference 
[csi.txt](https://github.com/dell/csm/files/8013121/csi.txt)

**Comment by gloriousbao** [comment]
When we apply powermax sample file, it still ends up pointing to k8s images.. 

![image](https://user-images.githubusercontent.com/98939984/152743194-81188174-4f51-4eaf-a3ca-b79abdb3b8f4.png)

**Comment by shanmydell** [comment]
@boyamurthy

**Comment by boyamurthy** [comment]
> 

hi @gloriousbao  , Could you please write detailed steps which you have followed for the offline installation using the operator which will help us in finding the root cause . 

Thanks,
Murthy

**Comment by shanmydell** [comment]
@gloriousbao : Please feel free to reopen the ticket when the requested details are available. Closing the ticket due to inactivity
