### ISSUE TITLE
[FEATURE]: Support for latest Powerstore array

### ISSUE THREAD

**Issue by harishp8889** [dell/csm#176]
**Describe the solution you'd like**
Add support to CSI Powerstore for latest powerstore array

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by prablr79** [comment]
@hoppea2 this feature will be targeted for Next Qtr.

**Comment by shanmydell** [comment]
@harishp8889 : Please raise the respective doc PR

**Comment by Prabhu-Dell** [comment]
Latest API changes implemented and Document updated.
