### ISSUE TITLE
[FEATURE]: Update Sidecar versions for CSI drivers 

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#182]
Update latest sidecar versions for CSI drivers .
external-provisioner :  k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
external-attacher    : k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
external-resizer     : k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
external-snapshotter : k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
node-driver-registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0

**Comment by shanmydell** [comment]
All drivers has updated their sidecar versions, closing the issue
