### ISSUE TITLE
[FEATURE]:Update latest UBIM image for CSI drivers

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#183]
Update latest UBIM image for CSI drivers . 

8.5-230
sha256:3aa3f379a81013bd3264faa0af87d201cdaa5981050d78c567b48fdfd5b38bb8

**Comment by bharathsreekanth** [comment]
Hi @shanmydell - Yes, PowerFlex has been updated to point to the -230 UBI image. This can be closed.
