### ISSUE TITLE
[FEATURE]: Update deprecated StorageClass parameter `fsType` with `csi.storage.k8s.io/fstype`

### ISSUE THREAD

**Issue by coulof** [dell/csm#188]
**Describe the solution you'd like**
As per the [provisioner container](https://github.com/kubernetes-csi/external-provisioner/blob/master/vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go#L71) logs the `fsType` parameter is now deprecated in favor of `csi.storage.k8s.io/fstype`.

Please update the driver storageClass samples to use the new parameter name.

**Comment by randeepsharma** [comment]
We should be using a release activies 1.3 github issue for this change.

**Comment by randeepsharma** [comment]
This is not applicable to csi-powerscale , hence removing the label for csi-powerscale.

**Comment by coulof** [comment]
@randeepsharma are you sure this is not applicable ? 

We had an issue at a customer site because the fsType was set to `ext4` by default instead of explicit `nfs`.

@nitesh3108, any opinion on that?

**Comment by randeepsharma** [comment]
> @randeepsharma are you sure this is not applicable ?
> 
> We had an issue at a customer site because the fsType was set to `ext4` by default instead of explicit `nfs`.
> 
> @nitesh3108, any opinion on that?

Based on discussion, will take this up and add the section in samples
