### ISSUE TITLE
[BUG]: Scaled down pod and got files from a different volume - Intermittent

### ISSUE THREAD

**Issue by francis-nijay** [dell/csm#198]
### Bug Description

Volumes get swapped or mounted to incorrect pods when pods are scaled down and scaled back up. Happens on multi appliance arrays and is intermittent. Issue is common to both FC and iSCSI.

### Logs

NA

### Steps to Reproduce

1. Create multiple STS
2. Make sure volumes are distributed across appliances and have the same LUN
3. Scale down the pods and scale them back up

### Expected Behavior

All pods are supposed to be scaled up with the same volume

### CSM Driver(s)

CSI Driver for Powerstore v2.1

### Installation Type

Helm

### Container Orchestrator

kubernetes 1.22

### Operating System

Ubuntu 20.04

**Comment by Prabhu-Dell** [comment]
Issue fixed.
