### ISSUE TITLE
[BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume

### ISSUE THREAD

**Issue by josejvillanueva** [dell/csm#200]
### Bug Description

So the pod spins up, requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume 

>> This occurs after some time, reportedly in 1-2 months. Just hangs when trying to mount/unmount according to splunk logs.

### Logs

[csaa_-_dell_storage_stuck_logs.csv](https://github.com/dell/csm/files/8112529/csaa_-_dell_storage_stuck_logs.csv)

### Additional Environment Information

$ oc describe csiisilon/csaa-isilon -n csaa-app-storage
Name: csaa-isilon
Namespace: csaa-app-storage
Labels: <none>
Annotations: storage.dell.com/CSIDriverConfigVersion: v4
storage.dell.com/attacher.Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-attacher:v3.0.0
storage.dell.com/attacher.Image.IsDefault: true
storage.dell.com/provisioner.Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-provisioner:v2.0.2
storage.dell.com/provisioner.Image.IsDefault: true
storage.dell.com/registrar.Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-node-driver-registrar:v2.0.1
storage.dell.com/registrar.Image.IsDefault: true
storage.dell.com/resizer.Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-resizer:v1.0.0
storage.dell.com/resizer.Image.IsDefault: true
storage.dell.com/snapshotter.Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-snapshotter:v3.0.2
storage.dell.com/snapshotter.Image.IsDefault: true
API Version: storage.dell.com/v1
Kind: CSIIsilon
Metadata:
Creation Timestamp: 2021-08-30T22:37:06Z
Generation: 3
Resource Version: 678791150
UID: b4f4aed1-1829-4ea1-af17-0edbb92ccb05
Spec:
Driver:
Common:
Envs:
Name: X_CSI_ISI_ENDPOINT
Value: p01dfn2000-mgmt.ent.rt.csaa.com
Name: X_CSI_ISI_PORT
Value: 8080
Name: X_CSI_ISI_PATH
Value: /ifs/Prod/p01dfn2000/nfs/apps/ocpd1/ocp-apps
Name: X_CSI_ISILON_NO_PROBE_ON_START
Value: false
Name: X_CSI_ISI_AUTOPROBE
Value: true
Name: X_CSI_ISI_INSECURE
Value: true
Name: X_CSI_CUSTOM_TOPOLOGY_ENABLED
Value: false
Name: X_CSI_DEBUG
Value: false
Image: prodnexus.ent.rt.csaa.com:10000/dellemc/csi-isilon:v1.4.0.000R
Image Pull Policy: IfNotPresent
Config Version: v4
Controller:
Envs:
Name: X_CSI_ISI_QUOTA_ENABLED
Value: true
Name: X_CSI_ISI_ACCESS_ZONE
Value: Prod
Node:
Envs:
Name: X_CSI_ISILON_NFS_V3
Value: true
Replicas: 1
Side Cars:
Args:
--volume-name-prefix=csipscale
Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-provisioner:v2.0.2
Image Pull Policy: IfNotPresent
Name: provisioner
Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-attacher:v3.0.0
Image Pull Policy: IfNotPresent
Name: attacher
Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-snapshotter:v3.0.2
Image Pull Policy: IfNotPresent
Name: snapshotter
Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-node-driver-registrar:v2.0.1
Image Pull Policy: IfNotPresent
Name: registrar
Image: prodnexus.ent.rt.csaa.com:10000/containerplatform/csi-resizer:v1.0.0
Image Pull Policy: IfNotPresent
Name: resizer
Snapshot Class:
Name: volumesnapshotclass
Parameters:
Isi Path: /ifs/Prod/p01dfn2000/nfs/apps/ocpd1/ocp-apps
Storage Class:
Allow Volume Expansion: true
Allowed Topologies:
Match Label Expressions:
Key: csi-isilon.dellemc.com/1.1.1.1
Values:
csi-isilon.dellemc.com
Name: nfs
Parameters:
Access Zone: Prod
Az Service IP: p01dfn2000-nfs.ent.rt.csaa.com
Isi Path: /ifs/Prod/p01dfn2000/nfs/apps/ocpd1/ocp-apps
Root Client Enabled: false
Reclaim Policy: Delete
Volume Binding Mode: Immediate
Status:
Controller Status:
Available:
isilon-controller-64d64bcc5b-4xj79
Driver Hash: 2130169020
Last Update:
Condition: Running
Time: 2021-10-13T00:09:04Z
Node Status:
Available:
isilon-node-lv6sx
isilon-node-rbfjb
isilon-node-8pbvw
isilon-node-pn9gn
isilon-node-drph5
isilon-node-7wp9t
isilon-node-wpqx7
isilon-node-slvpb
isilon-node-h7h64
isilon-node-kjkm6
isilon-node-lpk4w
isilon-node-r4hxm
isilon-node-ck7g4
isilon-node-n82dj
isilon-node-j4gdk
isilon-node-7w7vd
isilon-node-h749j
isilon-node-gztfp
isilon-node-7mjcf
isilon-node-24f4w
isilon-node-mrxpq
isilon-node-hlxz4
isilon-node-x7lg9
isilon-node-9td7z
isilon-node-lqxwc
isilon-node-dmzrh
isilon-node-kwmkg
isilon-node-727k2
isilon-node-kggz8
isilon-node-84f6p
isilon-node-bgj2l
isilon-node-bbx5g
isilon-node-qjmkb
isilon-node-vsf22
isilon-node-58jhb
isilon-node-29n8p
isilon-node-nggc2
isilon-node-fpdjq
isilon-node-xx6dn
isilon-node-vz7jx
isilon-node-4l9fr
State: Running
Events: <none>

### Steps to Reproduce

This occurs after some time, reportedly in 1-2 months. Just hangs when trying to mount/unmount according to splunk logs.

>> Resolved by rebooting their VMs. However, cannot leave the VM's in the unusable state, so hard to repro or troubleshoot when it occurs.

### Expected Behavior

Setup where the end users are Kubernetes pods that utilize Dell Contain Storage Interface (CSI) to mount 4 VM's to the Isilon exports. This set up constantly creates new exports and removes them, as well as modifies client accessibility. This occurs repeatedly as end users create builds throughout the workflow.

### CSM Driver(s)

Dell Operator Version: dell-csi-operator:v1.2.0.000R
Controller Version: csi-isilon:v1.4.0.000R
Driver Version: csi-isilon:v1.4.0.000R

### Installation Type

dell-csi-operator:v1.2.0.000R

### Container Orchestrator

Kubernetes

### Operating System

Linux

**Comment by prablr79** [comment]
@nitesh3108 @randeepsharma can you look into this issue ?

**Comment by randeepsharma** [comment]
@josejvillanueva could you pls share the controller and node logs, that will help us triage this. Will the current info shared, it is unlikely to root cause this.

**Comment by josejvillanueva** [comment]
do you have access to the following node logs: https://lpxlvaprd.isus.emc.com/logviewer/CALIFORNIA_STATE_AUTOMOBILE_ASSOCIATION/2022-02-24-001/
otherwise, I will work to get them uploaded here

**Comment by josejvillanueva** [comment]
Hello,

I have uploaded the logs as requested. Please let me know if you need anything else.

Thank you,

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>

**Comment by josejvillanueva** [comment]
++Brian Mulligan
++Prasanna Muthukumarasamy

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>



Internal Use - Confidential
From: Villanueva, Jose J
Sent: Tuesday, March 8, 2022 4:52 PM
To: dell/csm; dell/csm
Cc: Mention
Subject: RE: [dell/csm] [BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume (Issue #200)

Hello,

I have uploaded the logs as requested. Please let me know if you need anything else.

Thank you,

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>

**Comment by josejvillanueva** [comment]
Hi Randeep, Prasanna,

I am with Incident Management. Wanted to follow up on this case as focus is on how the CSI driver is communicating with the Isilon cluster.

Is there anything we can provide to assist in your investigation? Perhaps we could all jump on a call to discuss what our next steps should be here?

Please let us know how we can best move this case forward as we seem to be at an impasse here, last update was 14 days ago.

Greatly appreciated any assistance.

Thank you,
Brian Mulligan
Customer Success Incident Manager
Dell Technologies | Customer Success
mobile + 1 (508) 344-1663
***@***.******@***.***>





Internal Use - Confidential
From: Villanueva, Jose J ***@***.***>
Sent: Wednesday, March 9, 2022 12:41 PM
To: dell/csm; dell/csm
Cc: Mention; Mulligan, Brian; Muthukumarasamy, Prasanna
Subject: RE: [dell/csm] [BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume (Issue #200)

++Brian Mulligan
++Prasanna Muthukumarasamy

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>



Internal Use - Confidential
From: Villanueva, Jose J
Sent: Tuesday, March 8, 2022 4:52 PM
To: dell/csm; dell/csm
Cc: Mention
Subject: RE: [dell/csm] [BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume (Issue #200)

Hello,

I have uploaded the logs as requested. Please let me know if you need anything else.

Thank you,

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>

**Comment by nitesh3108** [comment]
@josejvillanueva sorry for the delay as we were busy in winding up on the code freeze activities. Am going through all the details provide here and update you ASAP.
Thanks for your patience !

**Comment by josejvillanueva** [comment]
Hi Team,

Following up on this case. Any updates from your investigation?

Thank you,
Brian Mulligan
Customer Success Incident Manager
Dell Technologies | Customer Success
mobile + 1 (508) 344-1663
***@***.******@***.***>





Internal Use - Confidential
From: Mulligan, Brian
Sent: Wednesday, March 9, 2022 12:48 PM
To: Villanueva, Jose J; dell/csm; dell/csm
Cc: Mention; Muthukumarasamy, Prasanna
Subject: RE: [dell/csm] [BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume (Issue #200)

Hi Randeep, Prasanna,

I am with Incident Management. Wanted to follow up on this case as focus is on how the CSI driver is communicating with the Isilon cluster.

Is there anything we can provide to assist in your investigation? Perhaps we could all jump on a call to discuss what our next steps should be here?

Please let us know how we can best move this case forward as we seem to be at an impasse here, last update was 14 days ago.

Greatly appreciated any assistance.

Thank you,
Brian Mulligan
Customer Success Incident Manager
Dell Technologies | Customer Success
mobile + 1 (508) 344-1663
***@***.******@***.***>





Internal Use - Confidential
From: Villanueva, Jose J ***@***.******@***.***>>
Sent: Wednesday, March 9, 2022 12:41 PM
To: dell/csm; dell/csm
Cc: Mention; Mulligan, Brian; Muthukumarasamy, Prasanna
Subject: RE: [dell/csm] [BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume (Issue #200)

++Brian Mulligan
++Prasanna Muthukumarasamy

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>



Internal Use - Confidential
From: Villanueva, Jose J
Sent: Tuesday, March 8, 2022 4:52 PM
To: dell/csm; dell/csm
Cc: Mention
Subject: RE: [dell/csm] [BUG]: requests 3 volumes, only 2 mount requests are sent to the actual Isilon which are fulfilled, but the 3rd call is never sent or hangs when trying to mount 3rd volume (Issue #200)

Hello,

I have uploaded the logs as requested. Please let me know if you need anything else.

Thank you,

Jose Villanueva
Technical Support Engineer 2 | Isilon
Dell Technologies | ISG Support Services
Office +1-800-782-4362 ext 6281959
email: ***@***.******@***.***>
San Dimas, California, USA (GMT-8)

My work schedule is 8:00am - 5:00pm PST, Sunday-Thursday
Need assistance outside of my working hours?
800-SVC-4-EMC, and request to speak to a Isilon Duty Manager.

My manager is ***@***.******@***.***>

**Comment by nitesh3108** [comment]
@josejvillanueva I tried reproducing the same at our end but every time its success, able to mount 3 different volumes on one node. Also, able to see 3 different mount calls triggered in Driver logs.

**Comment by randeepsharma** [comment]
Also please share the attacher and provisioner logs so that we can check if the number of requests are the same.

**Comment by prablr79** [comment]
@josejvillanueva can you use this tool to collect the logs https://github.com/dell/csm-logcollector

**Comment by prablr79** [comment]
@josejvillanueva please do enable DEBUG flag in values.yaml

**Comment by josejvillanueva** [comment]
Customer is working on upgrading the CSI driver sw. Here is what I saw back from the customer. Could you please assist?

We’re trying to update to the latest image(s), it appears that at least one of the images are missing. Can you please let us know when the updated image plans to be released?

dellemc/csi-isilon:v2.2.0

ERROR
Received a non-zero return code (1) from the following comand:
/bin/docker pull dellemc/csi-isilon:v2.2.0

Output was:
Trying to pull repository registry.access.redhat.com/dellemc/csi-isilon ...
Trying to pull repository registry.redhat.io/dellemc/csi-isilon ...
Trying to pull repository docker.io/dellemc/csi-isilon ...
Trying to pull repository docker.io/dellemc/csi-isilon ...
manifest for docker.io/dellemc/csi-isilon:v2.2.0 not found

This info was also sent in email.

**Comment by randeepsharma** [comment]
The csi-isilon [v2.2.0](https://hub.docker.com/layers/csi-isilon/dellemc/csi-isilon/v2.2.0/images/sha256-f80684cb14874264f1e0890d6364b7197189d6c7a274a86180d1390317dcb657?context=explore) image is out there dellemc/csi-isilon Tags | Docker Hub .
Can you please do a docker pull and check it.

**Comment by josejvillanueva** [comment]
Hello, thank you for the link. Customer has installed it and has requested a meeting and I am wondering when if you are available to do so?

**Comment by josejvillanueva** [comment]
Hello, this issue happened again. It is like the CSI driver does not see the PVC anymore. Here are the logs that were gathered at the time of the issue as well as screenshots of the environment. Please let me know if you find anything. Error they are getting:
Events:

  Type     Reason       Age                   From     Message

  ----     ------       ----                  ----     -------

  Warning  FailedMount  77m (x40 over 12h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[ivyrepo npmcache], unattached volumes=[kube-api-access-tdzj9 mvnrepo ivyrepo npmcache repositories workspace-volume]: timed out waiting for the condition

  Warning  FailedMount  48m (x55 over 11h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[ivyrepo npmcache], unattached volumes=[ivyrepo npmcache repositories workspace-volume kube-api-access-tdzj9 mvnrepo]: timed out waiting for the condition

  Warning  FailedMount  36m (x57 over 12h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[npmcache ivyrepo], unattached volumes=[npmcache repositories workspace-volume kube-api-access-tdzj9 mvnrepo ivyrepo]: timed out waiting for the condition

  Warning  FailedMount  23m (x57 over 12h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[ivyrepo npmcache], unattached volumes=[mvnrepo ivyrepo npmcache repositories workspace-volume kube-api-access-tdzj9]: timed out waiting for the condition

  Warning  FailedMount  7m10s (x51 over 12h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[ivyrepo npmcache], unattached volumes=[workspace-volume kube-api-access-tdzj9 mvnrepo ivyrepo npmcache repositories]: timed out waiting for the condition

  Warning  FailedMount  2m39s (x59 over 12h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[ivyrepo npmcache], unattached volumes=[repositories workspace-volume kube-api-access-tdzj9 mvnrepo ivyrepo npmcache]: timed out waiting for the condition

Based on this warning it looks like the pod is failing to mount mvnrepo. Mvnrepo, ivyrepo and npmcache are the 3 pvcs that this pod requests, all 3 are storage volumes provided by the dell CSI
pod info:
![volume mounts](https://user-images.githubusercontent.com/100168558/1630
![pvc](https://user-images.githubusercontent.com/100168558/163047520-f3f28215-acdf-47d0-91f0-4341f7fede8a.png)
47516-f192c491-7b84-4015-88d6-629b8509aa8f.png)

log files: 
[archive_04_12_2022_14_13_48.zip](https://github.com/dell/csm/files/8476319/archive_04_12_2022_14_13_48.zip)

you can see Devops1 has been trying to create for 12hours
![issue 4_12](https://user-images.githubusercontent.com/100168558/163047650-ef2b22f2-3e7f-4cb4-9920-63dbd4fe3cbc.png)

debug set to true
![CSI debug](https://user-images.githubusercontent.com/100168558/163047800-c7fc3871-75fd-44a5-a0ce-7f7300572a0d.png)
.

**Comment by nitesh3108** [comment]
Before mounting these 3 volumes to the node, make sure that particular node doesn't have volumeattachment stale entries especially for these 3 volumes.

**Comment by randeepsharma** [comment]
This is being investigated in discussion with the customer.

**Comment by randeepsharma** [comment]
Is being worked on.

**Comment by nitesh3108** [comment]
This issue was found at RedHat end and customer is interacting with them directly.
