### ISSUE TITLE
[BUG]: VolumeHealthMonitor config variable is not consistent across drivers 

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#203]
### Bug Description

for health monitor support , few drivers are using variable name as "volumehealthmonitor" and few as "healthMonitor" .
it should be consistent across the drivers .

Also documentation should have same feature names . 

### Logs

healthMonitor:
--
  | # enabled: Enable/Disable health monitor of CSI volumes- volume status, volume condition
  | # Allowed values:
  | # true: enable checking of health condition of CSI volumes
  | # false: disable checking of health condition of CSI volumes
  | # Default value: None
  | enabled: false

volumeHealthMonitor:
--
  | # enabled: Enable/Disable health monitor of CSI volumes- volume state, volume condition
  | # Allowed values:
  | # true: enable checking of health condition of CSI volumes
  | # false: disable checking of health condition of CSI volumes
  | # Default value: None
  | enabled: false

### Steps to Reproduce

Variable names in values.yaml file

### Expected Behavior

variable names should be same . 

### CSM Driver(s)

.

### Container Orchestrator

K8/operator

### Operating System

all supported

**Comment by shanmydell** [comment]
@francis-nijay @randeepsharma Please make a note of this feature for v1.3.0

**Comment by bharathsreekanth** [comment]
This was delivered in CSM 1.5, closing it.
