### ISSUE TITLE
[BUG]: Doc bug; CSI Specification causes confusion for some users.

### ISSUE THREAD

**Issue by gashof** [dell/csm#210]
### Bug Description

Issue:
The "CSI Specification" under CSI Driver Capabilities under Features in the documentation support matrix causes confusion for some users. Details on the CSI Spec are pointed out at the top of the page, but I have seen many users confuse this with the version of the Driver.
https://dell.github.io/csm-docs/docs/csidriver/#csi-driver-capabilities

Part of this confusion is that this page does not show the driver version that Features and Capabilities are for.

Fix:
Note that the CSI Spec is not the driver version and put a link to the Kubernetes CSI spec in the csi-driver-capabilities as well.
Put what version of the drivers the documentations covers on the csi-driver-capabilities page.

### Logs

n/a

### Screenshots

Available if required

### Additional Environment Information

n/a

### Steps to Reproduce

n/a

### Expected Behavior

n/a

### CSM Driver(s)

All CSI Drivers

### Installation Type

All Installation Types

### Container Storage Modules Enabled

n/a

### Container Orchestrator

n/a

### Operating System

n/a

**Comment by gallacher** [comment]
Thanks for taking the time to report this issue @gashof!

**Comment by coulof** [comment]
My 2 cents, let's just scrap the CSI Specification row from : https://dell.github.io/csm-docs/docs/csidriver/#csi-driver-capabilities

The first line of that page gives already the version of the spec we support.

**Comment by shanmydell** [comment]
@gashof : Thanks for reporting the issue. As @coulof suggested we are removing the row. This row was introduced when PowerSclae upgraded the spec earlier to support 128 characters, now that all drivers are in same page it is no more needed. This change will be part of our upcoming release

**Comment by gashof** [comment]
Hi,
Anything on this point:
Put what version of the drivers the documentations covers on the csi-driver-capabilities page.

**Comment by shanmydell** [comment]
@gallacher  and @coulof : Please let me know your thoughts on @gashof request. Shall we add the version of driver in CSI driver index page , we already have it in CSM home page but not in driver page index

**Comment by gallacher** [comment]
The requested changes have been made and will be available as part of the CSM v1.2.0 release.
