### ISSUE TITLE
[BUG]: Volume Health Monitoring section is missing under driver install using Operator

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#212]
### Bug Description

Volume Health Monitoring section is missing under driver install using Operator. 

### Logs

doc portal

### Steps to Reproduce

refer the documentation .

### Expected Behavior

ex:

Health Monitoring
This feature is introduced in CSI Driver for PowerMax version 2.2.0.

Operator based installation
Volume Health Monitoring feature is optional and by default this feature is disabled for drivers when installed via operator.

To enable this feature, add the below block to the driver manifest before installing the driver. This ensures to install external health monitor sidecar. To get the volume health state value under controller should be set to true as seen below. To get the volume stats value under node should be set to true.

### CSM Driver(s)

.

### Container Orchestrator

k8/openshift 

### Operating System

all supported

**Comment by shanmydell** [comment]
@bharathsreekanth @francis-nijay @randeepsharma : If this is addressed please close the issue
