### ISSUE TITLE
[QUESTION]: Unity Helm Chart, FC, Ubuntu Nodes with Kubernetes

### ISSUE THREAD

**Issue by wrender** [dell/csm#213]
Hi, I'm trying to provision the Dell CSI Unity Helm chart for Kubernetes clusters to use FC Storage. We have 3 Ubuntu 20.0.4 Kubernetes Host Nodes, with FC connections through Cisco UCS Servers to the Unity SAN. I believe the 3 nodes are zoned in Unity to the vHBA on Cisco UCS servers.  If I do a "multipath -ll" on each server I see the:
200 GB OS multipath device (That we are booting the nodes from)
4TB multipath device (to be used for Kubernetes)

I install the CSI helm chart, and get the following error when the pods start up for the driver and the pods just continually restart:
_The node [myserver-001] is not added to any of the arrays_

**Comment by karthikk92** [comment]
@wrender  Could you please share the bellow details:
          1. Kubernetes version
          2. Csi unity driver version
          3. Unity storage version

Also could you please share the controller and node logs for the same by enabling log level to Debug in myvalues.yaml which helps to analyze the issue further.

Thanks,
Karthik K
