### ISSUE TITLE
[BUG]: Dell CSI Operator v1.6.0 blocking 4.9.x minor cluster upgrades

### ISSUE THREAD

**Issue by jb33441** [dell/csm#214]
### Bug Description

Attempting to update Openshift 4.9.19 to 4.9.22. The Dell CSI Operator is blocking the upgrade, claiming that it doesn’t support minor versions greater than 4.9.  The cluster minor version _is_ 9, with a patch revision of .19.  Appears to be a defect in the operator.

The operatorframework.io/properties annotation in the dell-csi-operator.v1.6.0 ClusterServiceVersion manifest contains a parameter olm.maxOpenShiftVersion set to “4.9”.  This is a semver and should probably be set to “4.9.*” because its current value will prevent installing _any_ patches on a 4.9 cluster.  This is probably not intended.

### Logs

ClusterServiceVersions blocking cluster upgrade: dell-csi-operator/dell-csi-operator.v.1.6.0 is incompatible with OpenShift minor versions greater than 4.9

### Screenshots

![image](https://user-images.githubusercontent.com/101151642/157139741-6b556ac6-cd22-42fc-9809-1773d4c2e50e.png)

### Steps to Reproduce

Attempt upgrade to Open Shift 4.9.22

### Expected Behavior

Upgrade to 4.9.22 should be allowed

### CSM Driver(s)

Dell CSI Operator v1.6.0

### Container Orchestrator

Open Shift 4.9.19

### Operating System

RHEL 7.6

**Comment by rensyct** [comment]
Hi @jb33441 
Operator cannot block the openshift upgrade. Could you please reach out to RedHat as there is an open issue for the same as per the below mentioned link 
https://access.redhat.com/solutions/6267791

**Comment by rensyct** [comment]
Hi @jb33441
Please help provide the customer name in the ticket. 
Did you reach out to RedHat. Please help provide an update.
