### ISSUE TITLE
[FEATURE]: fsGroups wtihout alpha gates for PowerFlex

### ISSUE THREAD

**Issue by OA72280** [dell/csm#215]
Large financial customer seeking the ability to leverage fsGroups against volumes created by the CSI from PowerFlex 

Currently customer is running stable version of OCP 4.6 on k8s 1.19 

Is there a way this can be accomplished without Alpha gates enabled?

Driver version used is 1.5 for v1.19

The deployment method is offline install 

Created New Project
Applied CRDs from git repo
Applied configmap of driverconfig aftet taring it up
Created Dell CSI Operator using Operator.yml
Created secret needed for Backend Config
Applied CSI CR with annotations pointing to internal repo

**Comment by JacobGros** [comment]
operator version is 1.5

**Comment by hoppea2** [comment]
Please reopen if this is an issue with latest version. Thanks!
