### ISSUE TITLE
[QUESTION]: Unity pods gets into CrashLoopBackOff event<pod starting, crashing, starting again, and then crashing again>

### ISSUE THREAD

**Issue by thecloudgarage** [dell/csm#217]
### How can the Team help you today?

**Details: ?**

I have followed the exact procedure to the tee yet the installation fails and the status below depicts what I am experiencing.  Also note that the Array ID, the IP address, username, password configured in the secret.yaml are all proper and have validated it.

The secrets.yaml is validated with successful installation with OpenShift.

Now I am trying the procedure with EKS Anywhere and to my knowledge there should not be a challenge. 

Can you confirm if there is NO issue with regards to Cilium CNI or some other CNI issue as EKS Anywhere uses Cilium as the CNI.

ubuntu@localhost:~/w01/csi-unity/dell-csi-helm-installer$ ./csi-uninstall.sh --namespace unity --values ./myvalues.yaml
Unknown option --values
For help, run ./csi-uninstall.sh -h
ubuntu@localhost:~/w01/csi-unity/dell-csi-helm-installer$ ./csi-install.sh --namespace unity --values ./myvalues.yaml
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
------------------------------------------------------
> Installing CSI Driver: csi-unity on 1.21
------------------------------------------------------
------------------------------------------------------
> Checking to see if CSI Driver is already installed
------------------------------------------------------
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
------------------------------------------------------
> Verifying Kubernetes and driver configuration
------------------------------------------------------
|- Kubernetes Version: 1.21
|
|- Driver: csi-unity
|
|- Verifying Kubernetes version
|
|--> Verifying minimum Kubernetes version Success
|
|--> Verifying maximum Kubernetes version Success
|
|- Verifying that required namespaces have been created Success
|
|- Verifying that required secrets have been created Success
|
|- Verifying that required secrets have been created Success
|
|- Verifying alpha snapshot resources
|
|--> Verifying that alpha snapshot CRDs are not installed Success
|
|- Verifying sshpass installation.. |
|- Verifying iSCSI installation
Enter the root password of 172.24.167.58:Enter the root password of 172.24.167.59:
Failed
|
|- Verifying snapshot support
|
|--> Verifying that snapshot CRDs are available Success
|
|--> Verifying that the snapshot controller is available Success
|
|- Verifying helm version Success
|
|- Verifying helm values version Success------------------------------------------------------
> Verification Complete - With Warnings
------------------------------------------------------
Warnings:
- iSCSI client is either not found on node: 172.24.167.58 or not able to verify
- iscsid service is either not running on node: 172.24.167.58 or not able to verify
- iSCSI client is either not found on node: 172.24.167.59 or not able to verify
- iscsid service is either not running on node: 172.24.167.59 or not able to verify
------------------------------------------------------
WARNING:
Kubernetes validation failed but installation can continue.
This may affect driver installation.Press 'y' to continue or any other key to exit: y
|
|- Installing Driver Success
|
|--> Waiting for Deployment unity-controller to be ready Success
|
|--> Waiting for DaemonSet unity-node to be ready Failed
------------------------------------------------------
WARNING:
Timed out waiting for the operation to complete.
This does not indicate a fatal error, pods may take a while to start.
Progress can be checked by running "kubectl get pods -n unity"Press 'y' to continue or any other key to exit: y
------------------------------------------------------
> Operation complete
------------------------------------------------------
ubuntu@localhost:~/w01/csi-unity/dell-csi-helm-installer$

ubuntu@localhost:~/w01/csi-unity/dell-csi-helm-installer$ kubectl get pods -n unity
NAME READY STATUS RESTARTS AGE
unity-controller-6c5c475854-68kx7 4/5 CrashLoopBackOff 5 5m56s
unity-controller-6c5c475854-h5zx5 5/5 Running 4 5m56s
unity-node-4vkm7 1/2 CrashLoopBackOff 5 5m56s
unity-node-tmwhb 1/2 Error 6 5m56s

**Comment by panigs7** [comment]
Hi @thecloudgarage ,

Could you please  set the logLevel to 'debug' (`logLevel: "debug"`) in myvalues.yaml and  share the node logs. You can get the node logs by using the command `kubectl logs <node_pod_name> -n unity -c driver`. This logs will help us to analyze what is causing the pods to crash.

Thanks!!

**Comment by shanmydell** [comment]
@thecloudgarage : Could you please provide the logs as requested above?

**Comment by rajendraindukuri** [comment]
@thecloudgarage Closing this for now. Feel free to reopen if needed. Thanks

**Comment by thecloudgarage** [comment]
Hi,

I am closing this issue with the overall summary and documentation presented in the attached text file below. The entire issue with all the possible details of installation logs with level set to DEBUG, configurations,  etc. has been provided in the attached text file. The text file is segregated in to 11 steps each of one which has the relevant information.

The issue was note in Unity CSI version 2.10. I can confirm that whatever fix has been applied, the issue seems to be resolved in v2.2.0. 

At the time of raising this issue, the official documentation indicated use of version 2.1.0 and the defect was observed in 2.1.0

[Unity-XT-CSI-2.1.0-Pod-CrashLoopBack.txt](https://github.com/dell/csm/files/8725367/Unity-XT-CSI-2.1.0-Pod-CrashLoopBack.txt)

Thanks for resolving this particular issue in 2.2.0 

cheers,

Ambar
