### ISSUE TITLE
[BUG]: Removing dirty bit flag from CSI PowerMax 2.2.0 image 

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#222]
### Bug Description

Removing dirty bit flag from CSI PowerMax 2.2.0 image 

### Logs

ARCH ?= x86_64
MAJOR ?= 2
MINOR ?= 2
PATCH ?= 0
BUILD ?= 000
NOTES ?=
TYPE ?= R
DIRTY ?= true
SHA7 ?= ca3802d

### Steps to Reproduce

build the image 

### Expected Behavior

dirty bit should be false 

### CSM Driver(s)

CSI PowerMax 2.2

### Container Orchestrator

k8/openshift 

### Operating System

all supported

**Comment by delldubey** [comment]
https://github.com/dell/csi-powermax/pull/67
Fixed.
