### ISSUE TITLE
[FEATURE]: Provide exhaustive configuration sample for Dell CSI Operator

### ISSUE THREAD

**Issue by coulof** [dell/csm#228]
**Describe the solution you'd like**
The CSI operator comes with some samples on how to configure it for different platform : https://github.com/dell/dell-csi-operator/tree/main/samples

For each driver, could you give a complete sample with all possible options.

For example, `sideCars:` is given for PowerFlex, Unity & PowerScale but not the other drivers, despite it actually works.

**Comment by bharathsreekanth** [comment]
Thanks @coulof. Dell CSI Operator is deprecated as of CY23 (CSM 1.9). Dell CSI Operator will be replaced by CSM operator, hence this feature will not be addressed.
