### ISSUE TITLE
[BUG]: Karavi metrics pod not able to send data to OTEL

### ISSUE THREAD

**Issue by encore0** [dell/csm#232]
### Bug Description

Installed observability module and configured both data sources in the grafana GUI. I can see in the logs that the data is being scraped, but it seems like there is an issue sending the data to otel. There are no firewalls in place. This is leading to no info being shown in Grafana. All drop downs are blank. Topology dashboard works fine

### Logs

see screenshot

### Screenshots

![Untitled](https://user-images.githubusercontent.com/48772670/159359481-2c3c5696-f4b8-43f2-bc0a-7714f1f7ce5c.jpg)

### Additional Environment Information

10.98.28.94 is otel

### Steps to Reproduce

install observability module based on doc

### Expected Behavior

data sent to otel/grafana

### CSM Driver(s)

CSI for Powerstore

### Container Orchestrator

Kubernetes  1.21.6

### Operating System

centos 7

**Comment by shaynafinocchiaro** [comment]
Hello @encore0, can you provide us with which deployment mechanism you used from the documentation, the version of otel and grafana you're using, and are you using the default values.yaml file we provide or your own?

**Comment by encore0** [comment]
Hi! I used helm for everything. I did not change any values in any of the values.yaml. Grafana 7.3, otel/opentelemetry-collector:0.9.0. This system is on the Dell network if you want to log into it.

**Comment by encore0** [comment]
Issue was related to not having a specific version of otel/nginx
