### ISSUE TITLE
[FEATURE]: Unity support for custom networks for NFS I/O traffic

### ISSUE THREAD

**Issue by jb33441** [dell/csm#234]
### How can the Team help you today?

Can csi-unity support custom networks for NFS I/O traffic ?

Seems that csi-powerscale already has this feature via allowedNetworks option but not available with csi-unity? Is this same capability for csi-unity on roadmap?

**Comment by karthikk92** [comment]
@jb33441  Currently we do not support custom networks for NFS . Also we do not have it on the roadmap for csi-unity yet . However we will add it in feature backlog and keep you posted on the same.

**Comment by coulof** [comment]
Reopening as a feature request so the customer can track it.
