### ISSUE TITLE
Unit test support for windows

### ISSUE THREAD

**Issue by delldubey** [dell/csm#235]
### Bug Description

While running unit test on a windows machine, the test complains about the following files in **gofsutil**:
C:\Users\go\pkg\mod\github.com\dell\gofsutil@v1.8.0\gofsutil_fs.go:174:13: **undefined: unix.Statfs_t**
C:\Users\go\pkg\mod\github.com\dell\gofsutil@v1.8.0\gofsutil_fs.go:175:9: **undefined: unix.Statfs**

### Logs

PS C:\Work\CSI\external\csi-powermax\service> go test
github.com/dell/gofsutil
C:\Users\Utkarsh_Dubey\go\pkg\mod\github.com\dell\gofsutil@v1.8.0\gofsutil_fs.go:174:13: undefined: unix.Statfs_t
C:\Users\Utkarsh_Dubey\go\pkg\mod\github.com\dell\gofsutil@v1.8.0\gofsutil_fs.go:175:9: undefined: unix.Statfs
FAIL    github.com/dell/csi-powermax/v2/service [build failed]
PS C:\Work\CSI\external\csi-powermax\service>

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/92086230/159424190-61d7a839-de08-4c2d-96f5-4ab0d2478943.png)

### Additional Environment Information

1. Windows 10
2. Go installed: go version go1.17.1 windows/amd64

### Steps to Reproduce

1. Clone https://github.com/dell/csi-powermax
2. cd to csi-powermax
3. Run _make unit-test_ or cd csi-powermax/service and run cmd _go test_

### Expected Behavior

Unit test should run clean on windows machine

### CSM Driver(s)

CSI Driver for Powermax 2.1

### Container Orchestrator

NA

### Operating System

Windows 10

**Comment by sharmilarama** [comment]
@tssushma why is this tagged a feature? This was opened as a bug.

**Comment by shanmydell** [comment]
As windows platform is not supported currently, it is set to feature

**Comment by AronAtDell** [comment]
@shanmydell , @delldubey if this is a request for Windows Support, let's change the description to reflect it as opposed to Unit tests. Thanks!

**Comment by Prabhu-Dell** [comment]
@delldubey Please provide more information on what this request is for? Is this for development or deployment purpose?

**Comment by AronAtDell** [comment]
@shanmydell , @delldubey @Prabhu-Dell , @sharmilarama  - This is not supported nor will it be in the current vision of the product offering. Closing with this comment.
