### ISSUE TITLE
[FEATURE]: CSM 1.3 Release Specific Changes

### ISSUE THREAD

**Issue by randeepsharma** [dell/csm#243]
The following CSM 1.3 release activities will be included as part of this feature:

Update the version of Dell CSI Drivers to v2.3 wherever necessary including driver image
Update the version of Dell CSI Operator v1.8.0
Update code owners files
Update 3rd party dependencies
Update Dell CSI driver standalone Helm charts to allow extended k8s versions
Update Dell CSI Operator to support new versions of OCP and K8s
Documentation updates
Add changelog file

**Comment by rsedlock1958** [comment]
I have reviewed this. Everything looks fine.
