### ISSUE TITLE
[BUG]:  ORANGE OAB VAL DE REUIL :Ext4 filesystem is consuming extra reserved space from the total available size

### ISSUE THREAD

**Issue by karthikk92** [dell/csm#245]
### Bug Description

ORANGE OAB VAL DE REUIL :Ext4 filesystem is consuming extra reserved space from the total available size

### Logs

We’ve notice two issues with CSI Driver :

The first one is an issue with RedHat "Migration Toolkit for Virtualization" application which is supposed to import virtual machines from a RedHat Virtualization cluster to an Openshift Virtualization environment.
When doing such an import using Filesystem volume mode, we cope with an issue regarding volume size.
You’ll find all details concerning this issue in the following RedHat Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=2059057 [[bugzilla.redhat.com](https://bugzilla.redhat.com/)] which is exactly what we’ve encountered.

We don't currently know if this issue is resulting from the application itself or from DELL CSI driver ext4 implementation.

The Second one is that, in some cases, we need use a single PV in more than one container at same time.
It's seem that, in this case, we need use the PV in ReadWriteMany access mode.
We’ve notice that your documentation tell that this access mode in currently not available according to our configuration.
So questions are :
Do you plan to put this kind of access mode in DELL CSI Driver (as Red Hat tells us it's just a matter of driver coding) ?
If Yes, is there an existing roadmap or a currently existing driver version with this feature implemented ?
Is there any applicable workaround for this case ?

As mentioned by phone, we’ll quickly create an helpdesk ticket for this.
, Additional Info: { Sales Order Number: 00000}

### Steps to Reproduce

create a pvc of 100GB size using ext4 file system and ISCSI protocol. We observed that only 98.3 GB of storage space could be used .

### Expected Behavior

This is an expected array behavior. Every time we create a volume with certain space , some percentage of it is reserved for file system.

### CSM Driver(s)

CSI Driver for Unity XT v2.1

### Installation Type

csi driver unity

### Container Orchestrator

Kubernetes 1.23.1

### Operating System

RHEL 8

**Comment by karthikk92** [comment]
**Mail communication details**

Hi [@Lucey, Brian](mailto:B.Lucey@dell.com),

This is an expected array behavior. Every time we create a volume with certain space , some percentage of it is reserved for file system.

If the customer is looking for exact space to be available, he/she  needs to do the math based on filesystem being used(example : for ext4, 5 percent is reserved) and create the volume accordingly. As of now driver leaves it to the array on how much space needs to be reserved for filesystem.

We can use the following ticket to track the issue further : 
https://jira.cec.lab.emc.com/browse/KRV-4107

If needed we can get into a zoom call. Please let us know.

Regards,
Karthik K


Internal Use - Confidential
From: Lucey, Brian <[B.Lucey@dell.com](mailto:B.Lucey@dell.com)> 
Sent: Wednesday, March 30, 2022 4:25 PM
To: K, Karthik; Coulombel, Florian; Muthukumarasamy, Prasanna; Gasho, Frank; DevCon BLR CSI Team; Thomas, Rensy; Indukuri, Rajendra; Ghivari, Deepak
Cc: OCallaghan, Mark (CS Cork); Gowtham, Mayura; Schmaelzle, Matt; Gallacher, Sean
Subject: RE: SR 138122165 | Dell CSI driver unity driver for Openshift

Hi Karthik,

Any update on this issue?
Is this an issue with the driver, array or Openshift?
I haven’t been able to test this myself with Unity but when testing via PMAX iSCSI, a 100GB PVC appears as 100GB on the array but 120GB on the pod, with 104GB usable.


Thanks
Brian



Internal Use - Confidential
From: K, Karthik <[Karthik.K1@dell.com](mailto:Karthik.K1@dell.com)> 
Sent: Monday 28 March 2022 15:28
To: Coulombel, Florian; Muthukumarasamy, Prasanna; Gasho, Frank; DevCon BLR CSI Team; Thomas, Rensy; Indukuri, Rajendra; Ghivari, Deepak
Cc: Lucey, Brian; OCallaghan, Mark (CS Cork); Gowtham, Mayura; Schmaelzle, Matt; Gallacher, Sean
Subject: RE: SR 138122165 | Dell CSI driver unity driver for Openshift

Hi,

For the first question, 
We tried to reproduce the scenario by creating a pvc of 100GB size using ext4 file system and ISCSI protocol. We observed that only 98.3 GB of storage space could be used as seen in the screenshot attached. 
We have reached out to unity storage team to know the actual space that would be used by ext4 filesystem.
We had faced similar issue when provisioning using NFS protocol, where meta data was consuming 1.5 GB of the storage space. The issue was resolved by adding 1.5GB space to the requested capacity of the file system volume in the array.
 
For the second question,
As Florian mentioned,  ReadWriteMany (RWX) is supported only for NFS/raw block volumes and  not for ISCSI/FC (as this is not supported from the storage array).

Regards,
Karthik K


Internal Use - Confidential
From: Coulombel, Florian <[Florian.Coulombel@dell.com](mailto:Florian.Coulombel@dell.com)> 
Sent: Monday, March 28, 2022 12:45 PM
To: Muthukumarasamy, Prasanna; Gasho, Frank; DevCon BLR CSI Team; Thomas, Rensy; Indukuri, Rajendra; Ghivari, Deepak
Cc: Lucey, Brian; OCallaghan, Mark (CS Cork); Gowtham, Mayura; Schmaelzle, Matt; Gallacher, Sean
Subject: RE: SR 138122165 | Dell CSI driver unity driver for Openshift

Hi,
On the first question about the size of the PV has an interesting point.
[@Muthukumarasamy, Prasanna](mailto:Prasanna.Muthukumars@dell.com), maybe there is an enhancement to implement to reserve space for the meta data with formatted LUNs (as we do with NFS share). I’m not sure what is the recommendation in our field about that.

On the ReadWriteMany, the problem is that to allow multiple nodes to access the same block device we need a filesystem that accepts concurrency (NFS, GlusterFS, etc.) ; ext4 doesn’t allow concurrent access.
To allow RWX with Unity you have to use a Raw Block device ([volumeMode: block](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode)) or the NFS provider.

HTH

--- Answers in French
Comme décrit dans l’article, une fois formatté une partie de l’espace du volume est réservé pour les meta-données ext4.
Les solutions sont soit de :
-	demander un volume plus grand
-	ou de redimentionner le volume existant
-	ou d’utiliser un Raw Block Device en assumant que l’application va le formatter (ce qui semble être le cas d’après l’article).

ReadWriteMany signifie que plusieurs nœuds ou serveurs vont accéder au même volume de façon concurrente. Ext4 n’est pas un système de fichiers qui supporte la distribution sur plusieurs serveurs. Il n’est donc pas possible d’utiliser RWX.
Avec Unity, le RWX est supporté pour un accès via NFS ou avec un Raw Block device (volumeMode: block) en assumant que l’application qui utilise ce volume s’occupe de l’intégrité des données.

Cdt.


Internal Use - Confidential
From: Muthukumarasamy, Prasanna <[Prasanna.Muthukumars@dell.com](mailto:Prasanna.Muthukumars@dell.com)> 
Sent: Monday, March 28, 2022 6:40 AM
To: Gasho, Frank; Coulombel, Florian; DevCon BLR CSI Team; Thomas, Rensy; Indukuri, Rajendra; Ghivari, Deepak
Cc: Lucey, Brian; OCallaghan, Mark (CS Cork); Gowtham, Mayura; Schmaelzle, Matt; Gallacher, Sean
Subject: RE: SR 138122165 | Dell CSI driver unity driver for Openshift

+ [@Thomas, Rensy](mailto:Rensy.Thomas@dell.com), [@Indukuri, Rajendra](mailto:Rajendra.Indukuri@dell.com) [@Ghivari, Deepak](mailto:Deepak.Ghivari@Dell.com)

Thanks and Regards,
Prasanna M. 
[Prasanna.Muthukumars@dell.com](mailto:Prasanna.Muthukumars@dell.com)


Internal Use - Confidential
From: Gasho, Frank <[Frank.Gasho@dell.com](mailto:Frank.Gasho@dell.com)> 
Sent: Saturday, March 26, 2022 1:13 AM
To: Coulombel, Florian; DevCon BLR CSI Team
Cc: Lucey, Brian; OCallaghan, Mark (CS Cork); Gowtham, Mayura; Muthukumarasamy, Prasanna; Schmaelzle, Matt; Gallacher, Sean
Subject: SR 138122165 | Dell CSI driver unity driver for Openshift

+ Unity CSI team and Engineering management for awareness
Also pasted in Slack for awareness.

Hi Florian,
I notice there is a case in our q for Monday 5 am pickup for a customer in France called [ORANGE OAB VAL DE REUIL (FR)](https://dellservices.lightning.force.com/lightning/r/0010b00002NGWOqAAP/view) with requested language of French.  I was curious if you could help our EMEA team out with some of this?  

138122165
[ORANGE OAB VAL DE REUIL (FR)](https://dellservices.lightning.force.com/lightning/r/0010b00002NGWOqAAP/view)
[Nicolas SIMON](https://dellservices.lightning.force.com/lightning/r/0032R00002DGTwnQAH/view)
Severity: Medium

For the first question, I’m not familiar with some of what they are doing and I don’t find any hits for similar in Jira for what has been described so far in the Bugzilla.  I don’t have access to the Red Hat solution that is linked in the Bugzilla(but asked in Slack).  From the github that is linked in the Bugzilla could it be as simple as using a bigger PV?  Like I said, I am not familiar with what they are doing.  It might not even be our issue since there is a PR.  This isn’t the typical create a PV/PVC and assign it to a pod that we usually do.  We will need to get some logs and better details, but since this is new to me and my team it may be good to get you and/or engineering on the call sooner rather than later to get the details.

For the second question RWX is supported.  I pasted print screens from the support matrix below.  So I’m not sure where the confusion comes from here.

Customer opened the case with the following with a description in the Bugzilla.  I am not clear if this is the same customer or if there are 2 customers out there with the same issue:
Hi,
We currently building an OpenShift cluster (3 nodes compact mode cluster) with an DELL UNITY fiberchannel disk array.
At the moment we’ve installed OpenShift 4.9 with your DELL CSI-unity driver release 1.6.

We’ve notice two issues with CSI Driver :

The first one is an issue with RedHat "Migration Toolkit for Virtualization" application which is supposed to import virtual machines from a RedHat Virtualization cluster to an Openshift Virtualization environment.
When doing such an import using Filesystem volume mode, we cope with an issue regarding volume size.
You’ll find all details concerning this issue in the following RedHat Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=2059057 [[bugzilla.redhat.com](https://bugzilla.redhat.com/)] which is exactly what we’ve encountered.

We don't currently know if this issue is resulting from the application itself or from DELL CSI driver ext4 implementation.

The Second one is that, in some cases, we need use a single PV in more than one container at same time.
It's seem that, in this case, we need use the PV in ReadWriteMany access mode.
We’ve notice that your documentation tell that this access mode in currently not available according to our configuration.
So questions are :
Do you plan to put this kind of access mode in DELL CSI Driver (as Red Hat tells us it's just a matter of driver coding) ?
If Yes, is there an existing roadmap or a currently existing driver version with this feature implemented ?
Is there any applicable workaround for this case ?

As mentioned by phone, we’ll quickly create an helpdesk ticket for this.
, Additional Info: { Sales Order Number: 00000}


For clarification I think they mean that they are using Operator version 1.6.  Not CSI Driver for Unity 1.6.  This is often confused.  According to the 1.6 releases this supports OpenShift 4.9:
https://github.com/dell/dell-csi-operator/releases

To me it looks like RWX is supported:
https://dell.github.io/csm-docs/v1/csidriver/
 

Ext4 and FC look supported:
 


Thanks,
Frank

Frank Gasho
Senior Engineer | Primary Storage Integrated S/W 
Dell Technologies | ISG Support Services
1-800-945-3355 EXT. 6278222
[Frank.Gasho@Dell.com](mailto:Frank.Gasho@Dell.com)  
Hopkinton, MA, USA (GMT-5)
 
My work schedule is 9:00 am ‒ 5:00 pm ET, Monday – Friday
 
Need assistance outside of my working hours?
ProSupport 800 945 3355
https:/www.dell.com/support/incidents-online/en-us/contactus/dynamic [nam10.safelinks.protection.outlook.com] [nam10.safelinks.protection.outlook.com]
 
My Manager is [derek.silva@emc.com](mailto:derek.silva@emc.com)


Internal Use - Confidential

**Comment by rajendraindukuri** [comment]
Customer is ok to close this as per the internal jira tracking. Hence closing this.
