### ISSUE TITLE
[BUG]: PowerStore CSI container images v2.2.0  invalid tar header containerd

### ISSUE THREAD

**Issue by DougBernhardt** [dell/csm#248]
### Bug Description

RHEL 8.5, K8s 1.23.5 

Failed to pull image "dellemc/csi-powerstore:v2.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/dellemc/csi-powerstore:v2.2.0": failed to extract layer sha256:a8266c26c07ad75f89b5aabd0ed2774c574a150bc56ec556525657ba5b394c9c: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount4251419866: archive/tar: invalid tar header: unknown

Also, with containerd:
ctr image pull docker.io/dellemc/csi-powerstore:v2.2.0
docker.io/dellemc/csi-powerstore:v2.2.0: 

### Logs

ctr image pull docker.io/dellemc/csi-powerstore:v2.2.0
docker.io/dellemc/csi-powerstore:v2.2.0:   
resolved       |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:b66ecb766faf96354d82d4a6f48d6a9245c92803062a2ff0169ae253c7086612: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:8197d1a3d6ff60d66a60f9988945f6e744107934e5ced8cea43961430f2a0b2d:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:4104244c7ae883eabae8df8f3d8b9b255571138d59144d1c60394c0c1cb4cea3:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:9a73823c318df27ae6439d8ef68d58a5926966fe5a2bae1e9b84d9be2806a50f:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:873d1d9a57ac7a7fd3494799d78488c716c6f92c9ed7507ed28bbb616a8aeeaa:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:0daa62afc6a1abf8c26495d0e39d5926be1f306a5a2a72cb7ac82ac10e2002bb:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:f2c135b9c913170f2e5c3b81a745055173275dacdc706d3f80d7f0787d17c60a:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:4ca545ee6d5db5c1170386eeb39b2ffe3bd46e5d4a73a9acbebc805f19607eb3:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:fff56058a36aeca7e99de821eae2915281ba95b1bcbfcac953a05c6224d6b919:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 6.4 s                                                                    total:  98.1 M (15.3 MiB/s)
unpacking linux/amd64 sha256:b66ecb766faf96354d82d4a6f48d6a9245c92803062a2ff0169ae253c7086612...
INFO[0006] apply failure, attempting cleanup             error="failed to extract layer sha256:a8266c26c07ad75f89b5aabd0ed2774c574a150bc56ec556525657ba5b394c9c: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount929016669: archive/tar: invalid tar header: unknown" key="extract-975547576-_979 sha256:a8266c26c07ad75f89b5aabd0ed2774c574a150bc56ec556525657ba5b394c9c"
ctr: failed to extract layer sha256:a8266c26c07ad75f89b5aabd0ed2774c574a150bc56ec556525657ba5b394c9c: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount929016669: archive/tar: invalid tar header: unknown

### Steps to Reproduce

Deploy PowerStore CSI v2.2.0 or ctr image pull docker.io/dellemc/csi-powerstore:v2.2.0

### Expected Behavior

Should pull and deploy container images

### CSM Driver(s)

CSI Driver for PowerStore v2.2.0

### Installation Type

Helm

### Container Orchestrator

Kubernetes v1.23.5

### Operating System

RHEL 8.5

**Comment by coulof** [comment]
Hi @DougBernhardt,
Can you share the details of the container runtime (version, etc.) ?

I had seen this before but wasn't able to reproduce it.

I found this ticket https://bugzilla.redhat.com/show_bug.cgi?id=1826559 that explains there was a bug with Podman build format.

**Comment by coulof** [comment]
@harishp8889  & @prablr79, I have done extra verification and there is indeed issue with our images on :
```
crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.6.2
RuntimeApiVersion:  v1alpha2
```
If save/load the image to docker then it works.

We should rebuild with `--format=docker` & repush our images.

If you need access to Doug's system please contact us via email.

**Comment by prablr79** [comment]
@harishp8889 @francis-nijay we need to quickly respond i do see another customer issue coming on the similar issue

**Comment by francis-nijay** [comment]
Issue is caused by https://bugzilla.redhat.com/show_bug.cgi?id=1826559 and happens on containerd.
To build the image we should be using a podman version with a fix for the above problem.

@DougBernhardt can you please try installation again

**Comment by harishp8889** [comment]
@DougBernhardt We have pushed a new image now (Same tag), Please try to pull and install it. Thank you!
