### ISSUE TITLE
[FEATURE]: Implement `maximum_volume_size` for each driver

### ISSUE THREAD

**Issue by coulof** [dell/csm#249]
**Describe the solution you'd like**
Spec v1.6 is out ! https://github.com/container-storage-interface/spec/releases/tag/v1.6.0 & made GA the feature : "Promote `maximum_volume_size` field in `GetCapacityResponse`"

It will be nice to implement it and each array type sets its limit.

**Comment by adarsh-dell** [comment]
Hi @coulof I think this one will get covered as part of https://github.com/dell/csm/issues/905. Can we close it?
