### ISSUE TITLE
[BUG]: Wrong deployment method for the Snapshotter

### ISSUE THREAD

**Issue by coulof** [dell/csm#250]
### Bug Description

The installation example for the snapshotter is deprecated : https://github.com/dell/csm-docs/blame/main/content/docs/csidriver/installation/helm/powermax.md#L134

In 5.0+ we need to use `kustomize` to install the CRD and external snapshotter : 
https://github.com/kubernetes-csi/external-snapshotter/tree/v5.0.1#:~:text=Install%20Snapshot%20CRDs%3A

Can you please update all the references to the example install to reflect the new procedure ?

### Logs

No log

### Steps to Reproduce

Apply the example steps and it returns the errors:
```
error: unable to recognize "client/config/crd/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
error: unable to recognize "deploy/kubernetes/snapshot-controller/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
```

### Expected Behavior

No error

### CSM Driver(s)

Doc for CSI PowerMax at least

### Container Orchestrator

1.23

### Operating System

RHEL 8.3

**Comment by shanmydell** [comment]
Fix has been merged
