### ISSUE TITLE
[QUESTION]: Getting error while creating dell isilon custom resource: error: unable to recognize "isilon_v220_k8s_121.yaml": no matches for kind "CSIIsilon" in version "storage.dell.com/v1"

### ISSUE THREAD

**Issue by kps805** [dell/csm#253]
### How can the Team help you today?
Hi Dell Team,
i am getting this error while creating CR "error: unable to recognize "isilon_v220_k8s_121.yaml": no matches for kind "CSIIsilon" in version "storage.dell.com/v1""
i hva this k8s version:
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:02:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Using the yaml file  "isilon_v220_k8s_121.yaml"

Please help.  I have opened this service request with Dell support as well: SR # 138702394

**Comment by shanmydell** [comment]
Thanks for reaching out to us @kps805. @randeepsharma Could you please have a look?

**Comment by prablr79** [comment]
@kps805 are you using Openshift if yes which version ? I believe you have picked up the code directly from here https://github.com/dell/dell-csi-operator/blob/main/samples/isilon_v220_k8s_121.yaml  correct ?

**Comment by prablr79** [comment]
@nitesh3108 can you take a quick look on this case ? if we get more information around the Openshift environment.

**Comment by prablr79** [comment]
@kps805 its clearly documented , if you need any further help please ping  us on the same defect. you can also refer https://dell.github.io/csm-docs/docs/csidriver/installation/operator/isilon/ 
apiVersion: storage.dell.com/v1
kind: CSIIsilon
metadata:
  name: isilon
  namespace: test-isilon
spec:
  driver:
    # Config version for CSI PowerScale v2.2.0 driver
    configVersion: v2.2.0
    replicas: 2
    dnsPolicy: ClusterFirstWithHostNet
    forceUpdate: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    common:
      # Image for CSI PowerScale driver v2.2.0
      image: "dellemc/csi-isilon:v2.2.0"
      imagePullPolicy: IfNotPresent

**Comment by kps805** [comment]
Please close this ticket as we no longer have this setup.

Regards,
Kanwar


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by shanmydell** [comment]
Closing the issue as per the response
