### ISSUE TITLE
CSI Driver for Unity - FC configuration problems

### ISSUE THREAD

**Issue by warende** [dell/csm#264]
I have three Ubuntu physical hosts that are cabled for FC to a Unity 500 SAN.  Using Rancher to provision kubernetes clusters on these Ubuntu hosts. Each host has it's own 200GB FC LUN with WWN which the Ubuntu host is installed on.  We also want to use this FC initiator to provision Kubernetes LUNS on the Unity 500.

A couple questions:
1.  When I follow the install instructions, the helm install command:  /csi-install.sh --namespace unity --values ./myvalues.yaml  tries to ssh to each host and check the iscsi configuration. Why is this if I'm running FC?  Should this part just be ignored when running FC?

2.  There are problems with the unit-node pods starting up.  The first host in the cluster, the pod unity-node starts up correctly, and says "Got FC Initiators, Checking health of initiators." "FC Health is good for array: apm2342342342".   But on the 2nd and 3rd Ubuntu hosts, that have the 4TB LUN mapped to them shows the error:  REP 0006: rpc error: code = Unavailable desc = runid=6 The node [ah22-myhost-002] is not added to any of the arrays.  Each host when i run "multipath -l"  I can see the mpath 4TB LUN.

**Comment by karthikk92** [comment]
@warende  Could you please share the csi driver logs with debug enabled.

**Comment by karthikk92** [comment]
https://jira.cec.lab.emc.com/browse/KRV-4695 this issue is resolved . Hence closing the issue.
