### ISSUE TITLE
[BUG]: New nodes are not recognised by csi-unity driver and Pod NFS mount fails v2.2.0

### ISSUE THREAD

**Issue by jb33441** [dell/csm#275]
### Bug Description

New Openshift nodes which are NFS clients of Unity were added to Openshift cluster, however if a POD moves to one of these new nodes the csi-unity driver does not update the NFS client export permissions for the IP address of the new node, which causes NFS mount failure of that POD. This mechanism of export permission change works fine when the POD comes up on a node which was part of initial configuration.

The mechanism to inform csi-unity driver that new nodes are part of Openshift cluster seems to not be working

### Logs

Warning FailedAttachVolume 5m56s attachdetach-controller AttachVolume.Attach failed for volume "hostname-e6fe613c52" : rpc error: code = NotFound desc = runid=97 Find Host Failed unable to find host

### Steps to Reproduce

Add new nodes to Openshift cluster, attempt to bring up Pod on new Node

### Expected Behavior

Unity NFS export for Pod volume should be updated with IP address of new host the Pod is on

### CSM Driver(s)

csi-unity:v2.2.0

### Container Storage Modules Enabled

docker.io/dellemc/dell-csi-operator:v1.7.0

### Container Orchestrator

openshift 4.9.27

### Operating System

RHEL8

**Comment by coulof** [comment]
Hi @jb33441,
Can you confirm that the driver runs on these newly added nodes with : `kubectl get pods -o wide -n unity` ?

In the same idea, when you run : `kubectl describe csinode [your new node name]` do you see any details from CSI Unity ?

If you go into the host section of Unisphere do you see the new nodes ?

Do you see any errors from `driver` & `registrar` containers running on the newly added node ?

Thanks.

**Comment by jb33441** [comment]
Found issue after enabling csi debug mode was a mismatch/typo in Unity tenant name on Unity array vs csi array definition which caused Rest API to Unity to fail. After Unity Tenant name aligned/corrected everything works fine.

time="2022-04-22T03:53:04Z" level=debug arrayid=de406214046092 runid=node-9 msg="Adding node [de406214150360] failed, Error: [rpc error: code = Internal desc = runid= Unable to add host. Error: rpc error: code = Internal desc = runid= Ple
ase enter Valid tenant Name : OpenShift]" func="github.com/dell/csi-unity/service.(*service).syncNodeInfo.func2.1()" fil
e="/go/src/csi-unity/service/node.go:1886"

**Comment by karthikk92** [comment]
As per comments issue looks like resolved. Are we good to close this ticket ? @jb33441

**Comment by jb33441** [comment]
> As per comments issue looks like resolved. Are we good to close this ticket ? @jb33441

Yes, thanks
