### ISSUE TITLE
[BUG]: Grafana installation scrript - prometheus address is incorrect

### ISSUE THREAD

**Issue by DougBernhardt** [dell/csm#278]
### Bug Description

In the grafana deployment instructions, the address for the prometheus appears to be incorrect and the data source is therefore invalid.  The correct address should be: http://prometheus-server:9090.  Not http://prometheus:9090.

### Logs

Loading the prometheus data source in grafana and testing results in "bad gateway" error

### Steps to Reproduce

Deploy prometheus and grafana according to instructions here:
https://dell.github.io/csm-docs/docs/observability/deployment/

### Expected Behavior

Grafana datasource should be connected and working.

### CSM Driver(s)

CSM for PowerStore

### Container Orchestrator

Kubernetes v1.23.5

### Operating System

RHEL 8.5

**Comment by sharmilarama** [comment]
Thanks @DougBernhardt, we will investigate this and let you know.

**Comment by shaynafinocchiaro** [comment]
Hi @DougBernhardt this serves as an example. This should be the IP/PORT of your running Prometheus instance. This can be found by running `kubectl -n [CSM NAMESPACE] get svc/prometheus-server`.

**Comment by DougBernhardt** [comment]
OK.  perhaps mention that it's just an example and include that step.  Since the previous steps walk through deploying prometheus, then I guess I assumed that tied back to the previous step and that I would not need to resolve it in my environment and modify the value, if that make sense.

**Comment by shaynafinocchiaro** [comment]
Yes, I will make the necessary changes to the documentation.

**Comment by rsedlock1958** [comment]
I have reviewed this and made one minor grammatical update.
