### ISSUE TITLE
[FEATURE]: Annotation to set the default SC is not beta anymore

### ISSUE THREAD

**Issue by coulof** [dell/csm#281]
**Describe the solution you'd like**
The annotation to set the default StorageClass syntax has not been beta since at least k8s v1.19 : https://v1-19.docs.kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

Please update the documentation, samples & operator to use the correct syntax : `storageclass.kubernetes.io/is-default-class` instead of the `storageclass.beta.kubernetes.io/is-default-class`

**Comment by rajendraindukuri** [comment]
This has been addressed
