### ISSUE TITLE
[BUG]: PowerStore is not updated with CSI spec it is supporting 

### ISSUE THREAD

**Issue by shanmydell** [dell/csm#295]
### Bug Description

ReadMe of PowerStore is not updated with CSI spec that it supports 

### Logs

ReadMe of PowerStore is not updated with CSI spec that it supports 

### Steps to Reproduce

view read me file

### Expected Behavior

updated to CSI spec 1.5 

### CSM Driver(s)

CSI Driver for PowerStore

### Container Orchestrator

NA

### Operating System

NA

**Comment by Prabhu-Dell** [comment]
Updated the readme, hence closing the issue.
