### ISSUE TITLE
[BUG]: multipathd errors: tur checker reports path is down

### ISSUE THREAD

**Issue by centromere** [dell/csm#296]
### Bug Description

I am receiving many error messages from multipathd (see logs). Additionally, `multipath -ll` reports that many devices are in the `failed faulty running` state.

### Logs

```
$ sudo journalctl -fu multipathd
-- Logs begin at Fri 2022-05-06 20:44:39 UTC. --
May 11 16:40:10 k8s-worker-prod-ny5-1 multipathd[4554]: mpathaq: sdak - tur checker reports path is down
May 11 16:40:10 k8s-worker-prod-ny5-1 multipathd[4554]: mpathas: sdal - tur checker reports path is down
May 11 16:40:10 k8s-worker-prod-ny5-1 multipathd[4554]: mpathm: sdap - tur checker reports path is down
May 11 16:40:10 k8s-worker-prod-ny5-1 multipathd[4554]: mpathy: sdas - tur checker reports path is down
May 11 16:40:10 k8s-worker-prod-ny5-1 multipathd[4554]: mpathy: sdac - tur checker reports path is down
...
```

```
$ sudo multipath -ll | grep fault
  |- 6:0:4:13  sdaq 66:160  failed faulty running
  |- 6:0:2:13  sdaa 65:160  failed faulty running
  |- 19:0:3:13 sdcj 69:112  failed faulty running
  `- 19:0:4:13 sdcm 69:160  failed faulty running
  |- 6:0:0:34  sde  8:64    failed faulty running
  |- 6:0:1:34  sdq  65:0    failed faulty running
  |- 6:0:3:34  sdag 66:0    failed faulty running
  |- 6:0:7:34  sdbe 67:128  failed faulty running
  |- 19:0:0:34 sdbp 68:48   failed faulty running
  |- 19:0:1:34 sdbw 68:160  failed faulty running
...
```

### Additional Environment Information

Host: Dell R640
Attachment method: SCSI / FC

### Steps to Reproduce

1. Create statefulset with persistent storage template
2. Scale up
3. Scale down
4. Ensure the host mapping is removed prior to proceeding
5. Repeat

### Expected Behavior

I do not expect devices to linger in the `failed faulty running` state.

### CSM Driver(s)

CSI Driver for PowerStore v2.2.0

### Installation Type

Helm 3.8.2

### Container Orchestrator

Kubernetes 1.22.8

### Operating System

Ubuntu 20.04.4

**Comment by spriya-m** [comment]
@centromere , is this issue still seen? If so, can you please try with latest CSI PowerStore driver version - 2.4.0 and let us know the results?

**Comment by shanmydell** [comment]
@centromere: Due to no response, closing this issue. Please feel free to reopen if the issue persists, thanks.

**Comment by sunkai-XDD** [comment]
I meet the same question。。。
