### ISSUE TITLE
[QUESTION]: Share volume between multiple pods using PowerStore CSI ?

### ISSUE THREAD

**Issue by denis256** [dell/csm#311]
### Share volume between multiple pods using PowerStore CSI

Hello,
I was looking for a solution to share one volume between multiple pods, and noticed that [documentation](https://dell.github.io/csm-docs/v2/csidriver/features/powerstore/#raw-block-support) mention support for `ReadWriteMany` mode, but in [page](https://dell.github.io/csm-docs/blog/2020/09/28/csi-drivers-volume-expansion-and-beta-snapshot-support-update/#csi-driver-for-powerstore) is mentioned about NFS that can be used for concurrent access, so I'm not sure in the end if `ReadWriteMany` is supported and how can be used

**Comment by coulof** [comment]
Hi @denis256,
`ReadWriteMany` is supported with NFS only ; the concurrency is given by NFS protocol.
