### ISSUE TITLE
[BUG]: Offline Bundle Script is Looking for image version that doesn't exist in Docker repo

### ISSUE THREAD

**Issue by thechrislee** [dell/csm#312]
### Bug Description

I am attempting to run csi-offline-bundle.sh to create an offline bundle. The manifest that the script is using is looking for an image that is tagged with version 2.3.0. However, I do not see that version on dockerhub. Version 2.2.0 is the latest version I see on Dockerhub. Am I using the wrong repo?

### Logs

```
$ ./csi-offline-bundle.sh -c

*
* Building image manifest file

   Processing files in repos/csi-powerscale/helm

*
* Pulling and saving container images

   dellemc/csi-isilon:v2.3.0

ERROR
Received a non-zero return code (125) from the following comand:
  /usr/bin/docker pull dellemc/csi-isilon:v2.3.0

Output was:
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Resolving "dellemc/csi-isilon" using unqualified-search registries (.config/containers/registries.conf)
Trying to pull docker.io/dellemc/csi-isilon:v2.3.0...
Error: initializing source docker://dellemc/csi-isilon:v2.3.0: reading manifest v2.3.0 in docker.io/dellemc/csi-isilon: manifest unknown: manifest unknown

Exiting
```

### Steps to Reproduce

I am following the instructions listed here: https://github.com/dell/csi-powerscale/blob/main/dell-csi-helm-installer/csi-offline-bundle.md

### Expected Behavior

I would assume that the expected behavior is for this to complete without error?

### CSM Driver(s)

CSI Driver for Powerscale v2.3.0

### Container Orchestrator

1.21.9+vmware.1

### Operating System

RHEL 8.5

**Comment by thechrislee** [comment]
As an addendum, driver-image.yaml explicitly warns against modifying the image version.
[https://github.com/dell/csi-powerscale/blob/main/helm/csi-isilon/driver-image.yaml](url)

```
# IT IS RECOMMENDED YOU DO NOT CHANGE THE IMAGES TO BE DOWNLOADED.
images:
  # "images.driver" defines the container images used for the driver container.
  driver: dellemc/csi-isilon:v2.3.0
```

**Comment by coulof** [comment]
The confusion probably comes because you used a `main` branch instead of the tag for the associated version.

The `main` branch contains references to images that are not GA yet.
