### ISSUE TITLE
[BUG]: Authorization proxy server install fails due to missing container-selinux

### ISSUE THREAD

**Issue by tdawe** [dell/csm#313]
### Bug Description

Downloaded a stock RHEL 7.9 image and installed the Authorization RPM. Install failed due to missing container-selinux and k3s-selinux packages. This needs to be documented.

### Logs

Output from /tmp/k3s-install-for-karavi038296718:
```
[INFO]   Skipping k3s download and verify
[INFO]   Skipping installation of SELinux RPM
[ERROR]   Failed to find the k3s-selinux policy, please install:
      yum install -y container-selinux
      yum install -y https://rpm.rancher.io/k3s/stable/common/centos/7/noarch/k3s-selinux-0.4-1.el7.noarch.rpm
```

### Steps to Reproduce

Use stock version of RHEL 7.9 and install the RPM

### Expected Behavior

The install should be successful or the dependencies should be documented.

### CSM Driver(s)

n/a

### Container Storage Modules Enabled

Authorization

### Container Orchestrator

n/a

### Operating System

RHEL 7.9

**Comment by hoppea2** [comment]
Thanks @tdawe, we're looking at including this package

**Comment by tdawe** [comment]
In addition we may require to provide an SELinux policy for the RPM that can be used so that the installation will be successful.
