### ISSUE TITLE
[BUG]: Authorization doesn't provide a CLI to list RoleBindings

### ISSUE THREAD

**Issue by tdawe** [dell/csm#314]
### Bug Description

After assigning a role to a tenant using karavictl, there is no other CLI to list the role bindings. A CLI to list all role bindings or list by tenant or role should be available.

### Logs

n/a

### Steps to Reproduce

1. Create rolebinding using karavictl
2. No other CLI available to list the rolebindings

### Expected Behavior

There should be a CLI to list rolebindings

### CSM Driver(s)

n/a

### Container Storage Modules Enabled

Authorization

### Container Orchestrator

n/a

### Operating System

RHEL 7.9

**Comment by hoppea2** [comment]
Thank you for your submission @tdawe. The team will triage and update with next steps.

**Comment by tdawe** [comment]
After review, the `karavictl tenant get` CLI will also display any roles that are associated with the given tenant.
