### ISSUE TITLE
[BUG]: Authorization sidecar depends on specific namespaces to determine the platform type

### ISSUE THREAD

**Issue by tdawe** [dell/csm#315]
### Bug Description

Authorization sidecar has a dependency on the namespace where the CSI Driver is deployed. For example, when using PowerFlex the supported namespaces are "powerflex", "vxflexos" or "csi-vxflexos". If the driver was deployed in a different namespace, the error "plugin id not found" is returned for all requests to the proxy server.

### Logs

n/a

### Steps to Reproduce

Deploy the PowerFlex (or other driver) in namespace "foo"
After enabling Authorization sidecar, all requests to the proxy server fail with "plugin id not found" because the namespace is used as the platform type

### Expected Behavior

CSI Driver should be able to be deployed in any namespace

### CSM Driver(s)

n/a

### Container Storage Modules Enabled

Authorization

### Container Orchestrator

n/a

### Operating System

n/a

**Comment by hoppea2** [comment]
Thank you for your submission @tdawe. The team will triage and update with next steps.
