### ISSUE TITLE
[BUG]: the latest Dell CSI Operator can't work

### ISSUE THREAD

**Issue by FrancesChunFangChien** [dell/csm#316]
### Bug Description

I believe the latest Dell CSI Operator is v1.7.0, but when I do manual installation by running scrips/install.sh, the POD dell-csi-operator-controller-manager can't work and show its status ImagePullBackOff, and I checked the log shows Failed to pull image "dellemc/dell-csi-operator:v1.8.0"... it is supposed to be v1.7.0 right?

### Logs

  Normal   Scheduled  6m56s                  default-scheduler  Successfully assigned dell-csi-operator/dell-csi-operator-controller-manager-87765bc9d-fq92f to hdfs02
  Warning  Failed     5m56s (x5 over 7m16s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    5m41s (x4 over 7m17s)  kubelet            Pulling image "dellemc/dell-csi-operator:v1.8.0"
  Warning  Failed     5m41s (x4 over 7m17s)  kubelet            Failed to pull image "dellemc/dell-csi-operator:v1.8.0": rpc error: code = Unknown desc = Error response from daemon: manifest for dellemc/dell-csi-operator:v1.8.0 not found: manifest unknown: manifest unknown
  Warning  Failed     5m41s (x4 over 7m17s)  kubelet            Error: ErrImagePull
  Normal   BackOff    2m7s (x20 over 7m16s)  kubelet            Back-off pulling image "dellemc/dell-csi-operator:v1.8.0"

### Steps to Reproduce

git clone https://github.com/dell/dell-csi-operator
cd dell-csi-operator
bash scripts/install.sh
kubectl get pods -n dell-csi-operator
kubectl describe pods -n dell-csi-operator

### Expected Behavior

should be Pulling image "dellemc/dell-csi-operator:v1.7.0", not 1.8.0

### CSM Driver(s)

haven't downloaded PowerScale CSI drive yet...

### Installation Type

the latest operator v1.7.0

### Container Orchestrator

Kubernetes 1.23.6

### Operating System

CentOS 7.9

**Comment by rensyct** [comment]
Hi @FrancesChunFangChien 
Please checkout v1.7.0 from github. Main branch will have the code that is being developed currently. Last released version is v1.7.0

**Comment by shanmydell** [comment]
This is because of the branch being used, if you are still facing the issue @FrancesChunFangChien , please feel free to reopen the issue.
