### ISSUE TITLE
[BUG]: Authorization OPA policies fail if there are hosts or DNS entries for "localhost" that don't resolve to 127.0.0.1

### ISSUE THREAD

**Issue by tdawe** [dell/csm#321]
### Bug Description

If there is a DNS entry or entry in /etc/hosts for "localhost" that doesn't resolve to 127.0.0.1, the OPA policies in Authorization are in an error state. Relying on "localhost" is not sufficient if coredns does not resolve it to 127.0.0.1.

### Logs

n/a

### Steps to Reproduce

1. Create an /etc/hosts file similar to:
```
10.0.0.1 localhost
10.0.0.1 grpc.myhost
```

2. Install Authorization RPM
3. The OPA policies will be in an error state: k3s kubectl get cm/powerflex-urls -n karavi -o yaml
The policy-status snippet from the ConfigMap:
```
openpolicyagent.org/policy-status: '{"status":"error","error":{"Op":"Put","URL":http://localhost:8181/v1/policies/karavi/powerflex-urls/url.rego [localhost],"Err":{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"10.0.0.1","Port":8181,"Zone":""},"Err":{"Syscall":"connect","Err":111}}}}'
```

In order to fix, update /etc/hosts to:
```
127.0.0.1 localhost
10.0.0.1 grpc.myhost
```
Uninstall Authorization and then re-install.

### Expected Behavior

The policy-status should be in a successful state

### CSM Driver(s)

n/a

### Container Storage Modules Enabled

Authorization

### Container Orchestrator

N/A

### Operating System

RHEL 7.9

**Comment by hoppea2** [comment]
Thank you for your submission @tdawe. The team will triage
