### ISSUE TITLE
[QUESTION]: Powerscale CSI driver support OCP4.10 

### ISSUE THREAD

**Issue by wanghaoyuan2022** [dell/csm#337]
### How can the Team help you today?

Team, Do we have  any schedule to support OCP4.10 with Powerscale CSI driver? 

thanks!

**Comment by nitesh3108** [comment]
@wanghaoyuan2022 Yes, OCP-4.10 support is planned with Upcoming release of CSI PowerScale Driver v2.3.0 
Expected to release soon in coming weeks.
