### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by gashof** [dell/csm#345]
### Bug Description

Nithesh suggested opening a github issue for some of the behavior and questions we had related to the operator install instructions.  He will reach out in regards to these issues.

At this link we show how to install the operator
https://dell.github.io/csm-docs/docs/csidriver/installation/operator/#steps

These are the steps provided.
1. Clone the Dell CSI Operator repository.
2. cd dell-csi-operator
3. git checkout dell-csi-operator-`your-version’
4. Run bash scripts/install.sh to install the operator.

The checkout doesn't work for 1.7.0 but works for 1.6.0:
[root@lsisfty95 dell-csi-operator]# git checkout dell-csi-operator-1.7.0
error: pathspec 'dell-csi-operator-1.7.0' did not match any file(s) known to git.
[root@lsisfty95 dell-csi-operator]# git checkout dell-csi-operator-1.6.0
Branch dell-csi-operator-1.6.0 set up to track remote branch dell-csi-operator-1.6.0 from origin.
Switched to a new branch 'dell-csi-operator-1.6.0'
[root@lsisfty95 dell-csi-operator]# git branch
* dell-csi-operator-1.6.0
  main

It doesn't look like we have a 1.7.0 branch?
[root@lsisfty95 dell-csi-operator]# git branch -a
* dell-csi-operator-1.6.0
...
  remotes/origin/dell-csi-operator-1.4.0
  remotes/origin/dell-csi-operator-1.5.0
  remotes/origin/dell-csi-operator-1.6.0

[root@lsisfty95 dell-csi-operator]# git tag
csi-operator-v1.0.0
v1.0.0
v1.1.0
v1.2.0
v1.3.0
v1.4.0
v1.5.0
v1.6.0
v1.7.0
v1.8.0

We should 
make the docs so that novice and experts can use.
Explain that they are downloading all the versions and that the checkout command will get the version that they will use.  
Provide sample like we do in other areas of the docs
Fix step 3 syntax that is not clear and/or branch.  If the customer can't figure out this syntax for checkout/or the branch isn't there and doesn't use a tag or branch on step 1 this pulls all the files and in my case it was prerelease of 2.3 but tried to install 2.3 whiteout the 2.3 driver files being available yet. 
Also, 
We should explain we we don't do git clone -b for branch, or if we can provide that as an option.  Would this be the more simple way?
Why don't we use the tags v1.7.0 and latest?  
Should that be an option to just do git clone -b v1.7.0 https://github.com/dell/dell-csi-operator.git or should git clone -b v1.7.0 https://github.com/dell/dell-csi-operator.git:v1.7.0 work?
why do we force the user to download all of the drivers and images when they may only want to use a certain driver?

### Logs

see above

### Screenshots

n/a

### Additional Environment Information

Env 1(CS Lab)
Operator 1.7
PowerScale 2.2
K8 1.23
CentOS

Env 2
Operator seen during upgrade 1.6 => 1.7
PowerScale driver seen during upgrade 2.1 driver => 2.2
OCP 4.8
PowerScale 8.2.2

### Steps to Reproduce

see above

### Expected Behavior

see above

### CSM Driver(s)

CSI Operator v1.7.0
CSI Driver for PowerScale 2.2

### Installation Type

CSI Operator v1.7.0

### Container Storage Modules Enabled

n/a

### Container Orchestrator

OpenShift and K8

### Operating System

CentOS CoreOS

**Comment by shanmydell** [comment]
Documentation has been taken care.

**Comment by rajendraindukuri** [comment]
Hi @gashof,

Thanks for your inputs. Updated the documentation to make use of tags instead of branches. I think all the other points mentioned as part of the ticket are covered with this change except "why do we force the user to download all of the drivers and images when they may only want to use a certain driver?". We will handle this as part of the other git hub issue raised https://github.com/dell/csm/issues/348

If you are fine with the changes done. we will clos the ticket. Please let us know. 

Thanks
Rajendra

**Comment by gashof** [comment]
Thanks!
I think here:
https://dell.github.io/csm-docs/docs/csidriver/installation/operator/#steps
We should include clarification to put the version after the -b (v1.7.0 for example) just to be crystal clear.
I also think we should include examples to fill in any gaps with these instructions like we do for most of the other installs.

I also think we should put this clarification here for the offline operator install method:
https://dell.github.io/csm-docs/docs/csidriver/installation/offline/#building-an-offline-bundle
