### ISSUE TITLE
[FEATURE]:Should we consider changing the offline operator install method to only include the images related to the driver(and version) to be installed

### ISSUE THREAD

**Issue by gashof** [dell/csm#348]
**Describe the solution you'd like**
Should we consider changing the offline operator install method to only include the images related to the driver(and version) to be installed?
https://dell.github.io/csm-docs/docs/csidriver/installation/offline/
When doing an offline operator install, all images are pulled and pushed regardless of the driver(and version) that the user wished to install.
There would be considerably less images to pull/push/verify 

**Describe alternatives you've considered**
manual steps, modifying files and directories to limit images pulled.

**Additional context**
n/a

**Comment by rensyct** [comment]
Hi @gashof 
Operator supports n-2 version of drivers. Operator has support for 5 drivers. Currently offline script pulls images of the supported versions of every driver and links for each of these are modified to point to internal registry. 
Advantage of this approach is once the tar is created and copied to a system that does not have access to outside network, they can use the same tarball to install any version of the supported driver

**Comment by rensyct** [comment]
Thank you @gashof for explaining in detail.
Firstly we need to understand why offline bundle of dell-csi-operator was designed that way
After that we could try working on fetching only those images that are required to install a specific version of the driver
I have created a backlog item to track the first part https://jira.cec.lab.emc.com/browse/KRV-6357

**Comment by bharathsreekanth** [comment]
@gashof Dell CSI Operator is deprecated. It is recommended to use CSM operator going forward. I am closing this GH issue as no active work is being done on Dell CSI Operator. Thanks.
