### ISSUE TITLE
[BUG]: Replicated PV misses the RootClientEnable parameter

### ISSUE THREAD

**Issue by walker2** [dell/csm#358]
### Bug Description

While testing the CSM replication with PowerScale I noticed an issue with permissions (both NFSv3 & NFSv4).

It looks like after the failover on the target site (site-b) the PV is missing RootClientEnabled

### Logs

See screenshots

### Screenshots

![image](https://user-images.githubusercontent.com/19558513/177147658-e39ebc28-0c7b-40da-984a-9ff1ba639862.png)
![image](https://user-images.githubusercontent.com/19558513/177147681-04b668c2-9413-41cc-a948-9a4178d51dc5.png)

### Steps to Reproduce

Create replicated PV 

### Expected Behavior

Target PV should have RootClientEnabled attribute

### CSM Driver(s)

CSM Replication v1.3.0
CSI Driver for PowerScale v2.3.0

### Container Orchestrator

Any

### Operating System

Any

**Comment by santhoshatdell** [comment]
_RootClientEnabled_ was added to the target PV and it is configurable via StorageClass - user can specify a different value for the target side. This was added when similar work was done for _AzServiceIP_ in https://github.com/dell/csi-powerscale/pull/142

```
<SRC PV>

spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 14Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvcnsl10
    namespace: nsd1
    resourceVersion: "47481543"
    uid: ffd050a7-a57f-4707-b7db-2dce887686a7
  csi:
    driver: csi-isilon.dellemc.com
    volumeAttributes:
      AccessZone: System
      AzServiceIP: 10.xx.xx.xx
      ClusterName: P1
      ID: "10527"
      Name: k8s-ffd050a7a5
      Path: /ifs/data/csi/1/csi-nsd1-10.xx.xx.xx-Five_Minutes/k8s-ffd050a7a5
      RootClientEnabled: "false"
      storage.kubernetes.io/csiProvisionerIdentity: 1678311315590-8081-csi-isilon.dellemc.com
    volumeHandle: k8s-ffd050a7a5=_=_=10527=_=_=System=_=_=P1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: isilon-rep
  volumeMode: Filesystem
status:
  phase: Bound




<TGT PV>

spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 14Gi
  csi:
    driver: csi-isilon.dellemc.com
    volumeAttributes:
      AccessZone: System
      AzServiceIP: 10.xx.xx.xx
      ClusterName: P2
      ID: "98792"
      Name: k8s-ffd050a7a5
      Path: /ifs/data/csi/1/csi-nsd1-10.xx.xx.xx-Five_Minutes/k8s-ffd050a7a5
      RootClientEnabled: "false"
    volumeHandle: k8s-ffd050a7a5=_=_=98792=_=_=System=_=_=P2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: isilon-rep
  volumeMode: Filesystem
status:
  phase: Available
```
