### ISSUE TITLE
[FEATURE]: File Replication Support For Unity

### ISSUE THREAD

**Issue by walker2** [dell/csm#381]
Unity CSI driver needs to support file replication for both sync/async

**Comment by bharathsreekanth** [comment]
@santhoshatdell I see some PRs merged as part of this issue, can you confirm if this ticket can be closed? If not, can you update with what is pending? Thanks.

**Comment by santhoshatdell** [comment]
Hi @bharathsreekanth 
The PRs that were merged were to add initial replication support for Unity and then this [PR](https://github.com/dell/csi-unity/pull/107) has reverted those changes later.
Unity driver does NOT support replication module as of our last release.
