### ISSUE TITLE
[BUG]: Search Site with Lunr searc is broken in latest release of docsy 

### ISSUE THREAD

**Issue by shanmydell** [dell/csm#387]
### Bug Description

[BUG]: Search Site is broken in csm-docs

### Logs

[BUG]: Search Site is broken in csm-docs

### Steps to Reproduce

Search in doc site 

### Expected Behavior

results shld be shown

### CSM Driver(s)

Docs

### Container Orchestrator

NA

### Operating System

NA

**Comment by shanmydell** [comment]
https://github.com/google/docsy/issues/1111 : Issue is seen in latest release of docsy as well, filed a github issue for the same

**Comment by chalin** [comment]
Fixed via https://github.com/dell/csm-docs/pull/297
