### ISSUE TITLE
[BUG]: Using Authorization without dependency on jq

### ISSUE THREAD

**Issue by tdawe** [dell/csm#390]
### Bug Description

CSM Authorization documentation needs to be updated to show token generation steps without using jq. Remove references to using jq.

### Logs

n/a

### Steps to Reproduce

Use Authorization proxy server VM without jq installed

### Expected Behavior

There shouldn't be a dependency on jq

### CSM Driver(s)

n/a

### Container Orchestrator

n/a

### Operating System

RHEL 7.9

**Comment by donatwork** [comment]
@tdawe  Is Python 3 an option? We could use sed which does not have a dependency on much or Python 3, which should be standard now on most distributions.

<generate token> | python3 -c "import json,sys; print(json.load(sys.stdin)['Token'])"

**Comment by tdawe** [comment]
@donatwork Checking on my RHEL 7.9 setup, it comes with Python 2.7.5 so we may need to rely on sed.

**Comment by donatwork** [comment]
Python 2.7.x has been EOLd since 2020-01-01. Even then the same command can work with Python 2.7.x as well as Python 3. Python has been around for a long time. We can use sed but it is ugly. Is that your preference? The command will be this:

| sed -e 's/"Token": //' -e 's/[{}"]//g' -e 's/\\n/\n/g'

**Comment by atye** [comment]
Could we have `karavictl generate token` output valid yaml instead of requiring the user to parse the response? Perhaps we could have a new flag to support valid yaml output.

**Comment by tdawe** [comment]
I like that idea @atye , instead of having to rely on other tools to parse the output. A flag such as `--yaml` could be added so we remain backwards compatible with the current command but provide an option to get the valid yaml.

**Comment by sharmilarama** [comment]
I will add this as an enhancement in our backlog. We can update the documentation to use sed for now if we do not want Python dependency @tdawe?

**Comment by tdawe** [comment]
> I will add this as an enhancement in our backlog. We can update the documentation to use sed for now if we do not want Python dependency @tdawe?

Yes, doc update with sed for now should be fine.

**Comment by donatwork** [comment]
Removed dependencr on jq in favor of sed which is more portable.
