### ISSUE TITLE
[BUG]: node containers crash with "invalid memory address or nil pointer dreference" (CSI driver for PowerStore 2.3.0)  

### ISSUE THREAD

**Issue by ErikZandboer** [dell/csm#399]
### Bug Description

When deploying the CSI driver for PowerStore using Helm onto a freshly installed OpenShift 4.10 setup the controller pods start up ok but the node pods keep crashing showing "panic: runtime error: invalid memory address or nil pointer dreference". 

### Logs

Log from the driver container inside one of the node pods. All node pods show a similar output:
`Read CSI_LOG_FORMAT from log configuration file, format: json
Read CSI_LOG_LEVEL from log configuration file, level: debug
{"level":"info","msg":"updating array info","time":"2022-07-29T12:21:51.176039557Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x13bc2aa]
goroutine 1 [running]:
github.com/dell/csi-powerstore/pkg/array.(*PowerStoreArray).GetIP(...)
/root/redhattest/csi-powerstore/pkg/array/array.go:138
github.com/dell/csi-powerstore/pkg/node.(*Service).updateNodeID(0xc000110dc0)
/root/redhattest/csi-powerstore/pkg/node/node.go:1123 +0x2aa
github.com/dell/csi-powerstore/pkg/node.(*Service).Init(0xc000110dc0)
/root/redhattest/csi-powerstore/pkg/node/node.go:96 +0xe7
main.main()
/root/redhattest/csi-powerstore/cmd/csi-powerstore/main.go:124 +0x55c`

### Screenshots

![image](https://user-images.githubusercontent.com/16650934/181757784-8cd3c1c5-1c81-49e6-9677-bc81b52b5a4c.png)

### Additional Environment Information

[CSI config yamls.zip](https://github.com/dell/csm/files/9219895/CSI.config.yamls.zip)

### Steps to Reproduce

1) Install OpenShift 4.10 using Centos 7.7
2) Install CSI driver 2.3.0 for PowerStore using Helm
3) See the node pods fail to start

### Expected Behavior

node pods becoming "started" with a functional CSI driver.

### CSM Driver(s)

CSI driver for PowerStore 2.3.0

### Installation Type

Helm3

### Container Storage Modules Enabled

None.

### Container Orchestrator

v1.23.5+012e945

### Operating System

Operating System: CentOS Linux 7 (Core)        CPE OS Name: cpe:/o:centos:centos:7             Kernel: Linux 3.10.0-1160.71.1.el7.x86_64

**Comment by spriya-m** [comment]
The issue has been fixed in CSI PowerStore v2.4.
