### ISSUE TITLE
[QUESTION]:Hope to have csm-observability offline upgrade to v1.2.0 guide

### ISSUE THREAD

**Issue by jaeliang77** [dell/csm#400]
Thanks for the csm-observability for powerstore 1.2 feature update!
The customer is trying to upgrade their CSM but unfortunately they can only use offline upgrade.
We try to follow the offline upgrade guide in "https://dell.github.io/csm-docs/docs/observability/deployment/offline/ " but it seems that :
(1) There is no offline upgrade guide , but only reinstall guide for offline customers.
(2) There is still csm-metrics-powerstore:v1.0.0 in the offline installation package if we follow the offline install guide , but not new v1.2.0.

Hope to have your help to upgrade the offline CSM to update version, Many Thanks!!

**Comment by jaeliang77** [comment]
Got reply, we will wait for v1.3.0 release for PV/PVC namespace mapping , and offline upgrade guide. Thx!

**Comment by hoppea2** [comment]
Closing based on @jaeliang77.
