### ISSUE TITLE
[QUESTION]: Powerflex volumes are unavailable after network flaps

### ISSUE THREAD

**Issue by TomasKohout** [dell/csm#412]
### How can the Team help you today?

**Details: ?**

Hi, 

we have issues with Powerflex in Kubernetes (1.22.10) when network flaps happen. IO operations will end with IO error and volume has to be unpublished and published again to work properly. Is there a way how to prevent that from happen? Eg. to queue IO operations or something like that?

**Comment by alikdell** [comment]
Did you look at CSM for Resiliency (https://dell.github.io/csm-docs/docs/resiliency/) ? CSM for Resiliency will cover your use case, what it do not do is queue the IOs (broken), thanks.

**Comment by coulof** [comment]
@TomasKohout, if you have questions on CSM for Resiliency or other Container Storage Modules feel free to reach out from Slack : https://dellemccsm.slack.com.

An invite can be requested here : http://del.ly/Slack_request

**Comment by shanmydell** [comment]
@TomasKohout : We are closing out the issue, as the query has been answered.
