### ISSUE TITLE
[BUG]: CSM Authorization Helm Install

### ISSUE THREAD

**Issue by OA72280** [dell/csm#427]
### Bug Description

Following documentation - https://dell.github.io/csm-docs/docs/authorization/deployment/helm/ - received the following error:

### Logs

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/23239366/184909085-69d62f0e-0fec-47fc-8222-9ae66ade2acb.png)

re-ran the install command: helm -n authorization install authorization -f myvalues.yaml charts/csm-authorization

![image](https://user-images.githubusercontent.com/23239366/184909349-b4c193e9-eeac-4c70-9c46-a38d79edfc98.png)

### Additional Environment Information

RKE1 Kubernetes Version 1.23.7

### Steps to Reproduce

Error: INSTALLATION FAILED: An error occured while checking for chart dependencies. You may need to run ' helm dependency build' to fetch missing dependencies: found in Chart.yaml, but missing in cahrts/directory: cert-manager, ingress-nginx

from a node with kubectl access to cluster - cloned the helm-charts.git for authorization - git clone https://github.com/dell/helm-charts.git

kubectl create ns authorization
vi /samples/csm-authorization/config.yaml - edited the secret 

created the secret in namespace authorization

copied values to myvalues.yaml

helm -n authorization install authorization -f myvalues.yaml charts/csm-authorization

Error: INSTALLATION FAILED: An error occured while checking for chart dependencies. You may need to run ' helm dependency build' to fetch missing dependencies: found in Chart.yaml, but missing in cahrts/directory: cert-manager, ingress-nginx

ran helm dependency build from the csm-authorization directory

### Expected Behavior

n/a

### CSM Driver(s)

PowerFlex CSI 2.2.0

### Container Orchestrator

Kubernetes 1.23.7

### Operating System

Rocky 8.5

**Comment by sharmilarama** [comment]
Hi @OA72280, thanks for reaching out, we will investigate this issue.

**Comment by shaynafinocchiaro** [comment]
Hi @OA72280, please run a `helm dependency update`. It's possible your dependencies are not an acceptable version. I encountered this issue yesterday and running a `helm dependency update` resolved it.

**Comment by OA72280** [comment]
1st - Ran your command in several locations, and only worked when I was in the csm-installer directory.
2nd - Went to run the installation command and was provided the attached error.

![image](https://user-images.githubusercontent.com/23239366/185112563-43711eb2-90e8-4996-858b-80e0ccd4809d.png)


One recommendation that would be beneficial is to remove the csm-installer and karavi-observability directories as that can lead to further confusion. I'd also recommend that any config.yaml and values.yaml files be nested within a single directory from where all commands are to be levied to decrease potential errors.

**Comment by sharmilarama** [comment]
Hi @OA72280, the csm-installer and karavi-observability are separate helm-charts, they cannot be removed. For installing CSM Authorization, please run `helm dependency update` in the charts/csm-authorization directory.

**Comment by shaynafinocchiaro** [comment]
Closing this issue since it has not be updated in some time. Please reopen/open a new issue if the problem persists.
