### ISSUE TITLE
[QUESTION]:iscsi pvc to powerstore, pod need to recreate after network temporary disruption 

### ISSUE THREAD

**Issue by jaeliang77** [dell/csm#444]
Dear support:
       We met a K8S pod iscsi pvc can not access Powerstore pv problem in 8.19. It seemed that the problem related to Network broke temporary because of IP switch replacement . We had to delete and recreate pod , then pvc works normal. We found out that pods using NFS to access Powerstore remain normal after network recovered from disruption . But a lot of pods using iscsi can not recover automatically . 
        Is this work by design? Or anything we can do to make iscsi pod also recover automatically after network disruption？
        Need your kindly advice. Thanks!!

**Comment by AkshaySainiDell** [comment]
Closing this issues as we have addressed this in customer escalation ticket.
