### ISSUE TITLE
[BUG]: Documentation Update for Character Count Limits of 64 

### ISSUE THREAD

**Issue by rawstorage** [dell/csm#451]
### Bug Description

When the name of the SyncIQ policy is created, it must have less than 64 characters. We realized that because, at first, we used some large name for the project name in Openshift, so it wasn’t able to create the SyncIQ policy. We didn’t find any reference about this in the official documentation so we think it could be good to add this explanation to it or remove this limitation in the code.

### Logs

{"error":"DellCSIReplicationGroup.replication.storage.dell.com \"rg-c4b7ac23-ecce-4231-9983-c6d9ec8c9af7\" is invalid: metadata.labels: Invalid value: \"csi-pruebas-storage-kyndryl-isilontlv02-gestion.cajamar.int-Five_Minutes\": must be no more than 63 characters","level":"error","logger":"controller-runtime.manager.controller.persistentvolume","msg":"Reconciler error","name":"powerscale-acb1a8c408","namespace":"","reconciler group":"","reconciler kind":"PersistentVolume","time":"2022-08-22T09:56:59.672824697Z"}

### Steps to Reproduce

Create a SynqIQ Policy with >64 Characters

### Expected Behavior

Working as expected but documentation needs to reflect this limit.

### CSM Driver(s)

CSI for PowerScale

### Installation Type

Helm 2.3

### Container Storage Modules Enabled

Replication v1.1

### Container Orchestrator

K8s 1.23.1

### Operating System

RHEL 8.0

**Comment by coulof** [comment]
This looks to be a limitation coming from Kubernetes.

@dell team, please consider the following updates:
1. Update the CSM doc website as requested
2. In the respective examples (https://github.com/dell/csm-replication/blob/main/repctl/examples/ & https://github.com/dell/csi-powerscale/blob/main/samples/storageclass/isilon-replication.yaml#L52) add a note to indicate the 63 chars limit and therefore advise to keep the prefix short
3. The SyncIQ name limit is set to 100 characters ; @dell team please consider enforcing that validation in the CRD of `DellCSIReplicationGroup`.

Thanks !
