### ISSUE TITLE
[BUG]: "repctl cluster inject --use-sa" doesn't work for Kubernetes 1.24 and above

### ISSUE THREAD

**Issue by seanzhan2014** [dell/csm#463]
### Bug Description

Since Kubernetes 1.24, the default service account won't be generated automatically, unless feature gate LegacyServiceAccountTokenNoAutoGeneration is disabled. https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md

Because of this change, "repctl cluster inject --use-sa" doesn't work for Kubernetes 1.24 and later version.

### Logs

[root@k8s-n1 csm-replication]# repctl cluster inject --use-sa
[2022-09-06 21:11:16]  INFO Generating config maps from existing service accounts
[2022-09-06 21:11:16]  INFO Generating config for service account in site-n1 cluster
Compiling kubeconfig for "default"                [  OK  ]
Extracting secret                                 [  OK  ]
Extracting token                                  Error from server (NotFound): secrets "<none>" not found
[ FAIL ]
[2022-09-06 21:11:16]  INFO
[2022-09-06 21:11:16]  INFO Generating config for service account in site-n2 cluster
Compiling kubeconfig for "default"                [  OK  ]
Extracting secret                                 [  OK  ]
Extracting token                                  Error from server (NotFound): secrets "<none>" not found
[ FAIL ]

### Steps to Reproduce

Run "repctl cluster inject --use-sa" on Kubernetes 1.24 or later version.

### Expected Behavior

"repctl cluster inject --use-sa" still able to process.

### CSM Driver(s)

CSM 1.3

### Container Storage Modules Enabled

csm-replication

### Container Orchestrator

Kubernetes 1.24

### Operating System

CentOS7

**Comment by coulof** [comment]
@team,
The request is to :
1. Update the documentation to create a proper account
2. Patch to `repctl cluster inject --use-sa` to self generate the accounts

We can not ask the user to change a feature gate.

**Comment by falfaroc** [comment]
In the upcoming release, installing `csm-replication` on the clusters using the installation [script](https://dell.github.io/csm-docs/docs/replication/deployment/installation/#using-the-installation-script) will solve the `./repctl cluster inject --use-sa` issue.

In a future release, the above issue will be addressed via the installation of the replication controller using `repctl` path ([step 3](https://dell.github.io/csm-docs/docs/replication/deployment/install-repctl/#install-replication-walkthrough)).
