### ISSUE TITLE
[QUESTION]: ftp.emc.com login incorrect

### ISSUE THREAD

**Issue by TomasKohout** [dell/csm#492]
### How can the Team help you today?

**Details: ?**

Hi, 

emc ftp server login is incorrect thus we are unable to get scini kernel module. Would you know another location of scini kernel driver? We used ftp://[removed]@ftp.emc.com before.

**Comment by JacobGros** [comment]
Hello
The site has crashed and recovery is in progress.

**Comment by TomasKohout** [comment]
Ok, thanks! Btw those credentials are all over the network. Thought they are widely known. Sorry for my misunderstanding.

**Comment by TomasKohout** [comment]
Btw, @JacobGros , do you have an ETA?

**Comment by JacobGros** [comment]
> Ok, thanks! Btw those credentials are all over the internet. Thought they are widely known. Sorry for my misunderstanding.

No worries

**Comment by JacobGros** [comment]
> Btw, @JacobGros , do you have an ETA?

Not yet. I reached out to team for update and will update this issue when I find out.

**Comment by TomasKohout** [comment]
It's working again! Thanks. :-)
