### ISSUE TITLE
[FEATURE]: Improve deployment documentation

### ISSUE THREAD

**Issue by coulof** [dell/csm#51]
**Describe the solution you'd like**
The [first step of the deployment guide](https://github.com/dell/karavi-authorization/blob/main/docs/GETTING_STARTED_GUIDE.md#deploying-karavi-authorization) is to build the rpm while we release the artifact under : https://github.com/dell/karavi-authorization/releases

It will be nice to have separate instructions to build karavi-authorization with the pre-requisites (go v1.16, CentOS/RHEL 8 to build the rpm, etc.) and link the artifact in the install guide directly.

**Comment by hoppea2** [comment]
Hi @coulof,

We have made a number of improvements in our documentation. The [Deployment Guide for CSM Authorization](https://dell.github.io/csm-docs/docs/authorization/deployment/#single-binary-installer) now links the user first to the location of the [prebuilt rpms for each release](https://github.com/dell/karavi-authorization/releases). Could you review and provide any additional feedback? Thanks!

**Comment by coulof** [comment]
Looks good to me
