### ISSUE TITLE
[FEATURE]: CSI PowerScale documentation misses the privileges to user to use CSM replication

### ISSUE THREAD

**Issue by gallacher** [dell/csm#516]
### Feature Description

When using CSM replication with PowerScale the configured user for the driver needs enough privileges to create and execute SyncIQ policies.

The documentation should reflect the minimal required privileges by CSM replication.

I tried with ISI_PRIV_SYNCIQ and it works but maybe there are less needed privileges.

Documentation should be updated to describe the minimal required privileges by CSM replication.

### CSM Driver(s)

CSI Driver for PowerScale v2.4.0

### Container Storage Modules Enabled

Replication v1.3.0

### Container Orchestrator

Unknown

### Operating System

Unknown

**Comment by harshaatdell** [comment]
ISI_PRIV_SYNCIQ as well as API access via ISI_PRIV_LOGIN_PAPI are required permission at minimum to create and execute snycIQ policies. User has the options to limit the sub-privileges as required. Both permission are captured in csi-powerscale documentation. No further changes required for this feature.
