### ISSUE TITLE
[BUG]: Known issues are missing in Release Notes documentation for Replication 1.3.0

### ISSUE THREAD

**Issue by gallacher** [dell/csm#517]
### Bug Description

There are some known issues with Replication 1.3.0 that are not documented under "Known Issues" in the release notes section of the documentation.

Should include:
- https://github.com/dell/csm/issues/514
- https://github.com/dell/csm/issues/515
- https://github.com/dell/csm/issues/508
- https://github.com/dell/csm/issues/518
- https://github.com/dell/csm/issues/451
- CSM Replication for PowerScale does not support multiple networks - ie. clusters configured with multiple pools including one dedicated to replication traffic

### Logs

N/A

### Screenshots

N/A

### Additional Environment Information

N/a

### Steps to Reproduce

N/A

### Expected Behavior

Documentation for CSM 1.3 and 1.4 contains "Known Issues" in the release notes for Replication.

### CSM Driver(s)

CSI Driver for PowerScale v2.4.0

### Container Storage Modules Enabled

Replication v1.3.0

### Container Orchestrator

N/A

### Operating System

N/a

**Comment by mjsdell** [comment]
Release notes have been updated.
