### ISSUE TITLE
[BUG]: PowerScale Replication - Source directory disappears after failover

### ISSUE THREAD

**Issue by santhoshatdell** [dell/csm#518]
### Bug Description

On CSM for Replication with PowerScale, after a `repctl failover` to a target cluster, the source directory has been removed from the PowerScale.
The PersistentVolume Object is still present in Kubernetes.

### Logs

Issue is reproducible on demand.

### Steps to Reproduce

- Install driver with replication enabled,
- Provision volume to Pod using the storage classes with replication enabled which creates replicated PV,
- Run 'repctl failover' which makes the source directory on the PowerScale to disappear.

### Expected Behavior

Source directory to remain present even after failover operation.

### CSM Driver(s)

CSI Driver for PowerScale v2.4

### Installation Type

Helm v3

### Container Storage Modules Enabled

Replication v1.3

### Container Orchestrator

Kubernetes 1.24.3

### Operating System

RHEL 8.4

**Comment by harshaatdell** [comment]
This issue is now fixed. Failover will work as recommended by the PowerScale SME folks.
