### ISSUE TITLE
[QUESTION]:PowerStore thin provision may lead to inaccuracy Volume used capacity data in CSM observability 

### ISSUE THREAD

**Issue by jaeliang77** [dell/csm#527]
The customer uses CSM observability to monitor PowerStore Volume used capacity they used. They notice that if a volume was temporarily used to a high watermark (such as 90%), then it will always report 90% occupied alerts even the volume capacity has been released for a long time (such as a week ago) .
    We think this may be related to PowerStore thin provision function because we can also see the 90% Volume usage alerts in PowerStore Admin GUI.
    Hope to know if there are any suggestion to handle this problem as our customer is confused by the inaccuracy Volume used information report from CSM observability.
    Many Thanks!!

**Comment by jaeliang77** [comment]
Repost. Thanks!

The customer uses CSM observability to monitor PowerStore Volume used capacity they used. 
They notice that if a volume was temporarily used to a high watermark (such as 90%), then it will always report 90% occupied alerts even the volume capacity has been released for a long time (such as a week ago) .

We think this may be related to PowerStore thin provision function because we can also see the 90% Volume usage alerts in PowerStore Admin GUI.

Hope to know if there are any suggestion to handle this problem as our customer is confused by the inaccuracy Volume used information report from CSM observability.

Many Thanks!!

**Comment by shanmydell** [comment]
@forrestxia : Could you please have a look into this request?

**Comment by forrestxia** [comment]
We had some investigation on this issue, and we need to engage PowerStore CSI expert to understand the issue in further. @shanmydell @baoy1

**Comment by AkshaySainiDell** [comment]
@forrestxia, we did some research and found that CSI driver is not involved here, observability directly interacts with storage API's to gather the space/performance data. Platform or Observability team might be able to help here.

**Comment by baoy1** [comment]
We had a discussion with PowerStore team, and the conclusion is the behavior depends on the filesystem and the mount option.
Please check if the volume is mounted with "discard" option.
Refer to storage-class [mount option](https://kubernetes.io/docs/concepts/storage/storage-classes/#mount-options) for more info.

**Comment by jaeliang77** [comment]
Thanks!! We will contact with the customer to check if mount option can help on this problem. Thx!

**Comment by AkshaySainiDell** [comment]
Hi @jaeliang77 Can we close this ?

**Comment by jaeliang77** [comment]
Yes. Please help to close this issue . Many Thanks!!

________________________________
发件人: Akshay Saini ***@***.***>
发送时间: 2023年2月14日 15:05
收件人: dell/csm ***@***.***>
抄送: jaeliang77 ***@***.***>; Mention ***@***.***>
主题: Re: [dell/csm] [QUESTION]:PowerStore thin provision may lead to inaccuracy Volume used capacity data in CSM observability (Issue #527)


Hi @jaeliang77<https://github.com/jaeliang77> Can we close this ?

―
