### ISSUE TITLE
[QUESTION]:PowerFlex csi driver support NVMeTCP

### ISSUE THREAD

**Issue by wanghaoyuan2022** [dell/csm#549]
### How can the Team help you today?
When will PowerFlex csi driver support NVMeTCP ?
**Details: ?**

**Comment by coulof** [comment]
Hi,
The support for NVMe over TCP in CSI PowerFlex is currently planned for Q2-2023.

Feel free to reach out on Slack https://dell-csm.slack.com for private conversation and if you need more details on the roadmap.

Rgds.
