### ISSUE TITLE
[BUG]: Test issue to validate automation

### ISSUE THREAD

**Issue by atye** [dell/csm#56]
**Describe the bug**
This is a test issue to verify the automation of the service account.

**To Reproduce**
1. Step 1 ...
2. Step 2 ...
3. Step 3 ...
...
n. Step n See error

**Expected behavior**

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - OS/Version: [e.g. RHEL 7.6]
 - Kubernetes Version [e.g. 1.18]
 - Additional Information...

**Additional context**

**Comment by ioeicicdsvc** [comment]
link: 405
