### ISSUE TITLE
[QUESTION]: Unity pods gets into CrashLoopBackOff and Error event

### ISSUE THREAD

**Issue by khengsiong** [dell/csm#569]
Hi Support,

In my environment, I was using offline CSI operator installation and follow the step from this link https://dell.github.io/csm-docs/v2/csidriver/installation/offline/

The Unity CSI driver version i tried to use is 2.2.0 (unity_v220_k8s_121.yaml) as the upstream kubernetes version is v1.21 and also encountered the same issue of Unity pods gets into CrashLoopBackOff event. Any idea?

[admin@xxxx samples:]# kubectl create -f unity_v220_k8s_121.yaml

[admin@xxxx samples:]# kubectl get pods -n unity
NAME READY STATUS RESTARTS AGE
unity-controller-79dd767d54-brnfc 5/5 Running 0 57s
unity-controller-79dd767d54-x2kbs 5/5 Running 0 57s
unity-node-42sm7 1/2 CrashLoopBackOff 5 57s
unity-node-7x3s8 1/2 Error 5 57s
unity-node-68x7w 1/2 CrashLoopBackOff 5 57s

Thanks.

**Comment by keerthi652** [comment]
Hi @khengsiong, thanks for reaching out.
Can you please check the backing unity storage to see if the worker nodes IPs are not already registered under the target unity storage system under a different name?
- Can you please share the describe output of the crashing node pod?
