### ISSUE TITLE
[FEATURE]: CSM support for Openshift 4.12

### ISSUE THREAD

**Issue by rajendraindukuri** [dell/csm#571]
CSM support for Openshift 4.12

As part of this feature, we need to add support for:

- Enabling Openshift 4.12 support on all CSM components
- Qualify all the Openshift 4.12 related scenarios supported by CSM components through HELM charts, CSI Operator and CSM Operator

**Comment by Mal00123** [comment]
@rajendraindukuri As part of seamless customer experience on OCP console for Raven, we will need operator support for CSI/CSM with Openshift 4.12     - Malathy Ramani

**Comment by bharathsreekanth** [comment]
> How are things going with this? This is a real blocker for me to upgrade to OpenShift 4.12 and I would really like to continue using the Dell certified operators.

Things are on track and official support for 4.12 is planned for end of June.

**Comment by bharathsreekanth** [comment]
We do try and stay on track and align with the latest OCP releases each quarter. Q1 2023 was a bit different and for various reasons we could not qualify OCP 4.12. That being said, unfortunately at this time, we will not have official support for 4.12 in our operators (CSI/ CSM) by April 17th and it is planned for end of June as part of our next CSI/CSM release.
