### ISSUE TITLE
CSI driver logs which could not authenticate to the Isilon 

### ISSUE THREAD

**Issue by David-EBIND** [dell/csm#575]
we are getting the below error while running it on the Openshift. We have the HTTP authentication as basic.

OneFS version: 9.4.0.5
CSI : v2.4.0 
    -------------------------- GOISILON HTTP REQUEST -------------------------
    GET /platform/latest/ HTTP/1.1
    Host: test-isilon:8080
    Authorization: kubeadm@test-isilon:******
    

time="2022-12-13T05:13:31Z" level=info msg="podmon is not enabled"
[DEBUG] 
    -------------------------- GOISILON HTTP RESPONSE -------------------------
    HTTP/1.1 401 Unauthorized
    Content-Length: 50
    Accept-Ranges: bytes
    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';
    Content-Type: application/json
    Date: Tue, 13 Dec 2022 05:13:31 GMT
    Etag: "32-5d928e7e4bd00"
    Last-Modified: Tue, 01 Mar 2022 14:23:16 GMT
    Server: Apache
    Strict-Transport-Security: max-age=31536000;
    X-Content-Type-Options: nosniff
    X-Frame-Options: sameorigin
    X-Xss-Protection: 1; mode=block
    
    {"errors":[{"message":"Authorization required"}]}
time="2022-12-13T05:13:31Z" level=error   msg="init client failed for isilon cluster 'test-isilon': 'Authorization required'" file="/go/src/service/service.go:451"
time="2022-12-13T05:13:31Z" level=debug   msg="Probe failed for isilon cluster 'test-isilon' error:'clusterConfig.isiSvc (type isiService) is nil, probe failed'" file="/go/src/service/service.go:299"
time="2022-12-13T05:13:31Z" level=info msg="removed sock file" path=/var/run/csi/csi.sock
time="2022-12-13T05:13:31Z" level=fatal msg="grpc failed" error="probe of all isilon clusters failed"

**Comment by nitesh3108** [comment]
@David-EBIND 

time="2022-12-13T05:13:31Z" level=error msg="init client failed for isilon cluster 'test-isilon': 'Authorization required'" file="/go/src/service/service.go:451"
time="2022-12-13T05:13:31Z" level=debug msg="Probe failed for isilon cluster 'test-isilon' **error:'clusterConfig.isiSvc (type isiService) is nil, probe failed**'" file="/go/src/service/service.go:299"
time="2022-12-13T05:13:31Z" level=info msg="removed sock file" path=/var/run/csi/csi.sock
time="2022-12-13T05:13:31Z" level=fatal msg="grpc failed" error="probe of all isilon clusters failed"

Above logs shows "**(type isiService) is nil**" which indicates that for that particular time when Driver was communicating to OneFS it lost the connectivity to OneFS. (OneFS was unreachable)
Make sure connectivity is consist and not flapping.

Let me know if this helps you to mitigate the issue or any further help is required.

**Comment by David-EBIND** [comment]
Is this only related to the Network flappings? Or is it related to any authentication errors ? We believed it could be an authentication error from the log.

**Comment by nitesh3108** [comment]
Do you use LDAP ?

**Comment by nitesh3108** [comment]
@David-EBIND do you use LDAP or any other authentication mechanism

**Comment by David-EBIND** [comment]
Hi @nitesh3108 , 
No we don't use the LDAP to implement this, we use a local ISILON system kubernetes admin account for this.

It has enough permissions to deploy this,

 Privileges
             ID: ISI_PRIV_LOGIN_PAPI
     Permission: r

             ID: ISI_PRIV_LOGIN_SSH
     Permission: r

             ID: ISI_PRIV_CLUSTER
     Permission: w

             ID: ISI_PRIV_CONFIGURATION
     Permission: r

             ID: ISI_PRIV_HTTP
     Permission: w

             ID: ISI_PRIV_NFS
     Permission: w

             ID: ISI_PRIV_QUOTA
     Permission: w

             ID: ISI_PRIV_SNAPSHOT
     Permission: w

             ID: ISI_PRIV_IFS_BACKUP
     Permission: r

             ID: ISI_PRIV_IFS_RESTORE
     Permission: r

             ID: ISI_PRIV_NS_IFS_ACCESS
     Permission: r

**Comment by rajkumar-palani** [comment]
@David-EBIND 

**Thanks for your response.** using Basic Authentication, we have done a quick check on the CSI driver v2.4.0 in Openshift environment, able to communicate with One FS without any issues.

-------
[DEBUG]
    -------------------------- GOISILON HTTP REQUEST -------------------------
    GET /platform/latest/ HTTP/1.1
    Host: <<IP>>:8080
    Authorization: root:******


[DEBUG]
    -------------------------- GOISILON HTTP RESPONSE -------------------------
    HTTP/1.1 200 Ok
    Transfer-Encoding: chunked
    Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data:; script-src 'self' 'unsafe-eval'; style-src 'unsafe-inline' 'self';
    Content-Type: application/json
    Date: Fri, 13 Jan 2023 01:51:03 GMT
    Server: Apache
    Strict-Transport-Security: max-age=31536000;
    X-Content-Type-Options: nosniff
    X-Frame-Options: sameorigin

time="2023-01-13T07:29:35Z" 
---------------

would like to know, will you be able to connect to One FS using the credentials which you have used for Basic Authentication through browser? if so, can you please check whether the secret is having the right credentials to interact with driver.

**Comment by rajkumar-palani** [comment]
@David-EBIND 

Can you please check my earlier comment and respond. Thank You.

**Comment by David-EBIND** [comment]
Hi @rajkumar-palani 

I was able to solve this by changing the config file from the Openshift to the session based authentication. Then its able to work as expected. 

Regards
David J.

**Comment by rajkumar-palani** [comment]
Thanks @David-EBIND for your response. Glad that it is working as expected.

Regards,
Rajkumar Palani

**Comment by nitesh3108** [comment]
@David-EBIND Was just thinking about your original issue of unable to connect to OneFS via CSI Driver basic auth.
Did you check on OneFS wherther "basic auth" is enabled or not ? if not already pls enable it and give it a try with CSI Driver "basic auth" as well.
Both should work.

**Comment by cragr** [comment]
@David-EBIND  Thank you for posting the solution that isiAuthType needs to be session-based Authentication for OpenShift.

```
# isiAuthType: Indicates whether the authentication will be session-based or basic.
# Allowed values:
#   0: enables basic Authentication
#   1: enables session-based Authentication
# Default value: 0
isiAuthType: 1
```
