### ISSUE TITLE
[QUESTION]: Can you please update the status of PowerScale CSI support for EKS Anywhere to YES 

### ISSUE THREAD

**Issue by thecloudgarage** [dell/csm#579]
I have installed and successfully tested PowerScale CSI 2.2.0 with EKS Anywhere with multiple variations and configurations. I am a part of Dell APJ Presales team. Can you please update the status of the compatbility matrix to yes for the PowerScale CSI for EKS Anywhere.

Please see the below screen shots for the confirmations. Looking forward to the change in status to help our customers.

Please feel free to contact me via Teams via my name Ambar Hassani for any clarification as the setup is already running in my cluster.

![image](https://user-images.githubusercontent.com/39495790/207779348-fceaacae-6380-47d9-8b3f-689dabe8e900.png)

**Comment by nitesh3108** [comment]
Thanks @thecloudgarage for running qual against EKS anywhere. but looks like you ran it with OLD driver version and the latest available is CSI PowerScale v2.5.0, would it be possible for you to confirm for latest CSI Driver.

**Comment by nitesh3108** [comment]
Also, before we claim support for EKS anywhere, pls make sure all sanity is passing.
- create pvc
- create pod
- create snapshot
- restore snap

should be enough to gain the confidence.

**Comment by thecloudgarage** [comment]
All use cases (persistence, backup/restore, volume expansion, prefixes, etc.) mentioned are executed and documented with 2.5.0 driver version. Please see the medium.com article that documents in greater detail with all the logs, etc.

https://ambar-thecloudgarage.medium.com/eks-anywhere-part-2-dellemc-csi-for-powerscale-83b0e330b151

**Comment by nitesh3108** [comment]
Perfect ! PR in on the way.

**Comment by nitesh3108** [comment]
![image](https://user-images.githubusercontent.com/90749010/210496913-31a8f454-3d1b-4c57-8a92-5f3efbefc58f.png)
