### ISSUE TITLE
[QUESTION]: Can you please update the status of Unity XT CSI support for EKS Anywhere to YES

### ISSUE THREAD

**Issue by thecloudgarage** [dell/csm#621]
### How can the Team help you today?

**Details: ?**
I have installed and successfully tested Unity XT CSI 2.5.0 with EKS Anywhere with multiple variations and configurations. I am a part of Dell APJ Presales team. Can you please update the status of the compatbility matrix to yes for the Unity XT CSI for EKS Anywhere on this page
https://dell.github.io/csm-docs/docs/csidriver/

The entire deployment and scenario testing for the UNITY-XT 2.5.0 on EKS Anywhere running 1.23 version of Kubernetes is documented here
Deploying the Unity XT CSI driver on EKS Anywhere: https://ambar-thecloudgarage.medium.com/eks-anywhere-part-1-dell-emc-unity-xt-csi-version-2-2-0-f639773ac488
Scenario testing (including volume creation, persistence, snapshots, etc.): https://ambar-thecloudgarage.medium.com/eks-anywhere-part-2-dell-emc-unity-xt-csi-version-2-2-0-7756103b364e

I had undertaken similar work for PowerScale CSI 2.5.0 and the engineering team took note of all the installation logs and scenarios to finally create the PR and update the status to YES.

Could you please do the needful. Feel free to reach out to me in case,

cheers,

Ambar Hassani

**Comment by rajendraindukuri** [comment]
Hi @thecloudgarage  Thanks for qualifying and the detailed write up. We will work on raising a doc PR for the same.
