### ISSUE TITLE
[BUG]: Documentation - PowerStore Update Driver from v2.4 to v2.5 using Helm docs has wrong file name

### ISSUE THREAD

**Issue by DougBernhardtData** [dell/csm#643]
### Bug Description

https://dell.github.io/csm-docs/docs/csidriver/upgradation/drivers/powerstore/ - Step 2 "Edit helm/config.yaml file and configure connection information for your PowerStore arrays changing the following parameters:".  I believe this should be referring to the sample secret file. helm/config.yaml does not exist. 

### Logs

No logs

### Steps to Reproduce

Follow steps in documentation

### Expected Behavior

Files referenced in documentation steps should be consistent

### CSM Driver(s)

CSI Driver for PowerStore 2.5

### Container Orchestrator

Kubernetes 1.24.6

### Operating System

RHEL 8.6

**Comment by AkshaySainiDell** [comment]
We will fix this in upcoming release.

**Comment by shanmydell** [comment]
@rajkumar-palani : please have a look
