### ISSUE TITLE
[BUG]: When VolumeGroup Snapshot ReadyToUse, the VolumeSnapshot don't have Status

### ISSUE THREAD

**Issue by phuongatemc** [dell/csm#68]
When VolumeGroup Snapshot Ready, the VolumeSnapshot don't have Status

* Using dellemc/csi-volumegroup-snapshotter:v0.2.0, I created VolumeGroup Snapshot of 3 PVCs with same label "volume-group=volumeGroup1" using controller code.
* After the DellCsiVolumeGroupSnapshot.Status ReadyToUse is true, the code tried to fetch the VolumeSnapshot and found that it misses the Status field.
VG Snapshot's Status: {
    "snapshotGroupID": "217b52c106138b0f-c56b7d7100000003",
    "snapshotGroupName": "volumegroup1-102021-184622",
    "snapshots": "volumegroup1-102021-184622-0-pvol0,volumegroup1-102021-184622-1-pvol1,volumegroup1-102021-184622-2-pvol2",
    "creationTime": "2021-10-20T18:45:25Z",
    "readyToUse": true,
    "status": "Complete"
 }
...
Missing Status of volumesnapshot 'volumegroup1-102021-184622-2-pvol2' in ns 'helmtest-vxflexos'.

**Comment by nb950** [comment]
please retest with VG image  0.3.0 , seems related to issue reported in #67

**Comment by phuongatemc** [comment]
I have implemented in my controller code to validate VolumeSnapshot and VolumeSnapshotContent and retry if they are not ready as discussed with Jai Kumar.  So far I couldn't see the problem again.

**Comment by nb950** [comment]
created story action item  to fix this in vgs controller.

**Comment by mjsdell** [comment]
Marking this as closed per the above comment.

**Comment by bharathsreekanth** [comment]
This issue was fixed as part of https://github.com/dell/csi-volumegroup-snapshotter/pull/14.
