### ISSUE TITLE
[FEATURE]: CSM Replication: repctl UX improvements 

### ISSUE THREAD

**Issue by maxan98** [dell/csm#70]
Redesign repctls look&fell to improve UX, based on feedback 
- Use _get_ instead of _list_
- The _to-cluster_ argument in _execute-action_ naming is a not well understandable approach. Need to investigate and come up with proper naming/architecture for _executeAction_.
-Use the  _--wait_ argument for the execute actions command so that repctl will wait for the action to complete.

**Comment by rsedlock1958** [comment]
Made minor edits to the comment.
