### ISSUE TITLE
[QUESTION]: Can CSM resiliency be used in the Openshift environment?

### ISSUE THREAD

**Issue by kocap770607** [dell/csm#700]
### How can the Team help you today?

**Details: ?**
I'd like to use CSM resiliency feature in our Openshift environment. But deployment section says it only support helm chart installation. Is there a way to apply it to the Openshfit CSI environment installed with operator?

------------------------------------------------------------------------
Deployment
CSM for Resiliency is installed as part of the Dell CSI driver installation. The drivers can be installed either by a helm chart or by the Dell CSI Operator. **Currently, only Helm chart installation is supported.**

**Comment by alikdell** [comment]
As of now CSM for Resiliency do not support Operator deployment.

**Comment by sharmilarama** [comment]
Hi @kocap770607, we do not have plans to support Resiliency with Dell CSI operator. It will be supported as part of the Dell CSM Operator(https://github.com/dell/csm-operator) in the future.

**Comment by kocap770607** [comment]
Hi @sharmilarama, thanks for the reply. If so, can CSM resilienct be deployed using helm chart.  In the Openshift environment, if CSI driver is deployed using helm chart I think podmon spec can be applied. 
But we cannot install SDC manually on CoreOS, so if helm chart csi-install.sh is used, it will fail at the SDC check step. How do i solve this? The initcontainer spec is also not in the helm yaml file.

**Comment by bharathsreekanth** [comment]
can you provide the details of your environment, is this on OpenShift and if yes what's the version?

**Comment by kocap770607** [comment]
Thnaks All, I was able to manage it effectively using a Helm chart.
