### ISSUE TITLE
[QUESTION]: Powermax CSI failing to fetch details for array

### ISSUE THREAD

**Issue by mrandhikpurwala** [dell/csm#708]
We are using PowerMax as the CSI Driver for our openshift cluster. After setting up the driver and reverse proxy we get the following error 

{"level":"error","msg":"Failed to fetch details for array: <arraynumber>. [Not Found]","time":"2023-03-10T10:41:26.138717819Z"}
{"level":"error","msg":"None of the managed arrays specified are locally connected","time":"2023-03-10T10:41:26.138753045Z"}

We have verified connectivity to the unisphere management console. How to find the cause of the issue?

**Comment by boyamurthy** [comment]
hi @mrandhikpurwala  , could you share the version details , values file and driver/proxy logs .

**Comment by coulof** [comment]
It looks like a possible configuration issue.

Also, what protocol are you trying to access the PowerMax storage with (iSCSI, Fiber Channel, is the connectivity in place from the worker node ?) ?

**Comment by mrandhikpurwala** [comment]
Hi, we got some assistance from support and were able to investigate that the CSI driver and the version of powermax were incompatible. 

Putting the right version fixed the issue
