### ISSUE TITLE
[QUESTION]:Long time to bound PVC

### ISSUE THREAD

**Issue by ujohan** [dell/csm#71]
Hi.

Latest driver installed with Helm on OpenShift 4.8 and Isilon storage.
When creating a PVC the time until it get bound seams long, about 35 sec.
Any suggestions to improve this?
Some output in the log when a PVC is created attached.

Regards,
-Ulf

[DEBUG]
    -------------------------- GOISILON HTTP RESPONSE -------------------------
    HTTP/1.1 404 Not Found
    Transfer-Encoding: chunked
    Allow: GET, PUT, POST, DELETE, HEAD
    Content-Security-Policy: default-src 'none'
    Content-Type: application/json
    Date: Thu, 21 Oct 2021 06:48:50 GMT
    Server: Apache
    Strict-Transport-Security: max-age=31536000;
    X-Frame-Options: sameorigin
    X-Isi-Ifs-Spec-Version: 1.0

[DEBUG] Error in response. Method:GET URI:namespace/ifs/dst002dc50/nfs_dcc/ocp_test Error: Unable to open object 'dst002dc50/nfs_dcc/ocp_test/k8s-de8dfb1546' in store 'ifs' -- not found. JSON Error: Unable to open object 'dst002dc50/nfs_dcc/ocp_test/k8s-de8dfb1546' in store 'ifs' -- not found.
[DEBUG] the query of volume (id '', name 'k8s-de8dfb1546') returned an error, regard the volume as non-existent. error : 'Unable to open object 'dst002dc50/nfs_dcc/ocp_test/k8s-de8dfb1546' in store 'ifs' -- not found.'
time="2021-10-21T06:48:50Z" level=debug clusterName=dc50nfsdcc runid=19 msg="volume (id :'', name 'k8s-de8dfb1546') already exists : 'false'" file="/go/src/service/isiService.go:412"
time="2021-10-21T06:48:50Z" level=debug clusterName=dc50nfsdcc runid=19 msg="begin getting export with target path '/ifs/dst002dc50/nfs_dcc/ocp_test/k8s-de8dfb1546' and access zone 'dc50nfsdcc' for Isilon" file="/go/src/service/isiService.go:633"

[DEBUG] Execution successful on Method: GET, URI: platform/2/protocols/nfs/exports
time="2021-10-21T06:48:50Z" level=error clusterName=dc50nfsdcc runid=19 msg="error retrieving export ID for 'k8s-de8dfb1546', set it to 0. error : ''.
" file="/go/src/service/controller.go:320"
time="2021-10-21T06:48:50Z" level=error clusterName=dc50nfsdcc runid=19 msg="request parameters: the path is '/ifs/dst002dc50/nfs_dcc/ocp_test/k8s-de8dfb1546', and the access zone is 'dc50nfsdcc'." file="/go/src/service/controller.go:321"
time="2021-10-21T06:48:50Z" level=debug clusterName=dc50nfsdcc runid=19 msg="create volume with header metadata 'k8s-de8dfb1546' has been resolved to 'map[x-csi-pv-claimname:dxy x-csi-pv-name:k8s-de8dfb1546 x-csi-pv-namespace:fredrik]'" file="/go/src/service/controller.go:345"
time="2021-10-21T06:48:50Z" level=debug clusterName=dc50nfsdcc runid=19 msg="begin to create volume 'k8s-de8dfb1546'" file="/go/src/service/isiService.go:102"
time="2021-10-21T06:48:50Z" level=debug clusterName=dc50nfsdcc runid=19 msg="header metadata 'map[x-csi-pv-claimname:dxy x-csi-pv-name:k8s-de8dfb1546 x-csi-pv-namespace:fredrik]'" file="/go/src/service/isiService.go:103"

**Comment by Tharun-vr** [comment]
Hi @ujohan 

Kindly furnish the details: 
1. Is the csi-powerscale Driver version is V 2.0 ?
2. Provide yaml for -  Pvc, Pod , Storage class    -   
3. Output of the following  -   kubectl describe PVC <pvcname>
All Driver logs                     -  kubectl logs <controller pod> -n <namespace> -c driver
                                               kubectl logs <node pod> -n<namespace> -c driver. 

Logs will give us more clarity, Kindly provide to help.

**Comment by ujohan** [comment]
Hi.

Any ideas on this?

-Ulf

**Comment by bpjain2004** [comment]
@ujohan , can you please provide driver logs from controller pod which has logs related to createvolume request. The attached logs are from node pod.

**Comment by ujohan** [comment]
Hi @bpjain2004 

Controller driver log attached.

-Ulf
[controller.log](https://github.com/dell/csm/files/7466708/controller.log)

**Comment by hoppea2** [comment]
Thank you @ujohan , we are investigating and will get back to you.

**Comment by prablr79** [comment]
@bpjain2004 @randeepsharma  any updates on this issue ?

**Comment by randeepsharma** [comment]
Looking at the logs, the quota creation is taking quite some time (28s), due to this PVC is taking longer to bind.
Logs:
time="2021-10-29T07:39:13Z" level=debug clusterName=dc50nfsdcc runid=19 msg="begin to create quota for 'k8s-1081ae50e6', size '1073741824', quota enabled: 'true'" file="/go/src/service/isiService.go:168"
time="2021-10-29T07:39:41Z" level=info clusterName=dc50nfsdcc runid=19 msg="quota set to: 1073741824 on directory: 'k8s-1081ae50e6'" file="/go/src/service/isiService.go:205"

**Comment by prablr79** [comment]
@ujohan if you still facing this issue please open a bug. closing this issue.
