### ISSUE TITLE
Does CSM support Powermax CSI Driver?

### ISSUE THREAD

**Issue by mrandhikpurwala** [dell/csm#710]
We have integrated powermax CSI with our openshift cluster. Does the CSM operator support powermax CSI?

**Comment by shanmydell** [comment]
@mrandhikpurwala : Support is coming in next quarter.

**Comment by mrandhikpurwala** [comment]
@shanmydell  - any update on this, this is important as we are looking to implement dell CSM but we have DELL Powermax as CSI

**Comment by shanmydell** [comment]
@mrandhikpurwala : The feature is in development and will be released in June 2023.

**Comment by mrandhikpurwala** [comment]
Is there a beta release we can test?

**Comment by shanmydell** [comment]
@mrandhikpurwala : Will be updating in the same thread once we have a beta release. Thanks.
