### ISSUE TITLE
[QUESTION]: PowerScale Kubernetes CSI permission denied as non root

### ISSUE THREAD

**Issue by philipp1992** [dell/csm#718]
Hi,
i have deployed the CSI driver 2.5.

I set the IsiPermissions to 777 in the storageclass.
When creating a new PVC, the path on the PowerScale is created with 770 and i cant access the mounted share with a non root user in the container.
When i change the permissions on the PowerScale to 777 manually, i can access it.

What can cause the new share not being created with the permissions i have specified in the storageclass?
kind regards
Philipp

**Comment by philipp1992** [comment]
The problem is, that the path for the PVC on which the nfs export is created, is not created with 777 permissions but 770, even though i have set that in the secret and storageclass to 777. what can be the reason?

**Comment by philipp1992** [comment]
@rajkumar-palani 
Accessing the data with a root user in the container works, but when im a different user, i can not cd into the mount or create files.
What should be the default ACL on the Powerscale? Is there any documentation for creating proper ACLs?
Is there any other way to address this issue?

**Comment by HarishH-DELL** [comment]
@philipp1992 We are trying with non root user , We'll get back you

**Comment by HarishH-DELL** [comment]
@philipp1992 
### for 1st Question 
When csi driver make a call to one-fs for creating the PVC it will copy the permission from the SC irrespective of user . 
Even I can see the for non-root user permission was  different  what we passed when we creating PVC . better to check with one-fs team regarding this .

**Comment by HarishH-DELL** [comment]
@philipp1992 
### for 2nd Question (Accessing the data with a root user in the container works, but when im a different user, i can not cd into the mount or create files.
What should be the default ACL on the Powerscale? Is there any documentation for creating proper ACLs?
Is there any other way to address this issue?)

**ans** 
For non root user we can do **cd** and even we can **create file**  
I tried with my local system for non - root user it is working

**Comment by philipp1992** [comment]
can you check what permissions your directory on onefs has?
Is it possible that we have an ACL that prevents this?
When i change the permissions on the OneFS from 770 to 777 i can cd and create files as non root.

When the PVC is created, the directory on the OneFS will have 770 even though i specified 777 in the storageclass

**Comment by HarishH-DELL** [comment]
1. Permission for my directory is **drwxrwxrwx**
2. These are mandate roles for the user [](https://dell.github.io/csm-docs/docs/csidriver/installation/helm/isilon/#user-privileges)
3. It is working in our local system , I'm using onefs 9.3 version , better check with onefs team ( let me know any help you need from our end )


I created with different permission for PVC . all PVC were created with same permission which I mentioned in the SC .

**Comment by philipp1992** [comment]
thanks,  how can i connect with onefs team? our issue seems to be, that the storageclass has 777 but its not honored when the PVC and share is created

**Comment by HarishH-DELL** [comment]
@philipp1992 before reaching out onefs team . can you show the issue over call ? so i can debug and see where is an issue

**Comment by philipp1992** [comment]
yes, how can we connect ? slack?

**Comment by philipp1992** [comment]
please give me an email to connect

**Comment by HarishH-DELL** [comment]
> please give me an email to connect

harish.h2@dell.com

**Comment by HarishH-DELL** [comment]
@philipp1992 I hope your issue has been resolved!!

**Comment by philipp1992** [comment]
sent you an email

**Comment by philipp1992** [comment]
@gallacher  (mailto:container.storage.modules@dell.com)  bounces, any other way to connect?

**Comment by philipp1992** [comment]
what we notice is, that while the parent directory of the PVCs has 777 on the powerscale, the directory that gets created for the PVC has 770, which explains why only root can mount.

How can we change that? 
<img width="558" alt="image" src="https://github.com/dell/csm/assets/11994884/d1fc35aa-76b9-4b54-9b88-77c4ac977b54">
