### ISSUE TITLE
[QUESTION]: Provisioner keeps failing with lost connection error

### ISSUE THREAD

**Issue by mrandhikpurwala** [dell/csm#721]
Hi the provisioner pod keeps failing with the below error, request some guidance to fix the issue 

I0320 09:24:46.755324       1 connection.go:154] Connecting to unix:///var/run/csi/csi.sock
W0320 09:24:56.764652       1 connection.go:173] Still connecting to unix:///var/run/csi/csi.sock
W0320 09:25:06.764370       1 connection.go:173] Still connecting to unix:///var/run/csi/csi.sock
E0320 09:25:07.766463       1 connection.go:132] Lost connection to unix:///var/run/csi/csi.sock.

**Comment by hoppea2** [comment]
Hi @mrandhikpurwala, can you share some more details?

1. Which driver?
2. Which version?
3. Deployment mode
4. OS env

Thank you!

**Comment by hoppea2** [comment]
Closing for now. Please reopen if the issue persists.
