### ISSUE TITLE
[QUESTION]: Is rke2 supported

### ISSUE THREAD

**Issue by wrender** [dell/csm#734]
### How can the Team help you today?

The CSM drivers have been great for storage integration with Kubernetes. Thank you.  I see that rke 1.4.1 is now supported, but are these drivers being developed and supported for rke2 clusters?  From my understanding most people are now starting to use rke2 when provisioning Rancher kubernetes clusters.  We are currently planning to use rke2 to provision new clusters.

**Comment by wrender** [comment]
Ok. Even though it is not yet supported do you know if it will work?

**Comment by gallacher** [comment]
@wrender, we have not qualified RKE2 support, so we are unable to answer that question right now.

**Comment by wrender** [comment]
Ok. Thank you.
