### ISSUE TITLE
[QUESTION]: Is NFS v4.1 supported for PowerScale CSI driver

### ISSUE THREAD

**Issue by thecloudgarage** [dell/csm#736]
### How can the Team help you today?

**Details: ?**

Is NFS v4.1 supported for PowerScale CSI driver

**Comment by HarishH-DELL** [comment]
@thecloudgarage 
yes ,

**Comment by thecloudgarage** [comment]
Is there any specific setting in the PowerScale CSI driver installation procedure such that the NFS client on Tanzu Kubernetes Grid photon OS nodes use v4.1 instead v3

**Comment by brittup** [comment]
Add the mount option to the storage class that csi is using, and make sure nfs 4.1 is enabled in OneFS. 

Note: enabling nfsv4 is a global setting in onefs; once enabled, any nfs mount not specifying a version will attempt to mount at the highest level offered by onefs; this can cause existing v3 mounts to jump to v4 unless they explicitly mounting at v3(this can create issues). If v4.1 is enabled on the onefs cluster csi may just use it in this way, but I would suggest adding the mount options into the storage class.

snip from storage class

# specify additional mount options for when a Persistent Volume is being mounted on a node.
# To mount volume with NFSv4, specify mount option vers=4. Make sure NFSv4 is enabled on the Isilon Cluster
mountOptions: ["vers=4"]
