### ISSUE TITLE
CSI driver for PowerStore - support for OCP[QUESTION]:

### ISSUE THREAD

**Issue by stefanff** [dell/csm#752]
### How can the Team help you today?

Is there any information on when Openshift 4.12 support will be added?
Kind regards,
Stefan

**Comment by AkshaySainiDell** [comment]
Hi @stefanff,
OCP 4.12 support will be added in CSI-PowerStore v2.7 release. It will be available by the end of June 2023.

**Comment by stefanff** [comment]
Hi Akshay,

Thank you!


Kind regards,
Stefan

Stefan Florea
Mission Critical Services Lead

T:            +40 21 208 5800
M:          +40 726 326 409
F:            +40 21 208  5801
***@***.******@***.***>
www.kontron.ro | www.kontron.ag

***@***.***

Kontron Services Romania
58-60 Gheorghe Polizu Street | 6, 11, 12 Floors, 011062 Bucharest | Romania
***@***.*** ***@***.***

Important Note: Any form of unauthorized use, publication, reproduction, copying or disclosure of the content of this e-mail is not permitted. This message is exclusively for the person addressed or her/ his representative. If you are not the intended recipient of this message and its contents, please notify the sender immediately.

Please consider your environmental responsibility, before printing this e-mail. Ask yourself whether you need a hard copy!


On 12 Apr 2023, at 07:28, Akshay Saini ***@***.******@***.***>> wrote:



Hi @stefanff<https://github.com/stefanff>,
OCP 4.12 support will be added in CSI-PowerStore v2.7 release. It will be available by the end of June 2023.
