### ISSUE TITLE
[FEATURE]: gopowermax enhancements for PowerMax Terraform provider requirements

### ISSUE THREAD

**Issue by P-Cao** [dell/csm#770]
**Describe the solution you'd like**
Extra volume and port function need to be added for PowerMax Terraform provider development.

**Comment by doriac11** [comment]
Storage Group Snapshot functionality.

**Comment by nikitajoshi1** [comment]
Describe the solution you'd like
Snapshot Policy APIs are needed for PowerMax Terraform Provider.
