### ISSUE TITLE
[BUG]: CHAP is set to true in the CSI-PowerStore sample file in CSI Operator

### ISSUE THREAD

**Issue by AkshaySainiDell** [dell/csm#812]
### Bug Description

The CSI-PowerStore sample file in DELL CSI Operator has CHAP set to true, yet according to the documentation the default value for CHAP is false.
![image](https://github.com/dell/csm/assets/109056238/696e187b-56bc-4d97-897c-b9fd7269af4b)

The default value is correct (false) in helm but needs to be amended in CSI Operator.

### Logs

n/a

### Steps to Reproduce

Install CSI PowerStore using CSI Operator

### Expected Behavior

CHAP should be set to false by default

### CSM Driver(s)

CSI Driver for PowerStore v2.6

### Installation Type

Operator v1.11

### Container Orchestrator

OCP 4.10

### Operating System

RHEL

**Comment by alankar-verma** [comment]
The required changes have been merged into main branch. PR link - https://github.com/dell/dell-csi-operator/pull/155
