### ISSUE TITLE
[QUESTION]:PowerStore CSM Replication Module Inquiry about installation error

### ISSUE THREAD

**Issue by hiro-inada** [dell/csm#815]
### How can the Team help you today?

**Details: ?**

Refers to `https://dell.github.io/csm-docs/docs/replication/deployment/install-repctl` ,
we have CSM 1.4 for Replication installed in the Openshift 4.11, PowerStore environment.

In `4. Inject service accounts’ configs into clusters:`.
The following error occurs when executing `repctl cluster inject --use-sa`.

```
[2023-05-15 15:50:33]  INFO Generating config maps from existing service accounts
[2023-05-15 15:50:33]  INFO Generating config for service account in cluster-1 cluster
Compiling kubeconfig for "dell-replication-controller-sa"[  OK  ]
Extracting secret                                 [ FAIL ]
[2023-05-15 15:50:33]  INFO
[2023-05-15 15:50:33]  INFO Generating config for service account in cluster-2 cluster
Compiling kubeconfig for "dell-replication-controller-sa"[  OK  ]
Extracting secret                                 [ FAIL ]
[2023-05-15 15:50:33]  INFO
[2023-05-15 15:50:33]  INFO Custom configs provided, injecting them into clusters
[2023-05-15 15:50:33] FATAL cluster inject: error checking cfg /tmp/repctl/cluster-1: stat /tmp/repctl/cluster-1: no such file or directory
```

We don't know the cause, so please let me know how to deal with it.

When executing the above command, `gen-kubeconfig.sh` was created under the `/tmp/repctl` folder, and when we checked the contents, the `kubectl command` exists, but is the `kubectl` command necessary?
*Currently, we are building on Openshift, so the `oc` command exists, but `kubectl` is not installed.

Kind regards.

**Comment by falfaroc** [comment]
In the current situation, `kubectl` needs to be installed even with OpenShift for `repctl cluster inject --use-sa`. That being said, in the situation above, please use `repctl cluster inject` if you do not wish to install `kubectl`.

We will look into adding support for `oc` when `kubectl` isn't installed in the future.

**Comment by hiro-inada** [comment]
Thank you very much!! After installing `kubectl`, running `repctl cluster inject --use-sa` finished successfully.
This issue has been resolved, so it can be closed.
