### ISSUE TITLE
[BUG]: CSM object goes into failed state when deployments are getting scaled down/up

### ISSUE THREAD

**Issue by rajendraindukuri** [dell/csm#816]
### Bug Description

The CSM object is not tracking the Available count during scale down of deployment.

This affects all existing drivers. Attaching the log for reference.

snippet for when deployment is scaled down to 1 :

Here though the 

Status:
  Controller Status:
    Available:  2
    Desired:    1
    Failed:     0
  Node Status:
    Available:  2
    Desired:    2
    Failed:     0
  State:        Failed

and deployment status:

```
[root@master-1-lGshZ2jK1CelR ~]# k get deployment -n test-powerstore
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
test-powerstore-controller   1/1     1            1           24m
```

The Available state should be reflecting a value of 1 matching the current deployment available count.

### Logs

Status:
  Controller Status:
    Available:  2
    Desired:    1
    Failed:     0
  Node Status:
    Available:  2
    Desired:    2
    Failed:     0
  State:        Failed

and deployment status:
```
[root@master-1-lGshZ2jK1CelR ~]# k get deployment -n test-powerstore
NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
test-powerstore-controller   1/1     1            1           24m
```

### Steps to Reproduce

1. Install CSM Operator
2. Create CR using any of the samples under CSM Operator
3. Scale down the deployments using "k scale deployment/<deployment_name> --replicas=<n>"
4. Observe the state of CSM by "k get csm -n <namespace of the CR>"

### Expected Behavior

CSM should reflect the no of replicas as scaled and should be in succeeded state

### CSM Driver(s)

N/A

### Installation Type

CSM Operator

### Container Orchestrator

any kuberntes version supported

### Operating System

RHEL 8.5

**Comment by bharathsreekanth** [comment]
@rajendraindukuri Can we close this issue now?
