### ISSUE TITLE
[FEATURE]:Documentation update for nfsv4 mount option

### ISSUE THREAD

**Issue by Tharun-vr** [dell/csm#82]
Adding the Comment for nfsv4 mount option, in Isilon cluster NFSv4 should be set.
To mount a volume with NFSv4, specify mount option vers=4. Make sure NFSv4 is enabled on the Isilon Cluster

**Comment by prablr79** [comment]
@Tharun-vr is this addressed now ? you need any support here ?

**Comment by prablr79** [comment]
updated doc in dell/csm-docs#112
