### ISSUE TITLE
[FEATURE]: Delete PowerFlex SDC ID when Worker is Removed from Cluster

### ISSUE THREAD

**Issue by OA72280** [dell/csm#83]
**Describe the solution you'd like**
For PowerFlex systems, where SDCs are deployed on k8s workers, if the worker is permanently removed from the cluster this creates an orphaned SDC ID (GUID) 

SDC ID: d5d2119f00000025 Name: N/A IP: N/A State: Disconnected GUID:

While a new worker can be deployed and can take on the IP of that worker which had been deleted, there remains the artifact of that removed workers GUID. 

The ability to, when removing a worker or destroying a k8s cluster, to pass off to the PowerFlex gateway all the SDC IDs to be removed so as to decrease the alerts flagged in PFxM / Presentation server.

Currently, storage administrators of the PowerFlex must manually go in and remove these orphaned SDC ID's.

**Describe alternatives you've considered**

**Additional context**

**Comment by hoppea2** [comment]
Thank you for your request. We are in the process of reviewing this with regards of our product roadmap.

**Comment by hoppea2** [comment]
Hi @OA72280, we have reviewed your request and full management of the SDC on the array side currently does not align with the product roadmap for CSM. Please reach out if you have further questions.
