### ISSUE TITLE
[QUESTION]: dell csi operator for openshift 4.12

### ISSUE THREAD

**Issue by soudamsugit** [dell/csm#832]
### How can the Team help you today?

**Details: ?**

Hello Team,
we are plannign to upgrade to openshift 4.12, as per the https://github.com/dell/dell-csi-operator, there is still no compatible version for ocp 4.12

Can you please confirm we can proceed with existing 1.10.0 version for ocp 4.12 or will there be any issues?

Thanks,
Suresh

**Comment by rensyct** [comment]
Hi @soudamsugit,

We will be releasing dell-csi-operator v1.12.0 by the end of May which will have support for OCP 4.12. By second week of June, new version of Operator will be listed in OperatorHub.io. We would suggest not to proceed with existing 1.10.0 for OCP 4.12 and instead wait for the new release of operator.

Regards,
Rensy

**Comment by soudamsugit** [comment]
Thanks @rensyct

**Comment by soudamsugit** [comment]
I'll keep this open until the csi 1.12 is available.

**Comment by soudamsugit** [comment]
Hello Team,
Can you pls confirm if 1.10.0 is available now?

**Comment by rensyct** [comment]
Hi @soudamsugit 
dell-csi-operator v1.12.0 is not available yet
