### ISSUE TITLE
[BUG]: Fix csm-operator e2e replication and observability tests

### ISSUE THREAD

**Issue by donatwork** [dell/csm#853]
### Bug Description

Fixes for e2e tests where Replication and Observability on PowerScale and PowerFlex platforms.

### Logs

n/a

### Steps to Reproduce

n/a

### Expected Behavior

Tests should pass.

### CSM Driver(s)

n/a

### Installation Type

CSM-Operater 1.1.0

### Container Orchestrator

Kubernetes 1.26

### Operating System

n/a

**Comment by gallacher** [comment]
@donatwork - can you please update the bug description to include the tests that are failing and need to be fixed.  Thanks.

**Comment by donatwork** [comment]
E2e tests merged in https://github.com/dell/csm-operator/pull/278
