### ISSUE TITLE
[QUESTION]:Minimum user authority required when install CSI Driver for Powerflex

### ISSUE THREAD

**Issue by icece12** [dell/csm#867]
Hi experts,
What role is required when install CSI driver or run powerflex service in Openshift 4.11 environment? Now customers use privilege user for CSI driver installation and runtime in test environment, but they do not wanna use the privilege user in production environment, they are wondering which level of users are at least required for Powerflex CSI driver installation and runtime ?

**Comment by VamsiSiddu-7** [comment]
@icece12  Thanks for reaching out. We will look into this and get back to you.

**Comment by VamsiSiddu-7** [comment]
@icece12 
I am little confused from your question. When you are referring the user. did you mean Linux user that installs csi-powerflex driver or did you mean the Security context of the containers i.e Powerflex array user?
