### ISSUE TITLE
[BUG]: Isilon CSI driver repots: Error: Authorization required # DISCONNECTED SITE

### ISSUE THREAD

**Issue by Idan-Maimon** [dell/csm#88]
**Describe the bug**
Following Operator and CSI driver upgrade we notice the following errors on the Isilon controller:
"Error in response Method DELETE URI:platform/2/protocols/nfs/exports Error: Authorization required JSON Error: Authorization required"
Old operator version 1.2
Old CSI driver version: 1.4
New Operator version 1.5
New CSI driver version 2.0.0

Following this error message 
the CSI driver send an authentication request with the user and password, authentication succeed and the delete operation proceeding with no issue.
Next request will trigger another authentication error and the process follow.

The error will spawn for any type of request not only delete so basically the entire log is loaded with authentication issues and success
The time it takes for the operation to complete results in pods to timeout due to pvc access issues. 

**Expected behavior**
A  bearer token to be saved once and sent with each new request so the driver wont need to authenticate for any new request. 

**Screenshots**
Disconnected site 

**Logs**
Disconnected site 

**System Information (please complete the following information):**
OpenShift: 4.6.5
K8s: 1.19 
Dell Operator 1.5
CSI driver 2.0.0 
Isilon version 8.2.2.0
Isilon RUP 01-2021

**Comment by hoppea2** [comment]
Thank you @Idan-Maimon, we will investigate. This may be related to #71.
Could you supply the controller logs of the driver?

**Comment by Idan-Maimon** [comment]
Hi thanks for the comment, 
I also noticed the errors mentioned at #71 but it seems like a different issue.
in any case, once we changed the endpoint from a SmartConnect end point to a static node FQDN  the error disappear so it seems the driver is not working well with the Isilon SmartConnect mechanism.

**Comment by randeepsharma** [comment]
@Idan-Maimon could you please provide the driver logs, we need it to proceed on investigation.

**Comment by Idan-Maimon** [comment]
Hi,

Sorry for the late reply,
We are not able to send any logs out.
The error I gave was written by hand

**Comment by randeepsharma** [comment]
Hi @Idan-Maimon ,
We need to driver logs to proceed further on investigating this issue.
If you need any guidance on how to collect the logs, you could follow https://www.dell.com/support/kbdoc/en-us/000188057/container-storage-interface-csi-drivers-family-how-to-collect-driver-logs?lang=en 
Also we might need PVC, Pod and Storage Class, isilon controller and node yaml files. So please share that as well for quicker resolution of this.

**Comment by Idan-Maimon** [comment]
this is a disconnected site please work with FSS Israel T at +972-546757282

**Comment by hoppea2** [comment]
Thank you for the info. We reached out  and have the csi-isilon team get on a call early Monday morning.

**Comment by prablr79** [comment]
1. No of worker nodes that are used
2. How the load balancer is installed (how many master and worker nodes)
3. In the controller logs , grep for session based authentication logs
4. What are the steps customer performed while getting the timeout error in the log (only timeout error)
2. after re-authentication successful message how many requests are successful before getting timeout error

Note: Session based authentication is by default OneFS 9.1

**Comment by prablr79** [comment]
@Idan-Maimon looking for updates on this request, so that we can help customer.

**Comment by prablr79** [comment]
@Idan-Maimon we need to move forward in this case, help us with information so that we can provide necessary help.

**Comment by prablr79** [comment]
@Idan-Maimon any information on this issue will help us move forward, feel free to connect in SLACK channel.

**Comment by gallacher** [comment]
@Idan-Maimon, closing the issue for now.  Please feel free to reopen the issue when the necessary information is provided.
