### ISSUE TITLE
[FEATURE]: PowerFlex SDC log collection documentation

### ISSUE THREAD

**Issue by atye** [dell/csm#903]
**Describe the solution you'd like**

There are scenarios where the SDC logs need to be collected. We have something about this on the [docker hub page](https://hub.docker.com/r/dellemc/sdc) under "Debug and Logs Collection" but it needs more information about enabling monitoring in CSI-PowerFlex, what to do if the SDC was installed manually, step-by-step instructions, etc. This information should also be in csm-docs.

**Comment by bharathsreekanth** [comment]
@atye SDC monitor is a container maintained outside of the CSM team. I don't think we should include any documentation around that in CSM docs, but maybe point to a reference in the PowerFlex docs that will enable users to reference the appropriate information.
