### ISSUE TITLE
[QUESTION]: Is it allowed that multiple Pods running on a single Node access the same PVC with Isilon CSI Driver v1.2.0?

### ISSUE THREAD

**Issue by RyanBao** [dell/csm#906]
It's a case on Isilon CSI Driver v1.2.0 with H700 (v9.2.0), PVC accesss mode is RWX: It's found that during Pods rolling restart, some PVCs failed to be mounted because the node's Client IP was lost in Isilon NFS Exports. After restarting the Pods again and then the Client IP was automaticly added, the mount of PVCs would be OK. 

According to the CSI Driver code, Client IP is removed in Node Pod Function [NodeUnstageVolume](https://github.com/dell/csi-powerscale/blob/v1.2.0/service/node.go#L125). Considering the situation that two or more Pods running on a single Node accessing the same PVC, if one Pod is terminated, Client IP of the Node will be removed from NFS Exports, then other Pods will fail to access the PVC, is that will happen?

So, should it be avoided to let multiple Pods on a single Node to access the same PVC? 

Thanks a lot.

**Comment by coulof** [comment]
Hi @RyanBao,
I can't answer on the logic about the CSI driver, I will let @nitesh3108 and @bpjain2004.
w.r.t. to the question:
>So, should it be avoided to let multiple Pods on a single Node to access the same PVC?

You can control that with the access modes, with `ReadWriteOncePod` (which more recent versions of the driver support) you can make sure a Pod can only mount the PVC he owns with `ReadWriteOnce` allow multiple Pods on the same node to mount the same share.

`ReadWriteMany` means the volume can be mounted as read-write by many nodes and any pods of the nodes.

The CSI driver for Isilon v1.2.0 is 3+ years old and not supported anymore. I would highly recommend you update it.

**Comment by chimanjain** [comment]
Your use-case is supported by the csi-driver and it's always recommended to use the latest version of the driver.
