### ISSUE TITLE
If below version is support CSI for Powerstore

### ISSUE THREAD

**Issue by fcflsdly** [dell/csm#91]
Dears:

We have a customer want to install the csi for powerstore. Would you pls help to check if below software version support or not?Tks.

PowerStore:      2.0.1.0
OS Version:      RedHat 7.6
Kernel Version :        54.145-1.el7.elrepo.x86_64
Kubernetes：   1.20.9
Rancher:             2.5.9
Docker version     20.10.6, build 370c289
calico:               3.17.2
etcd:                 3.4.15
nginx-ingress:  0.43.0

**Comment by prablr79** [comment]
@fcflsdly Please do check here https://dell.github.io/csm-docs/docs/csidriver/

**Comment by prablr79** [comment]
@fcflsdly closing this comment, if you need any further assistance please feel free to contact us.
