### ISSUE TITLE
[QUESTION]:  csi-cert template is not updated in doc

### ISSUE THREAD

**Issue by vincent1chen** [dell/csm#914]
### How can the Team help you today?
I could get the CSI cert configuration template from two places both places don't show a full configuration template, like

    VolumeHealth: true
    RWOP: true
    VGS: true
 
but from documents or CLI help list,  I know CSI cert support these tests.  please update full template as  example in doc  

https://dell.github.io/csm-docs/docs/csidriver/installation/test/certcsi/#launching-certification-test-run

https://github.com/dell/cert-csi/blob/main/example-certify-config.yaml

**Comment by adarsh-dell** [comment]
Hi @vincent1chen Before I proceed to update the documentation, I wanted to confirm with you whether you've tested running these test suites by configuring the fields in the `config.yaml` file. Have you successfully executed all suites using the `certify` command?

**Comment by vincent1chen** [comment]
@adarsh-dell ,  i use config.yaml as template in my test.  it include a full feature list.

**Comment by adarsh-dell** [comment]
@vincent1chen If I understood the requirement correctly, you're requesting us to incorporate additional suites (if it is supported but missing in the sample file) into the template and revise the documentation so that they can be executed using the certify command, correct ?

**Comment by vincent1chen** [comment]
Yes, Adarsh. That's my request.

**Comment by adarsh-dell** [comment]
Hi @vincent1chen The requested changes have been completed and will be available from CSM1.8 onwards.
