### ISSUE TITLE
[QUESTION]: Getting error while using scaleio GO package

### ISSUE THREAD

**Issue by Diwahars** [dell/csm#924]
### How can the Team help you today?

**Details: ?**
im trying to use https://github.com/dell/goscaleio... when i trying to use this package... i'm getting following error

# github.com/dell/goscaleio
..\..\..\go\pkg\mod\github.com\dell\goscaleio@v1.11.0\drv_cfg.go:221:38: undefined: syscall.SYS_IOCTL

i'm running go version 1.20

could you help me here?

**Comment by hoppea2** [comment]
@Diwahars which version of the driver are you using? Can you run `go version` in your environment? Thanks.

**Comment by Diwahars** [comment]
go version go1.20.3 windows/amd64

i'm trying to github.com/dell/goscaleio v1.11.0

**Comment by Diwahars** [comment]
I'm trying to build a code separate to get some data. during build i'm getting this error.

**Comment by hoppea2** [comment]
Can you verify the command you're running?
I recommend upgrading go to >= 1.20.4 and retry

**Comment by Diwahars** [comment]
Yea... my go version = 1.20.7

command i use to run:
go run .\main.go
# github.com/dell/goscaleio
..\..\..\go\pkg\mod\github.com\dell\goscaleio@v1.11.0\drv_cfg.go:221:38: undefined: syscall.SYS_IOCTL

**Comment by Diwahars** [comment]
do you have any example to connect and getinstance?

**Comment by hoppea2** [comment]
@Diwahars this looks like an environmental issue. Make sure your have the /src/syscall dir in your env, example:  '/usr/local/go/src/syscall'. Based on the Linux environment you're using, that folder should contain various definitions of SYS_IOCTL. Check our docs for suporter Linux flavors.

**Comment by Diwahars** [comment]
Sure. Let me check that... do you have any example for connecting powerflex and getinstance in GOLang?

**Comment by hoppea2** [comment]
@Diwahars https://github.com/dell/csi-powerflex has example of connecting to PowerFlex

**Comment by Diwahars** [comment]
Thanks. is there a possibility to release windows based binary?

**Comment by hoppea2** [comment]
Hi @Diwahars no plans on our end. You may find solutions out there when you search for the undefined: syscall.SYS_IOCTL error in the context of Windows.

**Comment by hoppea2** [comment]
Closing for now.
