### ISSUE TITLE
[QUESTION]:  Dell CSI Driver Upgrade v1.12.0  - Harware requirements

### ISSUE THREAD

**Issue by soudamsugit** [dell/csm#942]
### How can the Team help you today?

**Details: ?**

We are planning to upgrade to Dell CSI Drive v1.12.0, can you please let us know if the unispehere need to be upgraded to version 10? I mean is there any dependency or does Unisphere 9 support v1.12.0

**Comment by hoppea2** [comment]
Hi @soudamsugit, assuming you're referring to CSI-PowerMax driver, support for Unisphere 9 was deprecated with [v.2.4.0.](https://github.com/dell/csi-powermax/releases/tag/v2.4.0) 
Let us know if this answered your question. Thanks!

**Comment by soudamsugit** [comment]
Hello @hoppea2 , Yes, referring to CSI PowerMax Driver, we are planning to upgrade to v2.7 does unisphere 9 support this or does it need to be upgraded to version 10

**Comment by hoppea2** [comment]
@soudamsugit Unisphere 10 is required from v2.4.0 onwards.

**Comment by coulof** [comment]
@soudamsugit, you can use a dedicated Unisphere 10 without upgrading the embedded one.

HTH

/assign

**Comment by shanmydell** [comment]
Closing the issue, as the question is addressed
