### ISSUE TITLE
[QUESTION]: multipath for the Dell CSI Operator 1.10 (CSI PowerMax 2.4)

### ISSUE THREAD

**Issue by soudamsugit** [dell/csm#943]
### How can the Team help you today?

Hello Team,

We are running  Dell CSI Operator 1.10 (CSI PowerMax 2.4) on openshift 4.10.
Can you please let me know if there are any vendor recommended multipath configurations?

This has hit us couple of times in production and would like to check your recommendations.

**Comment by coulof** [comment]
Hi @soudamsugit,
A sample `MachineConfig` can be found in the documentation here : https://dell.github.io/csm-docs/docs/deployment/csmoperator/drivers/powermax/#linux-multipathing-requirements

Can you share more details on the issue you faced ?

**Comment by shanmydell** [comment]
As the question is answered, closing it
