### ISSUE TITLE
[BUG]: PowerScale installation script for upgrade fails

### ISSUE THREAD

**Issue by santhoshatdell** [dell/csm#953]
### Bug Description

PowerScale installation script for upgrade fails now. It used to work.

Command used: 
./csi-install.sh  --namespace isilon  --values /xxx/powerscale/values.yaml --upgrade --skip-verify

### Logs

> Installing CSI Driver: csi-isilon on 1.28
......
Error: The CSI Driver is already installed
Installation cannot continue

### Steps to Reproduce

Run install script with upgrade flag

### Expected Behavior

Upgrade should work

### CSM Driver(s)

CSI Driver for PowerScale v2.8.0

### Installation Type

Install script

### Container Orchestrator

K8s 1.28

### Operating System

RHEL 8.7

**Comment by HarishH-DELL** [comment]
PR merged , issue been addressed
