### ISSUE TITLE
[QUESTION]:how to get statistics for each SDS?

### ISSUE THREAD

**Issue by Diwahars** [dell/csm#957]
### How can the Team help you today?

**Details: ?**
how to get statistics of each SDS?

**Comment by khareRajshree** [comment]
Hi @Diwahars, using the goscaleio library one can get the SDS statistics, https://github.com/dell/goscaleio/blob/main/sdc.go#L158. Hope that helps here.
Thanks.

**Comment by VamsiSiddu-7** [comment]
Hi @Diwahars 
If you are using scli you can use the following command to get the sds's list.
` scli  --mdm_ip "ip of the mdm"  --query_all_sds`
for each of the sds's entry you can get the sds statistics using the below command
`scli  --mdm_ip "ip of the mdm"  --query_sds --sds_id "id of the sds"`

**Comment by VamsiSiddu-7** [comment]
If you are using PowerFlex Rest Api:
to get all SDS instances
`https://{{powerflex_gateway_endpoint}}/api/types/Sds/instances`
for each SDS entry you can get the SDS statistics  using id in the path should be SDS id
`https://{{powerflex_gateway_endpoint}}/api/instances/Sds::{id}/relationships/Statistics`

**Comment by bharathsreekanth** [comment]
@Diwahars Does the reply from @VamsiSiddu-7 help answer your question? Please update us. thanks
