### ISSUE TITLE
Cert issue with software product CSM Operator for PowerFlex - CSI Driver for Dell PowerFlex w/Observability

### ISSUE THREAD

**Issue by gearoidcleary** [dell/csm#961]
hi all, 
I recently received a case for an issue  where the customer was  having  errors on certificates when trying to install drivers and the observability is not working. It is crashing when they try to run it.

A workaround was found but the customer wants to  know can the following be added to a troubleshooting guide or an install guide:

"Firstly I have deployed the observability driver as the guide says I have checked a hundred times. 
I have already solved the issue and would like for you to check it out and consider adding it to the offline bundle or at least the troubleshooting page.
My problem wasn't about the observability code but with the cert manager.

Once I deployed the driver (it said success) the openshift api was spammed with errors:
"Cacher (unstructed.unstructed) : unexpected ListAndWatch error: failed to list cert-manager.io/v1alpha3 [cert-manager.io], kind=certificateRequest: conversion webhook for cert-manager.io/v1 [cert-manager.io], kind=certificateRequest failed: post https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s [cert-manager-webhook.cert-manager.svc]: service cert-manager-webhook not found; reinitializing..."

After a few minutes the openshift broke down the gui stopped working and we had to delete the certificate and issuer objects to stop the errors.
So for the last week I have been researching the cert manager and I have found 2 issues that solved my problem.

1.The first is that according to google, cert manager needs us to already have a cluster issuer which not everyone already has - we didn't. 
To create one I had to generate a ca certificate with openssl and then create an openshift secret from it, then I created a clusterissuer using the secret.
 
2.The second thing is that for some reason the error points to not being able to access a service which exists (comes with the bundle with cert manager), 
so I went into karavi-observablity/charts/cert-manager/values.yaml  , there is a port specification for secure port which points to port 10250, this is the default which comes with cert manager
but I read about it and found that this port is sometimes used by kubelet, this is the port webhook should listen for requests which is fitting for my error exactly, 
in addition there was a recommendation on the net ro change the parameter hostNetwork to true I am not sure this had anything to do with my problem but I tried it anyway. 

All of those together fixed my issue so you can close the issue at dell but I would really appreciate if you could consider my words."

Let me know if this is the correct channel to post this query.

Regards, 
Gearóid

**Comment by bharathsreekanth** [comment]
@gearoidcleary Could you help provide the version of CSM operator/driver/observability that you were trying to deploy. Also, provide the version of cert-manager that was used. Thanks.

**Comment by shanmydell** [comment]
@gearoidcleary : Please provide the necessary information as requested and reopen the ticket if you are still facing the issue, thanks
