### ISSUE TITLE
[BUG]: Creating StorageClass for replication failed with unmarshal error

### ISSUE THREAD

**Issue by yutaro-satomi** [dell/csm#968]
### How can the Team help you today?

**Details: ?**
We installed CSI Driver for Dell PowerStore and CSM for Replication on OpenShift.
When trying to create a StorageClass for replication, the following error occurred.
```
$ oc create -f powerstore-replication-ext4.yaml
Error from server (BadRequest): error when creating "powerstore-replication-ext4.yaml": StorageClass in version "v1" cannot be handled as a StorageClass: json: cannot unmarshal bool into Go struct field StorageClass.parameters of type string
```

The StorageClass Manifest was created based on [the sample on GitHub](https://github.com/dell/csi-powerstore/blob/main/samples/storageclass/powerstore-replication.yaml).
The same error will occur even if the sample manifest is applied as is.

We don't know the cause, so please let us know how to deal with it.

Here is our environment details:
- PowerStore 1200T
- OpenShift Container Platform 4.12.28
- CSI Driver for Dell PowerStore 2.7.0
- CSM for Replication 1.5.0

Kind regards.

**Comment by donatwork** [comment]
Looks like line 34 (replication.storage.dell.com/isReplicationEnabled: true) should be a string. Will need to check the public docs but you could try enclosing the value in quotes to see if you get past the error. I'll take a look to see how it is used.

**Comment by brianlucey** [comment]
Line should read : 

replication.storage.dell.com/isReplicationEnabled: "true"

**Comment by santhoshatdell** [comment]
Right. Only the PowerStore driver sample file seems to have this issue, other driver repository sample files are correct. I will see if I can correct the PowerStore sample file.
Please refer to the CSM-Docs for any detail needed for any of these inputs at https://dell.github.io/csm-docs/docs/replication/deployment/powerstore/

Also provide the bool value for _replication.storage.dell.com/ignoreNamespaces_ within quotes.

**Comment by yutaro-satomi** [comment]
After enclosing the bool values in quotes as per the documentation, the StorageClass was successfully created.
This issue has been resolved, so it can be closed.
Thank you for your support.

**Comment by santhoshatdell** [comment]
Sample file has been corrected as part of PR https://github.com/dell/csi-powerstore/pull/272
