### ISSUE TITLE
Does Dell CSI Driver ver 2.7 Support Openshift 4.11 and K8S 1.24 ?

### ISSUE THREAD

**Issue by dlavi** [dell/csm#979]
### How can the Team help you today?

**Details: ?**

**Comment by adarsh-dell** [comment]
Hi @dlavi ,

JFYI, You can visit csm-doc portal anytime to see our support matrix. You can find it on below link:

https://dell.github.io/csm-docs/docs/csidriver/
![image](https://github.com/dell/csm/assets/109620911/31b7c423-d7c0-4e49-8e6f-33e226c45f42)


To see what specific version of csi-driver was released as part of CSM x.y.z release, you can navigate to below page:
https://dell.github.io/csm-docs/docs/csidriver/release/

**Comment by adarsh-dell** [comment]
@dlavi If the comment above have been helpful for your query, please feel free to close this GitHub issue.

Regards,
Adarsh

**Comment by dlavi** [comment]
Lavi, Doron ***@***.***) has sent you a protected message.
                                          Read the message            Learn about messages protected by Microsoft Purview Message Encryption.        
    
    
    
        
           Privacy Statement        
    
    
        
              Learn More on email encryption.             Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

**Comment by adarsh-dell** [comment]
Hi @dlavi Can you please add a comment on github directly, once you are available, we are unable to open the contents shared over mail.
Thanks

**Comment by shanmydell** [comment]
Please feel free to reopen the issue if the answer is not helpful
