### ISSUE TITLE
[BUG]: Name is getting printed in the log.

### ISSUE THREAD

**Issue by Tharun-vr** [dell/csm#98]
**Describe the bug**
If we check the controller and node log , developer name is coming In there.

**To Reproduce**
1. install driver..
2. create PVC,pod.
3. check the controller and node log. ...

**Expected behavior**
In logs dev name should not come.

**Screenshots**
![image](https://user-images.githubusercontent.com/91600716/141526667-e043d4bd-8384-4a42-873d-639bc5ef030c.png)

**Comment by prablr79** [comment]
@Tharun-vr  thank for reporting, looks like you are not using nightly build to validate here, especially podman build is not consumed with UBI image, hence its not valid bug closing it.
