### ISSUE TITLE
[QUESTION]: CSI documentation - Support matrix

### ISSUE THREAD

**Issue by maiti0706** [dell/csm#981]
### How can the Team help you today?
The way CSI support matrix is displayed in documentation, it takes time to digest the table, especially regarding "access mode". Why not to create a more consistent way of representation for people to figure out quickly something like below 

![image](https://github.com/dell/csm/assets/12999402/c718446e-63a5-44c7-b9d7-40396d5ae782)

Also, there is always a confusion when to use Dell CSI and VMware CSI/CNS in a VMware env. I think it would be better to state in form of separate table about CSI support for Baremetal, VMware and non-VMware hypervisor specifying preferred and supported drivers for FC and IP connectivity. 
[CSI Access mode.xlsx](https://github.com/dell/csm/files/12597010/CSI.Access.mode.xlsx)

**Details: ?**

**Comment by gallacher** [comment]
Hi @maiti0706.  Thank you for your feedback in regards to the support matrix portion of our documentation.  This feedback will be taken into consideration as we look drive improvements in the documentation of the next release and beyond.  Thank you.
