### ISSUE TITLE
[BUG]: PowerMax : Driver installation is failing

### ISSUE THREAD

**Issue by boyamurthy** [dell/csm#99]
while installing the driver using helm , it is failing with below error .

Press 'y' to continue or any other key to exit: y
|
|- Installing Driver                                                Error: template: csi-powermax/templates/node.yaml:90:88: executing "csi-powermax/templates/node.yaml" at <.Values.images.driver>: nil pointer evaluating interface {}.driver

------------------------------------------------------
Error: Helm operation failed, output can be found in /tmp/csi-install.1049175.out. The failure should be examined, before proceeding. Additionally, running csi-uninstall.sh may be needed to clean up partial deployments.
Installation cannot continue

it is regression of the PR :  https://github.com/dell/csi-powermax/pull/31 

**To Reproduce**

Install the driver using helm command "bash  csi-install.sh  --namespace=powermax --values=../helm/csi-powermax/values.yaml"

**Expected behavior**
 Driver should install successfully 

**System Information (please complete the following information):**
  k8 1.20  version

**Comment by shanmydell** [comment]
Issue is fixed and PR has been raised to fix in all CSI drivers 
https://github.com/dell/csi-powermax/pull/32
https://github.com/dell/csi-powerscale/pull/28
https://github.com/dell/csi-powerflex/pull/42
https://github.com/dell/csi-unity/pull/32
https://github.com/dell/csi-powerstore/pull/25
