### ISSUE TITLE
[QUESTION]: Dell CSI Operator to CSM

### ISSUE THREAD

**Issue by yoyz** [dell/csm#995]
### How can the Team help you today?
On the following document : 
https://dell.github.io/csm-docs/docs/csidriver/upgradation/drivers/operator/

It say the following : 
The Dell CSI Operator is no longer actively maintained or supported. It will be deprecated in CSM 1.9. It is highly recommended that you use [CSM Operator](https://dell.github.io/csm-docs/docs/deployment/csmoperator) going forward.

But there is no document link which describe how to move from Dell CSI Operator to Dell CSM.

**Comment by gallacher** [comment]
Hi @yoyz.  There is a feature in place to handle this in our next milestone: https://github.com/dell/csm/issues/996.

Can you provide some information on your current setup/configuration - CSI Driver/Platform, Container Orchestrator, etc.  Just to help understand your particular migration use case.

**Comment by yoyz** [comment]
Hi @gallacher !

Thanks for this feature ! 
The platform is a dell powerstore.
It use dell-csi-operator-certified.v1.12.0 on top of openshift 4.12.

**Comment by gallacher** [comment]
@yoyz, in the context of the CSI Operator, are you using the OpenShift UI or CLI?

**Comment by gpulido-redhat** [comment]
> @yoyz, in the context of the CSI Operator, are you using the OpenShift UI or CLI?

Hello, we are using both the web UI and CLI of OpenShift, depending on the specific task that we need to perform.

**Comment by yoyz** [comment]
@gallacher we both work together on this topic.

**Comment by shanmydell** [comment]
Migration of CSI operator to CSM will be documented in the upcoming release.
