### ISSUE TITLE
[FEATURE]: Dell CSI to Dell CSM Operator Migration Process

### ISSUE THREAD

**Issue by gallacher** [dell/csm#996]
**Describe the solution you'd like**
Dell CSI Operator is deprecated starting Q4 2023 (CSM 1.9). This feature is to put a transition path in place to adopt CSM Operator without having to re-create an environment.  Dell CSI Operator only support CSI Drivers, but users could have modules installed as well. The transition path will cover both drivers and modules. 

Transition path from an older CSI Operator to the new CSM Operator is essential for existing users to continue using CSM in their environment.

**Describe alternatives you've considered**

**Additional context**

**Comment by shefali-malhotra** [comment]
Completed
