### ISSUE TITLE
Customer has a RedHat OpenShift 4.12.8, CSM, and PowerStore version 2.1.0.1. Needs to know if this is supported. And a step by step process to implement it

### ISSUE THREAD

**Issue by hignir** [dell/csm#998]
[closed_caption.txt](https://github.com/dell/csm/files/12831626/closed_caption.txt)
Customer has a RedHat OpenShift 4.12.8, CSM, and PowerStore version 2.1.0.1. Needs to know if this is supported. And a step by step process to implement it

**Comment by adarsh-dell** [comment]
Hello @hignir,

Is the version 2.1.0.1 of PowerStore referring to the PST Array version? 
Which CSI-PowerStore driver version are you planning to install?

Thank you,
Adarsh

**Comment by hignir** [comment]
Yes it is the PowerStore version. I just know that it is Container Storage Manager

**Comment by adarsh-dell** [comment]
@hignir JFYI, You can always check the supported CO, CSI-Driver and Storage version on below link, based on the CSM release:
https://dell.github.io/csm-docs/docs/csidriver/
![image](https://github.com/dell/csm/assets/109620911/a77e1598-41e9-43af-a73b-959b177031b6)

**Comment by adarsh-dell** [comment]
> Yes it is the PowerStore version. I just know that it is Container Storage Manager

Which CSI-PowerStore driver version are you planning to install?

**Comment by hignir** [comment]
That is what they need to know. Which driver is supported. When they downloaded upgraded OpenShift to 4.12.8 it made them use CSM instead of CSI. And then they found a chart that made it look like CSM was not supported by PowerStore

**Comment by adarsh-dell** [comment]
Hello @hignir, I trust that your query has been resolved following our discussion on Teams. May I go ahead and close it?

**Comment by adarsh-dell** [comment]
This GitHub issue is being marked as resolved after a discussion with @hignir, as the query has already been addressed through offline communication.
